Tot in aceasta operatie s-a dori niste filtre nu doar dupa termenele din poz com livr ci si dupa termenele din poz com aprov legate prin pozaprov de poz com livr,in cazul in care exista aceste legaturi.Iar daca nu exista s-ar dori ca filtrul sa ia termenele din tabela termene din contractele furnizorilor care sunt stabiliti in nomencl.furnizor pe aceste coduri din com livr.Tot aici s-ar dori cant comandata din macheta op centr com livr sa fie cea de la aceste termene din tabela termene si nu pozcon.cantitate.Aceste modificari si cele din sesizarea de legatura ne directioneaza catre o procedura specifica(tip ProcGen...),ce ar putea fi apelata dupa popularea implicita a tabelelor de catre operatie,si care sa aiba in acelasi timp disponibili parametrii cu care s-a executat operatia,intr-un mod asemanator cu ce ati facut pt op de gen com aprov (ses 228965)

1. Cerinta de filtrare dupa termene din comanda de aprovizionare mi se pare neriguroasa. 2. Mai mult, filtrarea dupa termene din contract furnizor si apoi "nomencl.furnizor" mi se pare cu totul neclar. 3. Cantitatea comandata (reamintesc: suntem in Centralizatorul de comenzi livrare!) nu are niciun sens sa fie luata din detaliile pozitiei de contract furnizor (tabela termene). Inteleg ca se doreste un alt fel de Centralizator, care nu poate fi realizat/intretinut in ASiSplus. O varianta ar fi realizarea lui in ASiSria cu etapele: - realizam noi varianta standard, cu functionalitatile din sesizarile de legatura - procedurile fiind publice, puteti realiza alta varianta de Centralizator (copiere si modificare) cum doriti Este de interes realizarea Centralizatorul de comenzi livrare (de aprobare in functie de stoc) in ASiSria?

Imi cer scuze ca am formulat gresit problema,care defapt se imparte in doua.Va voi descrie intai situatia de aici:clientul trateaza termenele declarate in comenzile de livrare foarte riguros si le urmareste implinirea lor exacta atat ca data cat si cantitate livrata(nu se doreste livrarea de mai putin dar nici mai mult pt ca ar putea face imposibila livrarea altor comenzi,nefiind stoc aprovizionat mai mult decat s-a comandat pt articolele nestocabile).Din acest motiv termenele sunt tratate aproape ca si clauze contractuale.Dar nu se pot folosi termenele din contracte beneficiari pt ca nu toate com de livr au asociat un contract si daca totusi au,nu toate codurile din com de livr se regasesc neaparat si in contract,si pt ca deja folosim acele termene din contr benef pentru a retine scadenta in zile de livrare pt fiecare articol in parte ca diferenta de zile intre data contr benef si termen(asta e singura solutie gasita pe moment pentru a putea face importul contr benef).cont pe 

Am fost nevoiti sa folosim aceasta solutie pt ca in pozitii contr benef nu avem coloana scadenta ca in antet;dar daca aveti alta solutie va rugam sa ne spuneti.Este nevoie de aceasta scadenta per articol aici din cauza ca au obiecte greu de transportat,ex chiller,care nu merg odata cu restul articolelor din com de livr ci separat,si dureaza mai mult,si de aprovizionat si de livrat.Din aceasta cauza avem nevoie de acele pozitii cu termene si in com livr daca se poate(aceasta fiind a doua problema a acestor sesizari,nespecificata explicit anterior),ele fiind declarate si urmarite separat pe fiecare com de livr in parte pt fiecare cod in parte.Ex:o poz de livr chiller(val mare si greu de transp) cu o cantitate de 3:A-Se aproba 1 care este pe stoc la data curenta,se declara termenul ziua de azi plus 30 zile daca nu exista contr benef,iar daca exista se pune termen=azi+scadenta din poz contr benef (care aici e data_contr - termen_articol_contr) ca timp necesar de livrare. cont pe

B-Exista deja o com de aprov care nu are atasata alta com de livr in detalii pt acest articol,se adauga al doilea termen de livrare=termen de aprov din acea com de aprov deja lansata de pe pozitia cu acest articol,cu inca 1 cant.C-Nu mai exista alte com aprov disponibile,se adauga un al treilea termen de livrare=azi+zile scadenta din contr furnizorului declarat in nomenclator pt acest articol,de pe pozitia de contr furnizor cu acest articol ca diferenta dintre data contr furniz si termen pozitie articol,daca exista contr furnizor,altfel data de azi+30 zile cu cant de 1 ramasa,urmand ca la op de gen com aprov sa se genereze o pozitie cu aceasta cant de 1 ramasa,cu acest termen.Termenele sunt declarate de la inceput si transmise clientului.Dupa confirmare se face fact cu acea poz aprobata de 1 care era deja pe stoc.La realiz primei com de apov prin RM se revine pe aceasta com de livr si se completeaza aprob=1+1(aici intervine op centr com de livrare,problema initiala a acestor sesizari)

In concluzie am avea nevoie de:1-pozitii cu termene si in com de livr pt fiecare articol in parte(ca in contracte) pentru a putea fi introduse termenele de livrare aici.In plus fata de ceea ce este in contracte am avea de un camp in care sa specifice clientul de unde se face livrarea(din stoc, dintr-o com de aprov existenta sau din una viitoare) pentru a putea sti tot el de unde a declarat ca va livra la acel termen.In ex de mai inainte sa zicem ca azi ar fi 18.01.2012 data primei livrari-el va completa"din stoc",al doilea termen din com de aprov deja lansata la operarea com de livr ar fi 02.02.2012-data receptie com aprov+30zile-timp livrare=17.02.2012-"din aprovizionare",iar al treilea termen ar fi data com de livr 18.01.2012+30zile timp aprovizionare+30zile timp livrare=18.03.2012-"din contract furnizor"

2-a doua cerinta ar fi ca centr de com livr sa poate aduce cantitatile din acele pozitii de termene din com de livr,de pana la data specificata in filtrare.tinand cont ca la fiecare din aceste termene vom avea cate o cant de 1,centr de com livr ar trebui sa aduca o cant comandata de 2,pt un filtru pus de la 18.01.2012 pana la 17.02.2012 care este si data de azi cand rulez centralizatorul pt a vedea cat am de livrat si pt completare aprobat pe com de livr care sunt de livrat astazi.Este nevoie de acest centralizator pt a completa cant aprob pe acele com de livr facturate deja partial care sunt in starea realizat,si nu pot fi modificate manual si nici schimbata starea si pentru o operare centralizata a acestor modificari la com de livr deja facturate pt a evita greseala de operare.Dupa actualizarea cant aprob din centr com livr se face rezervarea automat tot din centralizator sau facturarea de pe comanda.

Nu putem astepta pana se trece la ria aici,clientul incepe inca de acum lucrul in aceasta maniera.Termenele deocamdata sunt declarate in acele termene folosite in contracte,la un loc cu scandeta,iar filtrarea in prezent se face doar dupa termenele din poz com livr care nu sunt suficiente in cazul in care sunt mai mult de o facturare(si se poate ajunge si la mai mult de 3 facturari partiale aici) si nici nu pot fi modificate de la o facturare la alta fiindca com de livr intra in starea realizat.Solutia mai rapida pt noi ar fi aducerea acelor termene sin in com de livr pe fiecare cod in parte si o procedura specifica atasata op centr com de livr.