SELECT (select val_alfanumerica as nume from par where tip_parametru='GE' and parametru='NUME') as C001, max(n.denumire) as C002, max(n.cod) as C003, max(n.um) as C004, ISNULL(REPLACE(REPLACE((select REPLACE(rtrim(CONVERT(varchar,SUM(p.cantitate)))+'_'+rtrim(isnull(max(n.UM),'')) +'_cu_'+RTRIM(p.Tip)+'_'+rtrim(p.numar)+'_din_'+rtrim(convert(varchar,p.data,102)),' ','_') from pozdoc p where p.Subunitate=s.Subunitate and p.Tip='TE' and p.Factura=s.Contract and p.Gestiune_primitoare=s.Cod_gestiune and p.Grupa=s.Cod_intrare and p.stare not in ('4', '6') and p.cantitate>0 GROUP BY p.Tip,p.Numar,p.Data FOR XML PATH('')),' ','_'),'_',' '),'') as C005, 'INCREMENT' as C006, MAX(s.COD_GESTIUNE) as C007, ISNULL(REPLACE(REPLACE((select REPLACE(rtrim(CONVERT(varchar,SUM(p.cantitate)))+'_'+rtrim(isnull(max(n.UM),'')) +'_cu_'+RTRIM(p.Tip)+'_'+rtrim(p.numar)+'_din_'+rtrim(convert(varchar,p.data,102)),' ','_') from pozdoc p where p.Subunitate=s.Subunitate and p.Tip='AP' and p.Contract=s.Contract and p.Gestiune=s.Cod_gestiune and p.Cod_intrare=s.Cod_intrare and p.cantitate>0 GROUP BY p.Tip,p.Numar,p.Data FOR XML PATH('')),' ',';'),'_',' '),'') as C008, convert(char(12),s.data,104) as C009, ISNULL(REPLACE(REPLACE((select REPLACE(rtrim(p.contract)+'_pt_'+RTRIM(max(t.denumire))+'_cod_'+rtrim(p.tert),' ','_') from pozcon p left join terti t on t.Subunitate=p.Subunitate and t.Tert=p.Tert where p.Subunitate=s.Subunitate and p.Tip='BK' and p.Contract=s.Contract GROUP BY p.Contract,p.Tert FOR XML PATH('')),' ',';'),'_',' '),'') as C010, rtrim(s.cod_intrare) as C011, SUM(s.stoc) as C012, (select sum(st.stoc) from stocuri st where st.subunitate=s.subunitate and st.Tip_gestiune NOT IN ('F','T') and st.Contract<>'' AND max(par.Val_logica*1)=1 AND CHARINDEX(';'+RTRIM(st.cod_gestiune)+';',';'+RTRIM(max(par.Val_alfanumerica))+';')>0 AND st.Stoc>0.001 and st.cod=s.cod ) as C013,'' AS C014,'' AS C015,'' AS C016,'' AS C017,'' AS C018,'' AS C019,'' AS C020,'' AS C021,'' AS C022,'' AS C023,'' AS C024,'' AS C025,'' AS C026,'' AS C027,'' AS C028,'' AS C029,'' AS C030,'' AS C031,'' AS C032,'' AS C033,'' AS C034,'' AS C035,'' AS C036,'' AS C037,'' AS C038,'' AS C039,'' AS C040,'' AS C041,'' AS C042,'' AS C043,'' AS C044,'' AS C045,'' AS C046,'' AS C047,'' AS C048,'' AS C049,'' AS C050,'' AS C051,'' AS C052,'' AS C053,'' AS C054,'' AS C055,'' AS C056,'' AS C057,'' AS C058,'' AS C059,'' AS C060,'' AS C061,'' AS C062,'' AS C063,'' AS C064,'' AS C065,'' AS C066,'' AS C067,'' AS C068,'' AS C069,'' AS C070,'' AS C071,'' AS C072,'' AS C073,'' AS C074,'' AS C075,'' AS C076,'' AS C077,'' AS C078,'' AS C079,'' AS C080,'' AS C081,'' AS C082,'' AS C083,'' AS C084,'' AS C085,'' AS C086,'' AS C087,'' AS C088,'' AS C089,'' AS C090,'' AS C091,'' AS C092,'' AS C093,'' AS C094,'' AS C095,'' AS C096,'' AS C097,'' AS C098,'' AS C099,'' AS C100 
FROM STOCURI s 
left join GESTIUNI g ON s.Subunitate=g.Subunitate and s.Tip_gestiune=g.Tip_gestiune and s.Cod_gestiune=g.Cod_gestiune 
left join NOMENCL n on n.Cod=s.Cod 
left join avnefac on avnefac.Subunitate=s.Subunitate and avnefac.Factura=s.Cod 
left JOIN con ON avnefac.subunitate=con.subunitate and avnefac.tip=con.tip and avnefac.contractul=con.contract and avnefac.cod_tert=con.tert and avnefac.data=con.data 
left JOIN pozcon ON pozcon.subunitate=con.subunitate and pozcon.tip=con.tip and pozcon.contract=con.contract and pozcon.data=con.data and pozcon.tert=con.tert 
LEFT JOIN terti ON terti.subunitate=con.subunitate and terti.tert=con.tert 
LEFT JOIN par ON par.Tip_parametru='GE' AND par.Parametru='REZSTOCBK' 
WHERE s.Tip_gestiune NOT IN ('F','T') AND s.Stoc>=0.001 AND AVNEFAC.TERMINAL='9096' 
GROUP BY s.Subunitate, s.Contract, s.Tip_gestiune, s.Cod_gestiune, s.Cod, s.Cod_intrare, s.Data 
ORDER BY s.Subunitate, s.Contract, s.Tip_gestiune, s.Cod_gestiune, s.Cod, s.Cod_intrare, s.Data

select * from avnefac 
where AVNEFAC.TERMINAL='7328'
select * from stocuri s