CREATE INDEX missing_index_13 ON [TET].[dbo].[istoricstocuri] ([Data_lunii]) INCLUDE ([Cod_gestiune], [Cod], [Data], [Cod_intrare], [Pret], [Stoc], [Cont], [Data_expirarii], [Furnizor], [Lot])			
CREATE INDEX missing_index_387 ON [TET].[dbo].[pozplin] ([Subunitate], [Numar])			
CREATE INDEX missing_index_338 ON [TET].[dbo].[stocuri] ([Cod], [Cod_intrare])			
CREATE INDEX missing_index_64 ON [TET].[dbo].[fisaMF] ([Subunitate], [Loc_de_munca]) INCLUDE ([Numar_de_inventar], [Data_lunii_operatiei], [Felul_operatiei])			
CREATE INDEX missing_index_259 ON [TET].[dbo].[terti] ([Subunitate], [Sold_ca_furnizor], [Tert])			
CREATE INDEX missing_index_364 ON [TESTOV].[dbo].[pozdoc] ([Subunitate], [Tip_miscare], [Data]) INCLUDE ([Tip], [Numar], [Cod], [Gestiune], [Cantitate], [Pret_valuta], [Pret_de_stoc], [Adaos], [Pret_vanzare], [Pret_cu_amanuntul], [TVA_deductibil], [Cota_TVA], [Utilizator], [Data_operarii], [Ora_operarii], [Cod_intrare], [Cont_de_stoc], [Cont_corespondent], [TVA_neexigibil], [Pret_amanunt_predator], [Numar_pozitie], [Loc_de_munca], [Comanda])			
CREATE INDEX missing_index_25 ON [TET].[dbo].[webConfigTipuri] ([procPopulare])			
CREATE INDEX missing_index_66 ON [TET].[dbo].[fisaMF] ([Subunitate], [Categoria], [Numar_de_inventar], [Data_lunii_operatiei], [Felul_operatiei], [Obiect_de_inventar]) INCLUDE ([Loc_de_munca], [Gestiune], [Comanda], [Valoare_de_inventar], [Valoare_amortizata], [Valoare_amortizata_cont_8045], [Valoare_amortizata_cont_6871], [Amortizare_lunara], [Amortizare_lunara_cont_8045], [Amortizare_lunara_cont_6871], [Durata], [Cont_mijloc_fix], [Numar_de_luni_pana_la_am_int])			
CREATE INDEX missing_index_175 ON [TESTOV].[dbo].[pozdoc] ([Subunitate], [Tip], [Gestiune_primitoare], [Data]) INCLUDE ([Cantitate], [Pret_de_stoc], [Pret_cu_amanuntul])			
CREATE INDEX missing_index_347 ON [TET].[dbo].[facturi] ([Subunitate], [Tip], [Tert], [Data])			
CREATE INDEX missing_index_389 ON [TET].[dbo].[pozplin] ([Subunitate], [Tert], [Data], [Plata_incasare])			
CREATE INDEX missing_index_370 ON [TESTOV].[dbo].[pozdoc] ([Subunitate], [Tip_miscare], [Data]) INCLUDE ([Tip], [Numar], [Cod], [Gestiune], [Cantitate], [Pret_valuta], [Pret_de_stoc], [Adaos], [Pret_vanzare], [Pret_cu_amanuntul], [TVA_deductibil], [Cota_TVA], [Utilizator], [Data_operarii], [Ora_operarii], [Cod_intrare], [Cont_de_stoc], [Cont_corespondent], [TVA_neexigibil], [Pret_amanunt_predator], [Locatie], [Data_expirarii], [Numar_pozitie], [Loc_de_munca], [Comanda], [Barcod], [Cont_intermediar], [Cont_venituri], [Discount], [Tert], [Factura], [Gestiune_primitoare], [Numar_DVI], [Stare], [Grupa], [Cont_factura], [Valuta], [Curs], [Data_facturii], [Data_scadentei], [Procent_vama], [Suprataxe_vama], [Accize_cumparare], [Accize_datorate], [Contract], [Jurnal])			
CREATE INDEX missing_index_372 ON [TET].[dbo].[pozplin] ([Data]) INCLUDE ([Subunitate], [Cont])			
CREATE INDEX missing_index_37 ON [TET].[dbo].[facturi] ([Subunitate], [Tip], [Tert])			
CREATE INDEX missing_index_177 ON [TESTOV].[dbo].[pozdoc] ([Subunitate], [Tip], [Data], [Gestiune_primitoare]) INCLUDE ([Cantitate], [Pret_de_stoc], [Pret_cu_amanuntul])			
CREATE INDEX missing_index_263 ON [TET].[dbo].[terti] ([Sold_ca_furnizor]) INCLUDE ([Subunitate], [Tert])			
CREATE INDEX missing_index_61 ON [TET].[dbo].[fisaMF] ([Numar_de_inventar], [Data_lunii_operatiei]) INCLUDE ([Loc_de_munca])			
CREATE INDEX missing_index_335 ON [TET].[dbo].[stocuri] ([Subunitate], [Cod])			
CREATE INDEX missing_index_377 ON [TET].[dbo].[pozncon] ([Data]) INCLUDE ([Subunitate], [Tip], [Numar])			
CREATE INDEX missing_index_53 ON [TET].[dbo].[stocuri] ([Subunitate], [Cod], [Cod_gestiune])			
CREATE INDEX missing_index_33 ON [msdb].[dbo].[backupset] ([media_set_id])			
CREATE INDEX missing_index_42 ON [TET].[dbo].[antetBonuri] ([Chitanta], [Data_bon]) INCLUDE ([Casa_de_marcat], [Numar_bon], [Vinzator], [Factura], [Data_facturii], [Tert], [Gestiune], [IdAntetBon])			
CREATE INDEX missing_index_392 ON [TET].[dbo].[stocuri] ([Subunitate], [Cod], [Stoc]) INCLUDE ([Tip_gestiune], [Cod_gestiune], [Data], [Cod_intrare], [Pret], [Cont], [Locatie])			
CREATE INDEX missing_index_383 ON [TET].[dbo].[CalStd] ([Luna]) INCLUDE ([LunaAlfa])			
CREATE INDEX missing_index_21 ON [TET].[dbo].[istoricstocuri] ([Data_lunii], [Tip_gestiune]) INCLUDE ([Subunitate], [Cod_gestiune], [Cod], [Cod_intrare], [idIntrareFirma])			
CREATE INDEX missing_index_374 ON [TET].[dbo].[balanta] ([Subunitate], [HostID], [Cont])			
CREATE INDEX missing_index_399 ON [TET].[dbo].[stocuri] ([Stoc]) INCLUDE ([Cod])			
CREATE INDEX missing_index_68 ON [TET].[dbo].[fisaMF] ([Data_lunii_operatiei], [Felul_operatiei]) INCLUDE ([Subunitate], [Numar_de_inventar], [Valoare_de_inventar], [Durata])			
CREATE INDEX missing_index_59 ON [TET].[dbo].[fisaMF] ([Numar_de_inventar], [Data_lunii_operatiei])			
CREATE INDEX missing_index_237 ON [TET].[dbo].[facturi] ([Subunitate], [Data_scadentei]) INCLUDE ([Tip], [Factura], [Tert], [Data], [Valoare], [TVA_11], [TVA_22], [Valuta], [Achitat], [Data_ultimei_achitari])			
CREATE INDEX missing_index_70 ON [TET].[dbo].[fisaMF] ([Felul_operatiei]) INCLUDE ([Subunitate], [Numar_de_inventar], [Data_lunii_operatiei], [Loc_de_munca], [Gestiune], [Comanda], [Valoare_de_inventar], [Valoare_amortizata], [Amortizare_lunara], [Durata], [Cont_mijloc_fix])			
CREATE INDEX missing_index_76 ON [TET].[dbo].[doc] ([Tip], [Data]) INCLUDE ([Cod_tert], [Factura], [Loc_munca])			
CREATE INDEX missing_index_79 ON [TET].[dbo].[pozplin] ([Plata_incasare]) INCLUDE ([Data], [Tert], [Factura], [Suma])			
