truncate table syssactiv
truncate table syssavx
truncate table syssc
truncate table syssca
truncate table sysscatop
truncate table sysscm
truncate table syssco
truncate table sysscoef
truncate table sysscoefm
truncate table sysscomenzi
truncate table sysscon
truncate table sysscor
truncate table syssdev
truncate table syssdevr
truncate table sysselem
truncate table sysselemactiv
truncate table sysselemtm
truncate table syssg
drop table yso.syssgr
truncate table syssgrmas
truncate table syssip
truncate table syssl
truncate table sysslsman
truncate table sysslsmat
truncate table syssm
truncate table syssmasini
truncate table syssmatrep
truncate table syssmm
truncate table syssn
truncate table syssopreper
truncate table syssp
truncate table sysspa
truncate table sysspcon
truncate table sysspd
truncate table sysspdev
truncate table sysspl
truncate table sysspn
truncate table sysspon
truncate table sysspozactiv
truncate table sysspp
truncate table sysspv
truncate table syssrealcom
truncate table syssret
truncate table syssrulsoldi
truncate table sysss
truncate table sysst
truncate table syssterm
truncate table sysstich
truncate table sysstipmas
truncate table syssWebConfigFiltre
truncate table syssWebConfigForm
truncate table syssWebConfigGrid
truncate table syssWebConfigMeniu
truncate table syssWebConfigTaburi
truncate table syssWebConfigTipuri