SELECT rtrim(max(con.valuta)) as C001,
 (select val_alfanumerica as nume from par where tip_parametru='GE' and parametru='NUME') as C002,
 max(terti.denumire) as C003,
 (select val_alfanumerica from par where tip_parametru = 'GE' and parametru = 'ORDREG') as C004,
 ltrim(max(con.contract)) as C005,
 max(terti.localitate) as C006,
 max(terti.judet) as C007,
 max(convert(char(12),con.data,104)) as C008,
 ltrim(rtrim(CASE max(pozcon.valuta) WHEN '' THEN '' ELSE convert(char(16),convert(money,MAX(CON.CURS))) END)) as C009,
 (select val_alfanumerica as cif from par where tip_parametru = 'GE' and parametru = 'CODFISC') as C010,
 max(terti.cont_in_banca) as C011,
 (select val_alfanumerica from par where tip_parametru='GE' and parametru = 'CONTBC') as C012,
 ltrim(max(con.contract)) as C013,
 max(terti.cod_fiscal) as C014,
 max(terti.banca) as C015,
 (select val_alfanumerica from par where tip_parametru='GE' and parametru = 'BANCA') as C016,
 max(terti.adresa) as C017,
 (select val_alfanumerica from par where tip_parametru='GE' and parametru = 'ADRESA') as C018,
 MAX(round(convert(decimal(17,5),pozcon.pret*pozCON.CURSvaluta),2)) as C019,
 max(nomencl.um) as C020,
 left(convert(char(16),convert(money,round(max(pozcon.Suma_TVA),2)),2),15) as C021,
 convert(char(15),convert(money,round(sum(sum(round(convert(decimal(17,5),pozcon.pret*(1-pozcon.Discount/100)*(1-pozcon.DiscDoi/100)*(1-pozcon.DiscTrei/100)*pozcon.CursValuta)*pozcon.cantitate,2 ))) over(partition by pozcon.contract),2)),1) as C022,
 convert(char(15),convert(money,round(sum(convert(decimal(17,5),pozcon.pret*(1-pozcon.Discount/100)*(1-pozcon.DiscDoi/100)*(1-pozcon.DiscTrei/100)*pozcon.CursValuta)*pozcon.cantitate),2)),1) as C023,
 convert(char(15),convert(money,round((select sum(p.pret*p.cantitate*(1-p.Discount/100)*(1-p.DiscDoi/100)*(1-p.DiscTrei/100)) from yso.pozconexp p where p.subunitate=max(pozcon.subunitate) and p.tip=max(pozcon.tip) and p.data=max(pozcon.data) and p.contract=max(pozcon.contract) and p.tert=max(pozcon.tert)),2)),1) as C024,
 left(convert(char(16),convert(money,round(max(pozcon.pret*(1-pozcon.Discount/100)),2)),2),15) as C025,
 left(convert(char(16),convert(money,round(max(pozcon.pret*(1-pozcon.Discount/100)*(1-pozcon.DiscDoi/100)),2)),2),15) as C026,
 left(convert(char(16),convert(money,round(max(convert(decimal(17,5),pozcon.pret)),2)),2),15) as C027,
 left(convert(char(16),convert(money,max(convert(decimal(17,5),pozcon.pret*(1-pozcon.Discount/100)*(1-pozcon.DiscDoi/100)*(1-pozcon.DiscTrei/100)))),2),16) as C028,
 left(convert(char(16),convert(money,round(max(pozcon.discount),2)),2),15) as C029,
 max(nomencl.denumire) as C030,
 (case when max(pozcon.tip)='FC' and exists (select codfurn from ppreturi where pozcon.cod=ppreturi.cod_resursa and max(pozcon.tert)=ppreturi.tert) then (select codfurn from ppreturi where pozcon.cod=ppreturi.cod_resursa and max(pozcon.tert)=ppreturi.tert) else pozcon.cod end) as C031,
 left(convert(char(16),convert(money,round(sum(pozcon.cantitate),2)),2),15) as C032,
 convert(char(15),convert(money,round(sum(sum(round(convert(decimal(17,5),pozcon.cantitate*pozcon.pret*(1-pozcon.Discount/100)*(1-pozcon.DiscDoi/100)*(1-pozcon.DiscTrei/100)*pozcon.CursValuta*(con.val_reziduala/100)*1.24),2 ))) over(partition by pozcon.contract),2)),1) as C033,
 convert(char(15),convert(money,round((select sum(round(convert(decimal(17,5),p.cantitate*p.pret*p.CursValuta*0.24),2 )) from yso.pozconexp p where p.subunitate= max(pozcon.subunitate) and p.tip= max(pozcon.tip) and p.contract= max(pozcon.contract) and p.data= max(pozcon.data) and p.tert=max(pozcon.tert)),2)),1) as C034,
 convert(char(15),convert(money,round(sum(sum(round(convert(decimal(17,5),pozcon.pret*(1-pozcon.Discount/100)*(1-pozcon.DiscDoi/100)*(1-pozcon.DiscTrei/100)*pozcon.CursValuta)*pozcon.cantitate*0.24,2 ))) over(partition by pozcon.contract),2)),1) as C035,
 convert(char(15),convert(money,round(sum(sum(round(convert(decimal(17,5),pozcon.pret*(1-pozcon.Discount/100)*(1-pozcon.DiscDoi/100)*(1-pozcon.DiscTrei/100)*pozcon.CursValuta)*pozcon.cantitate*1.24,2 ))) over(partition by pozcon.contract),2)),1) as C036,
 (select rtrim(Max(valoare)) from proprietati where TIP='UTILIZATOR' and cod_proprietate='EMAIL' and cod= max(pozcon.utilizator)) as C037,
 (select Max(Nume) from utilizatori where ID= max(pozcon.utilizator)) as C038,
'' as C039,
'' as C040,
'' as C041,
'' as C042,
'' as C043,
'' as C044,
'' as C045,
'' as C046,
'' as C047,
'' as C048,
'' as C049,
'' as C050,
'' as C051,
'' as C052,
'' as C053,
'' as C054,
'' as C055,
'' as C056,
'' as C057,
'' as C058,
'' as C059,
'' as C060,
'' as C061,
'' as C062,
'' as C063,
'' as C064,
'' as C065,
'' as C066,
'' as C067,
'' as C068,
'' as C069,
'' as C070,
'' as C071,
'' as C072,
'' as C073,
'' as C074,
'' as C075,
'' as C076,
'' as C077,
'' as C078,
'' as C079,
'' as C080,
'' as C081,
'' as C082,
'' as C083,
'' as C084,
'' as C085,
'' as C086,
'' as C087,
'' as C088,
'' as C089,
'' as C090,
'' as C091,
'' as C092,
'' as C093,
'' as C094,
'' as C095,
'' as C096,
'' as C097,
'' as C098,
'' as C099,
'' AS C100 FROM avnefac JOIN con ON avnefac.subunitate=con.subunitate and avnefac.tip=con.tip and avnefac.contractul=con.contract and avnefac.cod_tert=con.tert and avnefac.data=con.data JOIN yso.pozconexp pozcon ON pozcon.subunitate=con.subunitate and pozcon.tip=con.tip and pozcon.contract=con.contract and pozcon.data=con.data and pozcon.tert=con.tert LEFT JOIN terti ON terti.subunitate=con.subunitate and terti.tert=con.tert LEFT JOIN nomencl ON nomencl.cod=pozcon.cod and nomencl.cod=pozcon.cod WHERE pozcon.Listare='' AND AVNEFAC.TERMINAL='1032' 
GROUP BY avnefac.tip, avnefac.numar, avnefac.data, pozcon.cod,con.loc_de_munca, POZCON.TERT, TERTI.TERT, pozCON.CONTRACT