
 alter  table misMF disable trigger misMFsterg 
 alter  table elemente disable trigger elemsterg 
 alter  table tipmasini disable trigger tipmassterg 
 alter  table elemtipm disable trigger elemtmsterg 
 alter  table utilizatori disable trigger wTrigRia 
 alter  table facturi disable trigger yso_tr_validFacturi 
 alter  table facturi disable trigger tr_validFacturi 
 alter  table coefmasini disable trigger coefmsterg 
 alter  table pozplin disable trigger plinfac 
 alter  table pozplin disable trigger plininc 
 alter  table pozplin disable trigger plinTinc 
 alter  table pozplin disable trigger plinTxinc 
 alter  table pozplin disable trigger plinefect 
 alter  table pozplin disable trigger plindec 
 alter  table pozplin disable trigger plinantet 
 alter  table pozplin disable trigger pozplinsterg 
 alter  table incfact disable trigger incplin 
 alter  table bp disable trigger yso_bpsterg 
 alter  table terti disable trigger tertisterg 
 alter  table infoPers disable trigger tr_validInfopers 
 alter  table conturi disable trigger tr_validConturi 
 alter  table conturi disable trigger conturisterg 
 alter  table nomencl disable trigger nomenclsterg 
 alter  table nomencl disable trigger yso_insnomencl 
 alter  table doc disable trigger yso_docsterg 
 alter  table con disable trigger DelExtcon 
 alter  table con disable trigger consterg 
 alter  table benret disable trigger tr_validBenret 
 alter  table DVI disable trigger DVIfac 
 alter  table tipret disable trigger tr_validTipret 
 alter  table pozdoc disable trigger yso_tr_ValidPozdoc 
 alter  table pozdoc disable trigger tr_ValidPozdoc 
 alter  table pozdoc disable trigger pozdocsterg 
 alter  table pozdoc disable trigger doccontr 
 alter  table pozdoc disable trigger docantet 
 alter  table pozdoc disable trigger docdec 
 alter  table pozdoc disable trigger docfac 
 alter  table pozdoc disable trigger docfacav 
 alter  table pozdoc disable trigger realizpozprod 
 alter  table pozdoc disable trigger docMfix 
 alter  table pozdoc disable trigger docstoc 
 alter  table pozdoc disable trigger docXstoc 
 alter  table pozdoc disable trigger docFinc 
 alter  table pozdoc disable trigger docFxinc 
 alter  table pozdoc disable trigger docMinc 
 alter  table pozdoc disable trigger docNinc 
 alter  table pozdoc disable trigger docdefinitiv 
 alter  table pozdoc disable trigger doclunastc 
 alter  table pozdoc disable trigger docAinc 
 alter  table pozdoc disable trigger docAxinc 
 alter  table pozdoc disable trigger docBinc 
 alter  table pozdoc disable trigger docBxinc 
 alter  table pozdoc disable trigger docDinc 
 alter  table pozdoc disable trigger docDxinc 
 alter  table pozdoc disable trigger docRinc 
 alter  table pozdoc disable trigger docTinc 
 alter  table pozdoc disable trigger docTxinc 
 alter  table pozdoc disable trigger docTxyinc 
 alter  table pozdoc disable trigger docXinc 
 alter  table pozdoc disable trigger docXyinc 
 alter  table pozdoc disable trigger docXzinc 
 alter  table resal disable trigger resalsterg 
 alter  table resal disable trigger tr_ValidResal 
 alter  table resal disable trigger resalLmExp 
 alter  table resal disable trigger resallunai 
 alter  table lansman disable trigger lansmansterg 
 alter  table pozadoc disable trigger adocinc 
 alter  table pozadoc disable trigger adocXinc 
 alter  table pozadoc disable trigger adocXyinc 
 alter  table pozadoc disable trigger adocfacst 
 alter  table pozadoc disable trigger pozadocsterg 
 alter  table pozadoc disable trigger adocfacdr 
 alter  table pozadoc disable trigger adocantet 
 alter  table pozadoc disable trigger tr_ValidPozadoc 
 alter  table pontaj disable trigger pontajLmExp 
 alter  table pontaj disable trigger pontajlunai 
 alter  table pontaj disable trigger tr_ValidPontaj 
 alter  table pontaj disable trigger pontajsterg 
 alter  table lm disable trigger lmsterg 
 alter  table lansmat disable trigger lansmatsterg 
 alter  table Infopontaj disable trigger infopontajLmExp 
 alter  table Infopontaj disable trigger infopontajlunai 
 alter  table gestiuni disable trigger gestiunisterg 
 alter  table avexcep disable trigger avexceplunai 
 alter  table avexcep disable trigger avexcepsterg 
 alter  table avexcep disable trigger tr_ValidAvexcep 
 alter  table conmed disable trigger conmedsterg 
 alter  table conmed disable trigger conmedLmExp 
 alter  table conmed disable trigger conmedlunai 
 alter  table conmed disable trigger tr_ValidConmed 
 alter  table comenzi disable trigger delcompozprod 
 alter  table comenzi disable trigger comenzisterg 
 alter  table ConcOdih disable trigger concodihsterg 
 alter  table ConcOdih disable trigger tr_ValidConcodih 
 alter  table ConcOdih disable trigger concodihLmExp 
 alter  table ConcOdih disable trigger concodihlunai 
 alter  table corectii disable trigger corectiiLmExp 
 alter  table corectii disable trigger corectiilunai 
 alter  table corectii disable trigger tr_ValidCorectii 
 alter  table corectii disable trigger corectiisterg 
 alter  table personal disable trigger tr_validPersonal 
 alter  table personal disable trigger personalsterg 
 alter  table indicatori disable trigger tr_modifind 
 alter  table functii disable trigger tr_validFunctii 
 alter  table grupe disable trigger yso_grupesterg 
 alter  table persintr disable trigger tr_ValidPersintr 
 alter  table persintr disable trigger persintrlunai 
 alter  table Extinfop disable trigger tr_ValidExtinfop 
 alter  table tichete disable trigger tr_ValidTichete 
 alter  table tichete disable trigger ticheteLmExp 
 alter  table tichete disable trigger tichetelunai 
 alter  table tichete disable trigger tichetesterg 
 alter  table activitati disable trigger activsterg 
 alter  table pozactivitati disable trigger pozactivsterg 
 alter  table elemactivitati disable trigger elemactivsterg 
 alter  table tehn disable trigger yso_instehncomenzi 
 alter  table tehnpoz disable trigger yso_instehnpozcom 
 alter  table MFix disable trigger MFixsterg 
 alter  table infoconmed disable trigger infoconmedlunai 
 alter  table infoconmed disable trigger tr_ValidInfoconmed 
 alter  table conalte disable trigger conaltelunai 
 alter  table conalte disable trigger conaltesterg 
 alter  table conalte disable trigger tr_ValidConalte 
 alter  table preturi disable trigger preturisterg 
 alter  table realcom disable trigger tr_validRealcom 
 alter  table realcom disable trigger realcominch 
 alter  table realcom disable trigger realcomsterg 
 alter  table SalariiZilieri disable trigger SalariiZilierilunai 
 alter  table Termene disable trigger termsterg 
 alter  table pozcon disable trigger yso_ins_pozcon 
 alter  table pozcon disable trigger yso_delpozconexp 
 alter  table pozcon disable trigger yso_tr_validPozcon 
 alter  table pozcon disable trigger livrpozprod 
 alter  table pozcon disable trigger delpozprod 
 alter  table pozcon disable trigger cantcon 
 alter  table pozcon disable trigger pozconsterg 
 alter  table pozcon disable trigger cantpozaprov 
 alter  table pozcon disable trigger delpozaprov 
 alter  table catop disable trigger catopsterg 
 alter  table pozncon disable trigger nconant 
 alter  table pozncon disable trigger nconinc 
 alter  table pozncon disable trigger poznconsterg 
 alter  table extpozplin disable trigger extplinef 
 alter  table extpozplin disable trigger extplindec 
 alter  table penalizarifact disable trigger penalizarifact_modific 
 alter  table incrate disable trigger RATEPLIN 
 alter  table rulaje disable trigger rulajeinisterg 
 alter  table pozincon disable trigger inconant 
 alter  table pozincon disable trigger IncRul 
 alter  table pozincon disable trigger inconLmExp 
 alter  table pozincon disable trigger inconlunai 
 alter  table pozincon disable trigger tr_ValidPozincon 
 alter  table par disable trigger paramsterg 
