set transaction isolation level read uncommitted 
select rtrim((select val_alfanumerica as nume from par where tip_parametru='GE' and parametru='NUME')) as [UNITATE], rtrim(max(convert(char(12),pozdoc.data,104))) as [DATA], rtrim(rtrim(max(pozdoc.numar))) as [DOC], rtrim(max(gestiuni.denumire_gestiune)) as [GEST], rtrim(MAX(GESTIUNI.COD_GESTIUNE)) as [CODG], rtrim(max(terti.denumire)) as [FURN], rtrim(MAX(POZDOC.TERT)) as [CODF], rtrim(max(terti.adresa)) as [ADRESAF], rtrim(max(pozdoc.factura)) as [FACT], rtrim(MAX(POZDOC.DATA_FACTURII)) as [DATAF], rtrim(row_number() OVER(ORDER BY pozdoc.cod)) as [NR], rtrim(rtrim(pozdoc.cod)) as [COD], rtrim(max(nomencl.denumire)) as [DENUMIRE], rtrim(nomencl.um) as [UM], rtrim(left(convert(char(18),convert(money,pozdoc.pret_de_stoc),2),17)) as [PRET], rtrim(substring(convert(char(18),convert(money,round(pozdoc.cantitate,2)),2),6,11)) as [CANT], rtrim(substring(convert(char(17),convert(money,round(pozdoc.pret_de_stoc*pozdoc.cantitate,2)),1),4,14)) as [VALRON], rtrim(convert(char(17),convert(money,round(pozdoc.TVA_deductibil,2)),1)) as [TVA], rtrim(MAX(POZDOC.LOCATIE)) as [LOCATOR], rtrim(CASE RTRIM(max(pozdoc.valuta)) WHEN '' THEN '0' ELSE MAX(convert(char(18),convert(money,pozdoc.pret_valuta,2),17)) END) as [PRETVALUTA], rtrim(CASE RTRIM(max(pozdoc.valuta)) WHEN '' THEN '0' ELSE substring(convert(char(17),convert(money,round(pozdoc.pret_VALUTA*pozdoc.cantitate,2)),1),4,14) END) as [VALVALUTA], rtrim(convert(char(17),convert(money,round((select sum(p.pret_de_stoc*p.cantitate) from pozdoc p where p.subunitate=max(pozdoc.subunitate) and p.tip=max(pozdoc.tip) and p.data=max(pozdoc.data) and p.numar=max(pozdoc.numar)),2)),1)) as [TVAL], rtrim(convert(char(17),convert(money,round((select sum(p.TVA_deductibil) from pozdoc p where p.subunitate=max(pozdoc.subunitate) and p.numar=max(pozdoc.numar) and p.data=max(pozdoc.data) and p.tip=max(pozdoc.tip)),2)),1)) as [TTVA], rtrim(CASE RTRIM(max(pozdoc.valuta)) WHEN '' THEN '0' ELSE convert(char(17),convert(money,round((select sum(p.pret_valuta*p.cantitate) from pozdoc p where p.subunitate=max(pozdoc.subunitate) and p.tip=max(pozdoc.tip) and p.data=max(pozdoc.data) and p.numar=max(pozdoc.numar)),2)),1) end) as [TVALEUR], rtrim(convert(char(17),convert(money,round((select (sum(p.pret_de_stoc*p.cantitate)+sum(p.TVA_deductibil)) from pozdoc p where p.subunitate=max(pozdoc.subunitate) and p.tip=max(pozdoc.tip) and p.numar=max(pozdoc.numar) and p.data=max(pozdoc.data)),2)),1)) as [TOTAL], rtrim(max(anexadoc.numele_delegatului)) as [MEMBR1], rtrim(max(anexadoc.eliberat)) as [MEMBR2], rtrim(max(anexadoc.mijloc_de_transport)) as [MEMBR3], rtrim(max(anexadoc.observatii)) as [MEMBR4]
 --into ##raspASIS 
FROM avnefac,pozdoc,nomencl,terti,gestiuni,anexadoc
WHERE avnefac.subunitate=pozdoc.subunitate and avnefac.tip=pozdoc.tip and avnefac.numar=pozdoc.numar and avnefac.data=pozdoc.data and avnefac.cod_gestiune=pozdoc.gestiune and pozdoc.cod=nomencl.cod and terti.subunitate=avnefac.subunitate and terti.tert=pozdoc.tert and anexadoc.subunitate=pozdoc.subunitate and anexadoc.tip='RD' and anexadoc.numar=pozdoc.numar and anexadoc.data=pozdoc.data and gestiuni.subunitate=avnefac.subunitate and gestiuni.cod_gestiune=pozdoc.gestiune
and avnefac.terminal='ASIS' 
GROUP BY pozdoc.cod, pozdoc.pret_vanzare, pozdoc.factura, nomencl.um, pozdoc.cantitate, pozdoc.pret_de_stoc,POZDOC.PRET_VALUTA, pozdoc.tva_deductibil, pozdoc.numar_pozitie ORDER BY pozdoc.numar_pozitie 
--set @maxrand = isnull((select count(*) from ##raspASIS),0)

select * from avnefac a where a.Terminal='asis'