-- mai intai cele care expira dar nu sunt inca expirate in perioada anterioara datei expirarii comenzii de livrare din gest sursa, fara contract
exec sp_executesql N'SELECT Subunitate,Tip_gestiune,Cod_gestiune,Locatie,Contract,Lot,Data_expirarii,Cod,Data,Stoc,Cod_intrare,Pret,Cont,TVA_neexigibil,Pret_cu_amanuntul FROM TET..stocuri WHERE Subunitate = @P1 AND Tip_gestiune = @P2 AND Cod_gestiune = @P3 AND (Data_expirarii >= @P4 AND Data_expirarii < DATEADD (day, 1, @P5)) AND Cod = @P6 AND Data < DATEADD (day, 1, @P7) AND Stoc >= @P8    AND (Tip_gestiune not in (''F'', ''T'')) ORDER BY Subunitate ASC ,Tip_gestiune ASC ,Cod_gestiune ASC ,Cod ASC ,Data ASC ,Cod_intrare ASC ',N'@P1 char(9),@P2 char(1),@P3 char(20),@P4 datetime,@P5 datetime,@P6 char(20),@P7 datetime,@P8 float','1        ','C','101                 ','2012-01-12 00:00:00','2012-01-12 00:00:00','0003006A            ','2012-02-29 00:00:00',0.001

-- apoi cele din gestiunea intai de rezervari cu contr completat=com livr
exec sp_executesql N'SELECT Subunitate,Tip_gestiune,Cod_gestiune,Locatie,Contract,Lot,Data_expirarii,Cod,Data,Stoc,Cod_intrare,Pret,Cont,TVA_neexigibil,Pret_cu_amanuntul FROM TET..stocuri WHERE Subunitate = @P1 AND Tip_gestiune = @P2 AND Cod_gestiune = @P3 AND Contract = @P4 AND Cod = @P5 AND Data < DATEADD (day, 1, @P6) AND Stoc >= @P7    AND (Tip_gestiune not in (''F'', ''T'')) ORDER BY Subunitate ASC ,Tip_gestiune ASC ,Cod_gestiune ASC ,Cod ASC ,Data ASC ,Cod_intrare ASC ',N'@P1 char(9),@P2 char(1),@P3 char(20),@P4 char(20),@P5 char(20),@P6 datetime,@P7 float','1        ','C','300                 ','TEST                ','0003006A            ','2012-02-29 00:00:00',0.001

--apoi cele din gest a 2 a de rezervari cu contr completat=com livr
exec sp_executesql N'SELECT Subunitate,Tip_gestiune,Cod_gestiune,Locatie,Contract,Lot,Data_expirarii,Cod,Data,Stoc,Cod_intrare,Pret,Cont,TVA_neexigibil,Pret_cu_amanuntul FROM TET..stocuri WHERE Subunitate = @P1 AND Tip_gestiune = @P2 AND Cod_gestiune = @P3 AND Contract = @P4 AND Cod = @P5 AND Data < DATEADD (day, 1, @P6) AND Stoc >= @P7    AND (Tip_gestiune not in (''F'', ''T'')) ORDER BY Subunitate ASC ,Tip_gestiune ASC ,Cod_gestiune ASC ,Cod ASC ,Data ASC ,Cod_intrare ASC ',N'@P1 char(9),@P2 char(1),@P3 char(20),@P4 char(20),@P5 char(20),@P6 datetime,@P7 float','1        ','M','900                 ','TEST                ','0003006A            ','2012-02-29 00:00:00',0.001

--apoi cele din gest sursa a comenzii si contractul=com livr
exec sp_executesql N'SELECT Subunitate,Tip_gestiune,Cod_gestiune,Locatie,Contract,Lot,Data_expirarii,Cod,Data,Stoc,Cod_intrare,Pret,Cont,TVA_neexigibil,Pret_cu_amanuntul FROM TET..stocuri WHERE Subunitate = @P1 AND Tip_gestiune = @P2 AND Cod_gestiune = @P3 AND Contract = @P4 AND Cod = @P5 AND Data < DATEADD (day, 1, @P6) AND Stoc >= @P7    AND (Tip_gestiune not in (''F'', ''T'')) ORDER BY Subunitate ASC ,Tip_gestiune ASC ,Cod_gestiune ASC ,Cod ASC ,Data ASC ,Cod_intrare ASC ',N'@P1 char(9),@P2 char(1),@P3 char(20),@P4 char(20),@P5 char(20),@P6 datetime,@P7 float','1        ','C','101                 ','TEST                ','0003006A            ','2012-02-29 00:00:00',0.001

--apoi cele din gest sursa a comenzii si fara contract 
exec sp_executesql N'SELECT Subunitate,Tip_gestiune,Cod_gestiune,Locatie,Contract,Lot,Data_expirarii,Cod,Data,Stoc,Cod_intrare,Pret,Cont,TVA_neexigibil,Pret_cu_amanuntul FROM TET..stocuri WHERE Subunitate = @P1 AND Tip_gestiune = @P2 AND Cod_gestiune = @P3 AND Contract = @P4 AND Cod = @P5 AND Data < DATEADD (day, 1, @P6) AND Stoc >= @P7    AND (Tip_gestiune not in (''F'', ''T'')) ORDER BY Subunitate ASC ,Tip_gestiune ASC ,Cod_gestiune ASC ,Cod ASC ,Data ASC ,Cod_intrare ASC ',N'@P1 char(9),@P2 char(1),@P3 char(20),@P4 char(20),@P5 char(20),@P6 datetime,@P7 float','1        ','C','101                 ','                    ','0003006A            ','2012-02-29 00:00:00',0.001

--apoi cele din orice gest dar cu contract=com livr
exec sp_executesql N'SELECT Subunitate,Tip_gestiune,Cod_gestiune,Locatie,Contract,Lot,Data_expirarii,Cod,Data,Stoc,Cod_intrare,Pret,Cont,TVA_neexigibil,Pret_cu_amanuntul FROM TET..stocuri WHERE Subunitate = @P1 AND Contract = @P2 AND Cod = @P3 AND Data < DATEADD (day, 1, @P4) AND Stoc >= @P5    AND (Tip_gestiune not in (''F'', ''T'')) ORDER BY Subunitate ASC ,Tip_gestiune ASC ,Cod_gestiune ASC ,Cod ASC ,Data ASC ,Cod_intrare ASC ',N'@P1 char(9),@P2 char(20),@P3 char(20),@P4 datetime,@P5 float','1        ','TEST                ','0003006A            ','2012-02-29 00:00:00',0.001