
if exists (select 1 from webconfigmeniu where meniu='KO') begin raiserror('Acest meniu este configurat deja! Daca doriti, stergeti manual linia din webConfigMeniu',11,1) return end
--delete from webconfigmeniu where tipMacheta='D' and meniu='KO'
delete from webconfigfiltre where meniu='KO' and (''='' or isnull(tip,'')='')
delete from webconfiggrid where meniu='KO' and (''='' or isnull(tip,'')='') and (''='' or isnull(subtip,'')='')
delete from webconfigtipuri where meniu='KO' and (''='' or isnull(tip,'')='') and (''='' or isnull(subtip,'')='')
delete from webconfigform where meniu='KO' and (''='' or isnull(tip,'')='') and (''='' or isnull(subtip,'')='')
delete from webConfigTaburi where MeniuSursa='KO' and (''='' or isnull(TipSursa,'')='')

insert into webconfigmeniu --(id,Nume,idParinte,Icoana,TipMacheta,Meniu,Modul)
				(Meniu, Nume, MeniuParinte, Icoana, TipMacheta, NrOrdine, Componenta, Semnatura, Detalii, vizibil)
select top 0 null,null,null,null,null,null,null,null,null,null
union all select 'KO','Comenzi terti','URMARIRE CONTRACTE','Comenzi','D',42.00,'','','<row><vechi><row id="42" nume="Comenzi terti" idparinte="7" icoana="Comenzi" tipmacheta="D" meniu="KO" modul="UC"/></vechi></row>',1

insert into webconfiggrid (Meniu, Tip, Subtip, InPozitii, NumeCol, DataField, TipObiect, Latime, Ordine, Vizibil, Modificabil, Formula) 
select top 0 null,null,null,null,null,null,null,null,null,null,null,null
union all select 'KO','BK','','1','Cant. aprobata','@cant_aprobata','N','150','30','1','0',''
union all select 'KO','BK','','1','Cant. realizata','@cant_realizata','N','150','31','1','0',''
union all select 'KO','BK','','1','Cantit. transferata','@cant_transferata','N','150','23','0','0',''
union all select 'KO','BK','','1','Cantitate','@cantitate','N','150','7','1','0',''
union all select 'KO','BK','','1','Cantitate','@cantitateum1','N','150','15','0','0',''
union all select 'KO','BK','','1','Cantitate um2','@cantitateum2','N','150','18','0','0',''
union all select 'KO','BK','','1','Cantitate UM3','@cantitateum3','N','150','21','0','0',''
union all select 'KO','BK','','1','Cod','@cod','C','150','4','1','0',''
union all select 'KO','BK','','1','Coef. conv. UM2','@coefconvum2','N','100','17','0','0',''
union all select 'KO','BK','','1','Coef. conv. UM3','@coefconvum3','N','100','20','0','0',''
union all select 'KO','BK','','0','Contr. cor.','@contractcor','C','100','19','0','0',''
union all select 'KO','BK','','1','Cota tva','@cotatva','N','100','25','1','0',''
union all select 'KO','BK','','0','Curs','@curs','N','80','17','0','0',''
union all select 'KO','BK','','0','Data','@data','D','100','3','1','0',''
union all select 'KO','BK','','1','Data','@data','D','100','3','0','0',''
union all select 'KO','BK','','1','Termen3','@data1','C','100','11','0','0',''
union all select 'KO','BK','','1','Data exp.','@dataexpirarii','D','100','36','0','0',''
union all select 'KO','BK','','0','Gestiune','@dengestiune','C','150','6','1','0',''
union all select 'KO','BK','','0','Den. gestiune','@dengestiune','C','250','7','0','0',''
union all select 'KO','BK','','1','Den. gestiune','@dengestiune','C','250','27','0','0',''
union all select 'KO','BK','','0','Den. gest. primitoare','@dengestprim','C','250','15','0','0',''
union all select 'KO','BK','','0','Den. loc munca','@denlm','C','250','13','0','0',''
union all select 'KO','BK','','1','Den. obiect','@denobiect','C','250','38','0','0',''
union all select 'KO','BK','','1','Cod specif.','@denspecif','C','250','3','0','0',''
union all select 'KO','BK','','0','Den. stare','@denstare','C','100','22','1','0',''
union all select 'KO','BK','','0','Beneficiar','@dentert','C','200','8','1','0',''
union all select 'KO','BK','','0','Den. tert','@dentert','C','150','9','0','0',''
union all select 'KO','BK','','1','Den. tert','@dentert','C','250','29','0','0',''
union all select 'KO','BK','','1','Denumire','@denumire','C','250','4','1','0',''
union all select 'KO','BK','','0','Discount','@discount','N','80','20','0','0',''
union all select 'KO','BK','','1','Discount','@discount','N','150','24','0','0',''
union all select 'KO','BK','','0','Explicatii','@explicatii','C','250','4','0','0',''
union all select 'KO','BK','','1','Explicatii','@explicatii','N','250','33','0','0',''
union all select 'KO','BK','','0','Factura','@factura','C','150','10','0','0',''
union all select 'KO','BK','','1','Gestiune','@gestiune','C','150','5','0','0',''
union all select 'KO','BK','','0','Gest. primitoare','@gestprim','C','150','14','0','0',''
union all select 'KO','BK','','0','Info1','@info1','C','100','23','0','0',''
union all select 'KO','BK','','1','Info1','@info1','N','150','39','0','0',''
union all select 'KO','BK','','1','Info10','@info10','N','150','48','0','0',''
union all select 'KO','BK','','1','Info11','@info11','N','150','49','0','0',''
union all select 'KO','BK','','1','Info12','@info12','C','200','50','0','0',''
union all select 'KO','BK','','1','Info13','@info13','C','200','51','0','0',''
union all select 'KO','BK','','1','Info14','@info14','C','200','52','0','0',''
union all select 'KO','BK','','1','Info15','@info15','C','200','53','0','0',''
union all select 'KO','BK','','1','Info16','@info16','C','200','54','0','0',''
union all select 'KO','BK','','1','Info17','@info17','C','200','55','0','0',''
union all select 'KO','BK','','0','Info2','@info2','N','100','24','0','0',''
union all select 'KO','BK','','1','Info2','@info2','C','250','40','0','0',''
union all select 'KO','BK','','0','Info3','@info3','N','100','25','0','0',''
union all select 'KO','BK','','1','Info3','@info3','N','150','41','0','0',''
union all select 'KO','BK','','0','Info4','@info4','N','100','25','0','0',''
union all select 'KO','BK','','1','Info4','@info4','C','250','42','0','0',''
union all select 'KO','BK','','0','Info5','@info5','N','100','26','0','0',''
union all select 'KO','BK','','1','Info5','@info5','C','250','43','0','0',''
union all select 'KO','BK','','0','Info6','@info6','C','150','27','0','0',''
union all select 'KO','BK','','1','Info6','@info6','C','100','44','0','0',''
union all select 'KO','BK','','1','Info7','@info7','C','100','45','0','0',''
union all select 'KO','BK','','1','Info8','@info8','N','150','46','0','0',''
union all select 'KO','BK','','1','Info9','@info9','N','150','47','0','0',''
union all select 'KO','BK','','0','Loc munca','@lm','C','150','12','0','0',''
union all select 'KO','BK','','1','Lot','@lot','C','150','35','0','0',''
union all select 'KO','BK','','1','Mod plata','@modplata','C','100','3','0','0',''
union all select 'KO','BK','','0','Numar','@numar','C','100','2','1','0',''
union all select 'KO','BK','','1','Numar','@numar','C','150','2','0','0',''
union all select 'KO','BK','','1','Nr. pozitie','@numarpozitite','N','100','34','0','0',''
union all select 'KO','BK','','1','Obiect','@obiect','C','150','37','0','0',''
union all select 'KO','BK','','0','Pozitii','@pozitii','N','50','30','1','0',''
union all select 'KO','BK','','1','Pret','@pret','N','150','22','1','0',''
union all select 'KO','BK','','0','Punct livrare','@punctlivrare','C','150','11','0','0',''
union all select 'KO','BK','','1','Punct livrare','@punctlivrare','C','150','26','0','0',''
union all select 'KO','BK','','0','Stare','@stare','C','50','21','0','0',''
union all select 'KO','BK','','1','Termen5','@Tcant_realizata','N','100','13','0','0',''
union all select 'KO','BK','','1','Termen1','@Tcantitate','N','150','9','0','0',''
union all select 'KO','BK','','0','Termen','@termen','D','100','5','0','0',''
union all select 'KO','BK','','1','Termen poz.','@termen_poz','C','150','32','0','0',''
union all select 'KO','BK','','1','Termen2','@termene','C','100','10','0','0',''
union all select 'KO','BK','','1','Tert','@tert','C','150','6','0','0',''
union all select 'KO','BK','','0','Tip','@tip','C','50','1','0','0',''
union all select 'KO','BK','','1','Tip','@tip','C','50','1','0','0',''
union all select 'KO','BK','','1','Tip gestiune','@tipgestiune','C','50','28','0','0',''
union all select 'KO','BK','','1','Termen4','@Tpret','N','100','12','0','0',''
union all select 'KO','BK','','1','UM secundara','@um1','C','50','14','1','0',''
union all select 'KO','BK','','1','UM2','@um2','C','50','16','0','0',''
union all select 'KO','BK','','1','UM3','@um3','C','50','19','0','0',''
union all select 'KO','BK','','0','Valoare','@valoare','N','100','18','1','0',''
union all select 'KO','BK','','0','Valuta','@valuta','C','80','16','0','0',''
union all select 'KO','BK','','1','Valuta','@valuta','C','100','8','0','0',''
union all select 'KO','BK','GF','1','Cant.aprobata','@cant_aprobata','N','150','3','1','0',''
union all select 'KO','BK','GF','1','Cant.realizata','@cant_realizata','N','150','4','1','0',''
union all select 'KO','BK','GF','1','Cant.disponibila','@cantitate_disponibila','N','150','5','1','0',''
union all select 'KO','BK','GF','1','Cant.de facturat','@cantitate_factura','N','150','6','1','1',''
union all select 'KO','BK','GF','1','Cod','@cod','C','100','1','1','0',''
union all select 'KO','BK','GF','1','Denumire','@denumire','C','300','2','1','0',''
union all select 'KO','BK','GT','1','Cant. aprobata','@cant_aprobata','N','100','3','0','0',''
union all select 'KO','BK','GT','1','Cant. transferata','@cant_transferata','N','100','4','0','0',''
union all select 'KO','BK','GT','1','Cant. disponibila','@cantitate_disponibila','N','100','5','0','0',''
union all select 'KO','BK','GT','1','Cant. de transferat','@cantitate_transfer','N','100','6','0','0',''
union all select 'KO','BK','GT','1','Cod','@cod','C','70','1','0','0',''
union all select 'KO','BK','GT','1','Denumire','@denumire','C','300','2','0','0',''
union all select 'KO','FC','','1','Cant. aprobata','@cant_aprobata','N','150','31','0','0',''
union all select 'KO','FC','','1','Cant. realizata','@cant_realizata','N','150','30','1','0',''
union all select 'KO','FC','','1','Cantit. transferata','@cant_transferata','N','150','23','0','0',''
union all select 'KO','FC','','1','Cantitate','@cantitate','N','150','7','0','0',''
union all select 'KO','FC','','1','Cantitate','@cantitateum1','N','150','15','1','0',''
union all select 'KO','FC','','1','Cantitate um2','@cantitateum2','N','150','18','0','0',''
union all select 'KO','FC','','1','Cantitate UM3','@cantitateum3','N','150','21','0','0',''
union all select 'KO','FC','','1','Cod','@cod','C','150','4','1','0',''
union all select 'KO','FC','','1','Coef. conv. UM2','@coefconvum2','N','100','17','0','0',''
union all select 'KO','FC','','1','Coef. conv. UM3','@coefconvum3','N','100','20','0','0',''
union all select 'KO','FC','','0','Contr. cor.','@contractcor','C','100','19','1','0',''
union all select 'KO','FC','','1','Cota tva','@cotatva','N','100','25','0','0',''
union all select 'KO','FC','','0','Curs','@curs','N','80','17','0','0',''
union all select 'KO','FC','','0','Data','@data','D','100','3','1','0',''
union all select 'KO','FC','','1','Data','@data','D','100','3','0','0',''
union all select 'KO','FC','','1','Termen3','@data1','C','100','11','0','0',''
union all select 'KO','FC','','1','Data exp.','@dataexpirarii','D','100','36','0','0',''
union all select 'KO','FC','','0','Den. gestiune','@dengestiune','C','250','7','0','0',''
union all select 'KO','FC','','1','Den. gestiune','@dengestiune','C','250','27','0','0',''
union all select 'KO','FC','','0','Den. gest. primitoare','@dengestprim','C','250','15','0','0',''
union all select 'KO','FC','','0','Den. loc munca','@denlm','C','250','13','0','0',''
union all select 'KO','FC','','1','Den. obiect','@denobiect','C','250','38','0','0',''
union all select 'KO','FC','','0','Den. stare','@denstare','C','100','22','1','0',''
union all select 'KO','FC','','0','Furnizor','@dentert','C','150','8','1','0',''
union all select 'KO','FC','','0','Den. tert','@dentert','C','150','9','0','0',''
union all select 'KO','FC','','1','Den. tert','@dentert','C','250','29','0','0',''
union all select 'KO','FC','','1','Denumire','@denumire','C','250','4','1','0',''
union all select 'KO','FC','','0','Discount','@discount','N','80','20','0','0',''
union all select 'KO','FC','','1','Discount','@discount','N','150','24','0','0',''
union all select 'KO','FC','','0','Explicatii','@explicatii','C','250','4','0','0',''
union all select 'KO','FC','','1','Explicatii','@explicatii','N','250','33','0','0',''
union all select 'KO','FC','','0','Factura','@factura','C','150','10','0','0',''
union all select 'KO','FC','','0','Gestiune','@gestiune','C','150','6','0','0',''
union all select 'KO','FC','','1','Gestiune','@gestiune','C','150','5','0','0',''
union all select 'KO','FC','','0','Gest. primitoare','@gestprim','C','150','14','0','0',''
union all select 'KO','FC','','0','Info1','@info1','C','100','23','0','0',''
union all select 'KO','FC','','1','Info1','@info1','N','150','39','0','0',''
union all select 'KO','FC','','1','Info10','@info10','N','150','48','0','0',''
union all select 'KO','FC','','1','Info11','@info11','N','150','49','0','0',''
union all select 'KO','FC','','1','Info12','@info12','C','200','50','0','0',''
union all select 'KO','FC','','1','Info13','@info13','C','200','51','0','0',''
union all select 'KO','FC','','1','Info14','@info14','C','200','52','0','0',''
union all select 'KO','FC','','1','Info15','@info15','C','200','53','0','0',''
union all select 'KO','FC','','1','Info16','@info16','C','200','54','0','0',''
union all select 'KO','FC','','1','Info17','@info17','C','200','55','0','0',''
union all select 'KO','FC','','0','Info2','@info2','N','100','24','0','0',''
union all select 'KO','FC','','1','Info2','@info2','C','250','40','0','0',''
union all select 'KO','FC','','0','Info3','@info3','N','100','25','0','0',''
union all select 'KO','FC','','1','Info3','@info3','N','150','41','0','0',''
union all select 'KO','FC','','0','Info4','@info4','N','100','25','0','0',''
union all select 'KO','FC','','1','Info4','@info4','C','250','42','0','0',''
union all select 'KO','FC','','0','Info5','@info5','N','100','26','0','0',''
union all select 'KO','FC','','1','Info5','@info5','C','250','43','0','0',''
union all select 'KO','FC','','0','Info6','@info6','C','150','27','0','0',''
union all select 'KO','FC','','1','Info6','@info6','C','100','44','0','0',''
union all select 'KO','FC','','1','Info7','@info7','C','100','45','0','0',''
union all select 'KO','FC','','1','Info8','@info8','N','150','46','0','0',''
union all select 'KO','FC','','1','Info9','@info9','N','150','47','0','0',''
union all select 'KO','FC','','0','Loc munca','@lm','C','150','12','0','0',''
union all select 'KO','FC','','1','Lot','@lot','C','150','35','0','0',''
union all select 'KO','FC','','1','Mod plata','@modplata','C','100','3','0','0',''
union all select 'KO','FC','','0','Numar','@numar','C','100','2','1','0',''
union all select 'KO','FC','','1','Numar','@numar','C','150','2','0','0',''
union all select 'KO','FC','','1','Nr. pozitie','@numarpozitite','N','100','34','0','0',''
union all select 'KO','FC','','1','Obiect','@obiect','C','150','37','0','0',''
union all select 'KO','FC','','0','Pozitii','@pozitii','N','50','19','0','0',''
union all select 'KO','FC','','1','Pret','@pret','N','150','22','1','0',''
union all select 'KO','FC','','0','Punct livrare','@punctlivrare','C','150','11','0','0',''
union all select 'KO','FC','','1','Punct livrare','@punctlivrare','C','150','26','0','0',''
union all select 'KO','FC','','0','Stare','@stare','C','50','21','0','0',''
union all select 'KO','FC','','1','Termen5','@Tcant_realizata','N','100','13','0','0',''
union all select 'KO','FC','','1','Termen1','@Tcantitate','N','150','9','0','0',''
union all select 'KO','FC','','0','Termen','@termen','D','100','5','0','0',''
union all select 'KO','FC','','1','Termen poz.','@termen_poz','C','150','32','0','0',''
union all select 'KO','FC','','1','Termen2','@termene','C','100','10','0','0',''
union all select 'KO','FC','','1','Tert','@tert','C','150','6','0','0',''
union all select 'KO','FC','','0','Tip','@tip','C','50','1','0','0',''
union all select 'KO','FC','','1','Tip','@tip','C','50','1','0','0',''
union all select 'KO','FC','','1','Tip gestiune','@tipgestiune','C','50','28','0','0',''
union all select 'KO','FC','','1','Termen4','@Tpret','N','100','12','0','0',''
union all select 'KO','FC','','1','UM','@um1','C','50','14','1','0',''
union all select 'KO','FC','','1','UM2','@um2','C','50','16','0','0',''
union all select 'KO','FC','','1','UM3','@um3','C','50','19','0','0',''
union all select 'KO','FC','','0','Valoare','@valoare','N','150','18','1','0',''
union all select 'KO','FC','','0','Valuta','@valuta','C','80','16','0','0',''
union all select 'KO','FC','','1','Valuta','@valuta','C','100','8','0','0',''

insert into webconfigFiltre (Meniu, Tip, Ordine, Vizibil, TipObiect, Descriere, Prompt1, DataField1, Interval, Prompt2, DataField2) 
select top 0 null,null,null,null,null,null,null,null,null,null,null
union all select 'KO','BK','5','0','','Denumire gestiune','Denumire gestiune','@f_dengestiune','0','',''
union all select 'KO','BK','7','0','','Den. gest. primitoare','Den. gest.primitoare','@f_dengestprim','0','',''
union all select 'KO','BK','12','0','','Denumire loc munca','Denumire loc munca','@f_denlm','0','',''
union all select 'KO','BK','10','1','','Denumire tert','Denumire tert','@f_dentert','0','',''
union all select 'KO','BK','4','1','','Gestiune','Gestiune','@f_gestiune','0','',''
union all select 'KO','BK','6','0','','Gestiune primitoare','Gestiune primitoare','@f_gestprim','0','',''
union all select 'KO','BK','11','0','','Loc munca','Loc munca','@f_lm','0','',''
union all select 'KO','BK','2','1','','Numar','Numar','@f_numar','0','',''
union all select 'KO','BK','8','1','','Stare','Stare','@f_stare','0','',''
union all select 'KO','BK','9','0','','Tert','Tert','@f_tert','0','',''
union all select 'KO','BK','13','0','','Valoare jos','Valoare jos','@f_valoarejos','0','',''
union all select 'KO','BK','14','0','','Valoare sus','Valoare sus','@f_valoaresus','0','',''
union all select 'KO','FC','5','0','','Denumire gestiune','Denumire gestiune','@f_dengestiune','0','',''
union all select 'KO','FC','7','0','','Den. gest. primitoare','Den. gest.primitoare','@f_dengestprim','0','',''
union all select 'KO','FC','12','0','','Denumire loc munca','Denumire loc munca','@f_denlm','0','',''
union all select 'KO','FC','10','1','','Furnizor','Furnizor','@f_dentert','0','',''
union all select 'KO','FC','4','1','','Gestiune','Gestiune','@f_gestiune','0','',''
union all select 'KO','FC','6','0','','Gestiune primitoare','Gestiune primitoare','@f_gestprim','0','',''
union all select 'KO','FC','11','0','','Loc munca','Loc munca','@f_lm','0','',''
union all select 'KO','FC','2','1','','Numar','Numar','@f_numar','0','',''
union all select 'KO','FC','8','1','','Stare','Stare','@f_stare','0','',''
union all select 'KO','FC','9','0','','Tert','Tert','@f_tert','0','',''
union all select 'KO','FC','13','0','','Valoare jos','Valoare jos','@f_valoarejos','0','',''
union all select 'KO','FC','14','0','','Valoare sus','Valoare sus','@f_valoaresus','0','',''

insert into webconfigTipuri (Meniu, Tip, Subtip, Ordine, Nume, Descriere, TextAdaugare, TextModificare, ProcDate, ProcScriere, ProcStergere, ProcDatePoz, ProcScrierePoz, ProcStergerePoz, Vizibil, Fel, procPopulare,tasta) 
select top 0 null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
union all select 'KO','BK','','2','Comenzi livrare','','','','wIaCon','','wStergCon','wIaPozCon','wScriuPozCon','wStergPozCon','1','','',''
union all select 'KO','BK','BK','1','Produs/serviciu','','','','','','','','','','1','','',''
union all select 'KO','BK','DC','10','Definitivare comanda','Operatia va realiza trecerea comenzii selectate in starea 1 in conditiile in care comanda nu este intr-o stare superioara ( >1 ); daca comanda in cauza se afla in aceasta situatia se va primi o notificare.','','','','wOPDefinitivareComanda','','','','','0','O','wOPDefinitivareComanda_p',''
union all select 'KO','BK','GF','3','Generare factura','           Operatie pentru generarea facturilor pe baza comenzilor de livrare. Se pot factura doar pozitiile care au cantitate disponibila, si numai in limita stocului existent. Exista posibilitatea de a se generara mai multe facturi de pe aceasi comanda de livrare fara insa a se depasi cantitatile disponibile.','','','','wOPGenerareUnAPdinBK','','','','','1','O','wOPGenerareUnAPdinBK_p',''
union all select 'KO','BK','GT','1','Generare transfer','Operatie care va genera document de tip TE din comenzi de livrare. Data aleasa va fi data documentului care va fi generat','','','','wOPGenTEsauAPdinBK','','','','','1','O','',''
union all select 'KO','BK','RS','2','Rezervare stoc','Operatie pentru rezervare stoc pe comanda de livrare.','','','','wOPRezervareStocBK','','','','','1','O','wOPRezervareStocBK_p',''
union all select 'KO','BK','ST','9','Schimbare stare','','','','','wOPSchimbStare','','','','','1','O','',''
union all select 'KO','BK','YW','8','Refacere cant.realiz','','','','','wOPRefacereCantitatiRealizate','','','','','0','O','wOPRefacereCantitatiRealizate_p',''
union all select 'KO','FC','','4','Comenzi aprov','','','','wIaCon','','wStergCon','wIaPozCon','wScriuPozCon','wStergPozCon','1','','',''
union all select 'KO','FC','DC','2','Definitivare comanda','Operatie pentru definitivarea unei comenzi','','','','wOPSchimbStare','','','','','0','O','',''
union all select 'KO','FC','FC','1','Produs/serviciu','','','','','','','','','','1','','',''
union all select 'KO','FC','ST','1','Schimbare stare','','','','','wOPSchimbStare','','','','','1','O','',''
union all select 'KO','FC','YW','8','Refacere cant.realiz','','','','','wOPRefacereCantitatiRealizate','','','','','0','O','wOPRefacereCantitatiRealizate_p',''

insert into webconfigForm (Meniu, Tip, Subtip, Ordine, Nume, TipObiect, DataField, LabelField, Latime, Vizibil, Modificabil, ProcSQL, ListaValori, ListaEtichete, Initializare, Prompt, Procesare, Tooltip, formula)
select top 0 null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
union all select 'KO','BK','','36','Categ. pret','AC','@categpret','@dencategpret','300','0','1','wACCategPret','','','','Categorie pret','','',''
union all select 'KO','BK','','30','Contr. coresp.','AC','@contr_cadru','@contr_cadru','300','1','1','wACContracte','','','','Contract Corespondent','','',''
union all select 'KO','BK','','30','Contr. coresp.','AC','@contractcor','@contractcor','300','0','1','wACContracte','','','','Contract corespondent','','',''
union all select 'KO','BK',' ','3','Data','D','@data','','100','1','1','','','','','Data','','',''
union all select 'KO','BK',' ','23','Stare','C','@denstare','','150','0','0','','','','','Stare','','',''
union all select 'KO','BK',' ','11','Explicatii','C','@explicatii','','250','1','1','','','','','Explicatii','','',''
union all select 'KO','BK',' ','8','Factura','C','@factura','','150','0','1',' ','','','','Factura','','',''
union all select 'KO','BK',' ','4','Gestiune','AC','@gestiune','@dengestiune','150','1','1','wACGestiuni','','','','Gestiune','','',''
union all select 'KO','BK',' ','5','Gest. prim.','AC','@gestprim','@dengestprim','150','0','1','wACGestiuni','','','','Gestiune primitoare','','',''
union all select 'KO','BK',' ','12','Info1','C','@info1','','150','0','0','','','','','Info1','','',''
union all select 'KO','BK',' ','13','Info2','N','@info2','','150','0','0','','','','','Info2','','',''
union all select 'KO','BK',' ','14','Info3','N','@info3','','150','0','0','','','','','Info3','','',''
union all select 'KO','BK',' ','15','Info4','N','@info4','','150','0','0','','','','','Info4','','',''
union all select 'KO','BK',' ','16','Info5','N','@info5','','150','0','0','','','','','Info5','','',''
union all select 'KO','BK',' ','17','Info6','C','@info6','','200','0','0','','','','','Info6','','',''
union all select 'KO','BK',' ','10','Loc munca','AC','@lm','@denlm','150','1','1','wACLocm','','','','Loc munca','','',''
union all select 'KO','BK',' ','2','Comanda','C','@numar','','150','1','0','','','','','Contract','','',''
union all select 'KO','BK',' ','7','Punct livrare','AC','@punctlivrare','@punctlivrare','150','0','1','wACPuncteLivrare','','','','Punct livrare','','',''
union all select 'KO','BK',' ','9','Termen','D','@termen','','100','0','0','','','','','Termen','','',''
union all select 'KO','BK',' ','6','Beneficiar','AC','@tert','@dentert','250','1','1','wACTerti','','','','Tert','','',''
union all select 'KO','BK',' ','1','Tip','C','@tip','','50','0','0','','','','','Tip','','',''
union all select 'KO','BK',' ','20','Valoare','N','@valoare','','150','0','0','','','','','Valoare','','',''
union all select 'KO','BK','BK','3','Cantitate','N','@cantitate','','150','1','1','','','','','Cantitate','','',''
union all select 'KO','BK','BK','6','Cantitate','N','@cantitateum1','','150','0','1','','','','','Cantitate UM1','','',''
union all select 'KO','BK','BK','7','Cantitate um2','N','@cantitateum2','','150','0','1','','','','','Cantitate UM2','','',''
union all select 'KO','BK','BK','8','Cantitate UM3','N','@cantitateum3','','150','0','1','','','','','Cantitate UM3','','',''
union all select 'KO','BK','BK','10','Categ. pret','AC','@categpret','@categpret','150','1','1','wACCategPret','','','','Categorie pret','','',''
union all select 'KO','BK','BK','1','Cod','AC','@cod','@denumire','350','1','1','wACNomenclator','','','','Cod','','',''
union all select 'KO','BK','BK','13','Cota tva','N','@cotatva','','100','0','1','','','','','Cota tva','','',''
union all select 'KO','BK','BK','11','Curs','C','@curs','','50','0','1','','','','','Curs','','',''
union all select 'KO','BK','BK','16','Data exp.','D','@dataexpirarii','','100','0','1','','','','','Data expirarii','','',''
union all select 'KO','BK','BK','12','Discount','N','@discount','','150','0','1','','','','','Discount','','',''
union all select 'KO','BK','BK','14','Explicatii','N','@explicatii','','250','0','1','','','','','Explicatii','','',''
union all select 'KO','BK','BK','2','Gestiune','AC','@gestiune','@gestiune','150','0','1','wACGestiuni','','','','Gestiune','','',''
union all select 'KO','BK','BK','18','Info1','N','@info1','','150','0','1','','','','','Info1','','',''
union all select 'KO','BK','BK','27','Info10','N','@info10','','150','0','1','','','','','Info10','','',''
union all select 'KO','BK','BK','28','Info11','N','@info11','','150','0','1','','','','','Info11','','',''
union all select 'KO','BK','BK','29','Info12','C','@info12','','200','0','1','','','','','Info12','','',''
union all select 'KO','BK','BK','30','Info13','C','@info13','','200','0','1','','','','','Info13','','',''
union all select 'KO','BK','BK','31','Info14','C','@info14','','200','0','1','','','','','Info14','','',''
union all select 'KO','BK','BK','32','Info15','C','@info15','','200','0','1','','','','','Info15','','',''
union all select 'KO','BK','BK','33','Info16','C','@info16','','200','0','1','','','','','Info16','','',''
union all select 'KO','BK','BK','34','Info17','C','@info17','','200','0','1','','','','','Info17','','',''
union all select 'KO','BK','BK','19','Info2','C','@info2','','250','0','1','','','','','Info2','','',''
union all select 'KO','BK','BK','20','Info3','N','@info3','','150','0','1','','','','','Info3','','',''
union all select 'KO','BK','BK','21','Info4','C','@info4','','250','0','1','','','','','Info4','','',''
union all select 'KO','BK','BK','22','Info5','C','@info5','','250','0','1','','','','','Info5','','',''
union all select 'KO','BK','BK','23','Info6','D','@info6','','100','0','1','','','','','Info6','','',''
union all select 'KO','BK','BK','24','Info7','D','@info7','','100','0','1','','','','','Info7','','',''
union all select 'KO','BK','BK','25','Info8','N','@info8','','150','0','1','','','','','Info8','','',''
union all select 'KO','BK','BK','26','Info9','N','@info9','','150','0','1','','','','','Info9','','',''
union all select 'KO','BK','BK','15','Lot','C','@lot','','150','0','1','','','','','Lot','','',''
union all select 'KO','BK','BK','0','Mod plata','C','@modplata',' ','100','0','1',' ','','','','Selectati','','',''
union all select 'KO','BK','BK','35','Nr. pozitie','N','@numarpozitie','','150','0','1','','','','','Nr. pozitie','','',''
union all select 'KO','BK','BK','17','Obiect','C','@obiect','','150','0','1','','','','','Obiect','','',''
union all select 'KO','BK','BK','9','Pret','N','@pret','','150','1','1','','','','','Pret','','',''
union all select 'KO','BK','BK','4','Termen1','N','@Tcantitate','','150','0','1','','','','','Termen1','','',''
union all select 'KO','BK','BK','5','Termen2','N','@Tpret','','100','0','1','','','','','Termen2','','',''
union all select 'KO','BK','DC','2','Numar','C','@contract','','300','0','0','','','','','','','',''
union all select 'KO','BK','DC','1','Definitivare comanda','CHB','@definitivare','','300','0','0','','','','','','','',''
union all select 'KO','BK','GF','3','Data factura','D','@datadoc','','100','1','1','','','','','Data transfer','','',''
union all select 'KO','BK','GF','1','Beneficiar','C','@dentert','','350','1','0','','','','','Tert','','',''
union all select 'KO','BK','GF','9','Eliberat','C','@eliberat','','150','1','1','','','','','','','',''
union all select 'KO','BK','GF','5','Mijloc de transport','C','@mijloctp','','150','1','1','','','','','Mijloc de transport','','',''
union all select 'KO','BK','GF','6','Numar mijl transport','C','@nrmijltransp','','100','1','1','','','','','Nr mijloc de transport','','',''
union all select 'KO','BK','GF','8','Numar Buletin','C','@numarbuletin','','100','1','1','','','','','','','',''
union all select 'KO','BK','GF','2','Factura','C','@numardoc','','100','1','1','','','','','Numar transfer','','',''
union all select 'KO','BK','GF','4','Nume delegat','C','@numedelegat','','150','1','1','','','','','Nume delegat','','',''
union all select 'KO','BK','GF','10','Observatii','C','@observatii','','300','1','1','','','','','Observatii','','',''
union all select 'KO','BK','GF','7','Serie Buletin','C','@seriabuletin','','150','1','1','','','','','','','',''
union all select 'KO','BK','GT','5','Data','D','@datadoc','','100','1','1','','','','','','','',''
union all select 'KO','BK','GT','9','Eliberat','C','@eliberat','','150','0','1','','','','','','','',''
union all select 'KO','BK','GT','4','Gestiune transp.','AC','@gesttr','@dengestiune','200','1','1','wACGestiuniD','','','','Gestiune transp','','',''
union all select 'KO','BK','GT','5','Mijloc de transport','C','@mijloctp','','150','0','1','','','','','Mijloc de transport','','',''
union all select 'KO','BK','GT','2','Numar mijl transport','C','@nrmijltransp','','100','1','1','','','','','Nr mijloc de transport','','',''
union all select 'KO','BK','GT','8','Numar Buletin','C','@numarbuletin','','100','0','1','','','','','','','',''
union all select 'KO','BK','GT','1','Numar transfer','C','@numardoc','','100','0','1','','','','','Numar transfer','','',''
union all select 'KO','BK','GT','1','Nume delegat','C','@numedelegat','','100','1','1','','','','','Nume delegat','','',''
union all select 'KO','BK','GT','3','Observatii','C','@observatii','','100','1','1','','','','','Observatii','','',''
union all select 'KO','BK','GT','7','Serie Buletin','C','@seriabuletin','','150','0','1','','','','','','','',''
union all select 'KO','BK','RS','3','Cod','AC','@cod',' ','300','0','1','wACNomenclator','','','','Cod','','',''
union all select 'KO','BK','RS','1','Data','D','@data_rez','','100','1','1','','','','','','','',''
union all select 'KO','BK','RS','5','Gestiune de rezervari','AC','@gestiune_rez','@dengest_rez','300','1','1','wACGestiuni','','','','Gestiune  de rezervari','','',''
union all select 'KO','BK','RS','4','Gestiune sursa','AC','@gestiune_sursa','@dengest_sursa','300','1','1','wACGestiuni','','','','Gestiune sursa','','',''
union all select 'KO','BK','RS','2','Comanda de livrare','AC','@numar','@numar','100','1','1','','','','','Comanda de livrare','','',''
union all select 'KO','BK','RS','6','Numar document','C','@numar_doc','','100','1','0','','','','','','','',''
union all select 'KO','BK','RS','1','Beneficiar','AC','@tert','@dentert','300','1','1','','','','','Beneficiar','','',''
union all select 'KO','BK','ST','1','Schimbare stare','CB','@stare','','100','1','1','','0-Operat,1-Definitiv,2-Blocat,3-Confirmat,4-Transferat,6-Realizat,7-Reziliat','','','Stare','','',''
union all select 'KO','BK','YW','6','Comenzi livrare','CHB','@comenziLivrBK','','300','0','0','','','','','','','',''
union all select 'KO','BK','YW','12','Contract','C','@fltContract','','150','0','0','','','','','','','',''
union all select 'KO','BK','YW','2','Recalculare realizari','CHB','@recalculareRealizari','','300','0','1','','','','','','','',''
union all select 'KO','BK','YW','1','Stergere realizari','CHB','@stergereRealizari','','300','0','1','','','','','','','',''
union all select 'KO','FC','','30','Contr. coresp.','AC','@contractcor','@contractcor','300','0','1','wACContracte','','','','Contract Corespondent','','',''
union all select 'KO','FC','','4','Stare','C','@denstare','','150','0','0','','','','','Stare','','',''
union all select 'KO','FC','','22','Valoare','N','@valoare','','150','0','0','','','','','Valoare','','',''
union all select 'KO','FC',' ','9','Contract cor.','C','@contractcor','','100','1','0','','','','','','','',''
union all select 'KO','FC',' ','3','Data','D','@data','','100','1','1','','','','','Data','','',''
union all select 'KO','FC',' ','10','Explicatii','C','@explicatii','','250','0','0','','','','','Explicatii','','',''
union all select 'KO','FC',' ','7','Factura','C','@factura','','150','0','1',' ','','','','Factura','','',''
union all select 'KO','FC',' ','4','Gestiune','AC','@gestiune','@dengestiune','200','0','1','wACGestiuni','','','','Gestiune','','',''
union all select 'KO','FC',' ','5','Gest. primitoare','AC','@gestprim','@gestprim','150','0','1','wACGestiuni','','','','Gestiune primitoare','','',''
union all select 'KO','FC',' ','11','Info1','C','@info1','','150','0','0','','','','','Info1','','',''
union all select 'KO','FC',' ','12','Info2','N','@info2','','150','0','0','','','','','Info2','','',''
union all select 'KO','FC',' ','13','Info3','N','@info3','','150','0','0','','','','','Info3','','',''
union all select 'KO','FC',' ','14','Info4','N','@info4','','150','0','0','','','','','Info4','','',''
union all select 'KO','FC',' ','15','Info5','N','@info5','','150','0','0','','','','','Info5','','',''
union all select 'KO','FC',' ','16','Info6','C','@info6','','200','0','0','','','','','Info6','','',''
union all select 'KO','FC',' ','7','Loc munca','AC','@lm','@denlm','200','1','0','wACLocm','','','','Loc munca','','',''
union all select 'KO','FC',' ','2','Comanda','C','@numar','','150','1','0','','','','','Contract','','',''
union all select 'KO','FC',' ','6','Punct livrare','AC','@punctlivrare','','150','0','1','wACPuncteLivrare','','','','Punct livrare','','',''
union all select 'KO','FC',' ','6','Zile scadenta','N','@scadenta',' ','50','0','1','','','','','Scadenta','','',''
union all select 'KO','FC',' ','8','Termen','D','@termen','','100','1','0','','','','','Termen','','',''
union all select 'KO','FC',' ','4','Furnizor','AC','@tert','@dentert','250','1','1','wACTerti','','','','Selectati un tert','','',''
union all select 'KO','FC',' ','1','Tip','C','@tip','','50','0','0','','','','','Tip','','',''
union all select 'KO','FC',' ','9','Valabilitate','D','@valabilitate','','100','0','1','','','','','Valabilitate','','',''
union all select 'KO','FC','DC','1','Definitivare comanda','CHB','@definitivare','','300','0','1','','','','','','','',''
union all select 'KO','FC','FC','3','Cantitate','N','@cantitate','','150','1','1','','','','','Cantitate','','',''
union all select 'KO','FC','FC','6','Cantitate','N','@cantitateum1','','150','0','1','','','','','Cantitate UM1','','',''
union all select 'KO','FC','FC','7','Cantitate um2','N','@cantitateum2','','150','0','1','','','','','Cantitate UM2','','',''
union all select 'KO','FC','FC','8','Cantitate UM3','N','@cantitateum3','','150','0','1','','','','','Cantitate UM3','','',''
union all select 'KO','FC','FC','10','Categ. pret','AC','@categpret','@categpret','50','0','1','wACCategPret','','','','Categorie pret','','',''
union all select 'KO','FC','FC','1','Cod','AC','@cod','@denumire','250','1','1','wACNomenclatorCon','','','','Cod','','',''
union all select 'KO','FC','FC','13','Cota tva','N','@cotatva','','100','1','1','','','','','Cota tva','','',''
union all select 'KO','FC','FC','11','Curs','C','@curs','','50','0','1','','','','','Curs','','',''
union all select 'KO','FC','FC','16','Data exp.','D','@dataexpirarii','','100','0','1','','','','','Data expirarii','','',''
union all select 'KO','FC','FC','12','Discount','N','@discount','','150','0','1','','','','','Discount','','',''
union all select 'KO','FC','FC','14','Explicatii','N','@explicatii','','250','0','1','','','','','Explicatii','','',''
union all select 'KO','FC','FC','2','Gestiune','AC','@gestiune','@dengestiune','150','0','1','wACGestiuni','','','','Gestiune','','',''
union all select 'KO','FC','FC','18','Info1','N','@info1','','150','0','1','','','','','Info1','','',''
union all select 'KO','FC','FC','27','Info10','N','@info10','','150','0','1','','','','','Info10','','',''
union all select 'KO','FC','FC','28','Info11','N','@info11','','150','0','1','','','','','Info11','','',''
union all select 'KO','FC','FC','29','Info12','C','@info12','','200','0','1','','','','','Info12','','',''
union all select 'KO','FC','FC','30','Info13','C','@info13','','200','0','1','','','','','Info13','','',''
union all select 'KO','FC','FC','31','Info14','C','@info14','','200','0','1','','','','','Info14','','',''
union all select 'KO','FC','FC','32','Info15','C','@info15','','200','0','1','','','','','Info15','','',''
union all select 'KO','FC','FC','33','Info16','C','@info16','','200','0','1','','','','','Info16','','',''
union all select 'KO','FC','FC','34','Info17','C','@info17','','200','0','1','','','','','Info17','','',''
union all select 'KO','FC','FC','19','Info2','C','@info2','','250','0','1','','','','','Info2','','',''
union all select 'KO','FC','FC','20','Info3','N','@info3','','150','0','1','','','','','Info3','','',''
union all select 'KO','FC','FC','21','Info4','C','@info4','','250','0','1','','','','','Info4','','',''
union all select 'KO','FC','FC','22','Info5','C','@info5','','250','0','1','','','','','Info5','','',''
union all select 'KO','FC','FC','23','Info6','D','@info6','','100','0','1','','','','','Info6','','',''
union all select 'KO','FC','FC','24','Info7','D','@info7','','100','0','1','','','','','Info7','','',''
union all select 'KO','FC','FC','25','Info8','N','@info8','','150','0','1','','','','','Info8','','',''
union all select 'KO','FC','FC','26','Info9','N','@info9','','150','0','1','','','','','Info9','','',''
union all select 'KO','FC','FC','15','Lot','C','@lot','','150','0','1','','','','','Lot','','',''
union all select 'KO','FC','FC','0','Mod plata','C','@modplata',' ','100','0','1',' ','','','','Selectati','','',''
union all select 'KO','FC','FC','35','Nr. pozitie','N','@numarpozitie','','150','0','1','','','','','Nr. pozitie','','',''
union all select 'KO','FC','FC','17','Obiect','C','@obiect','','150','0','1','','','','','Obiect','','',''
union all select 'KO','FC','FC','9','Pret','N','@pret','','150','1','1','','','','','Pret','','',''
union all select 'KO','FC','FC','4','Termen1','N','@Tcantitate','','150','0','1','','','','','Termen1','','',''
union all select 'KO','FC','FC','5','Termen2','N','@Tpret','','100','0','1','','','','','Termen2','','',''
union all select 'KO','FC','ST','1','Schimbare stare','CB','@stare','','100','1','1','','15,0-Operat,1-Definitiv,2-Blocat,3-Confirmat,4-Expediat,5- In vama,6-Realizat,7-Reziliat',' ','','Stare','','',''
union all select 'KO','FC','YW','5','Comenzi aprovizionare','CHB','@comenziAprovFC','','300','0','0','','','','','','','',''
union all select 'KO','FC','YW','12','Contract','C','@fltContract','','150','0','0','','','','','','','',''
union all select 'KO','FC','YW','2','Recalculare realizari','CHB','@recalculareRealizari','','300','0','1','','','','','','','',''
union all select 'KO','FC','YW','1','Stergere realizari','CHB','@stergereRealizari','','300','0','1','','','','','','','',''

insert into webconfigtaburi (MeniuSursa,TipSursa,NumeTab,icoana,TipMachetaNoua,MeniuNou,TipNou,ProcPopulare,Ordine,Vizibil)
select top 0 null,null,null,null,null,null,null,null,null,null