
delete from webconfiggrid where meniu='DO' and (''='' or isnull(tip,'')='') and ('MA'='' or isnull(subtip,'')='MA')
delete from webconfigtipuri where meniu='DO' and (''='' or isnull(tip,'')='') and ('MA'='' or isnull(subtip,'')='MA')
delete from webconfigform where meniu='DO' and (''='' or isnull(tip,'')='') and ('MA'='' or isnull(subtip,'')='MA')
--delete from webConfigTaburi where MeniuSursa='DO' and (''='' or isnull(TipSursa,'')='')


insert into webconfiggrid (Meniu, Tip, Subtip, InPozitii, NumeCol, DataField, TipObiect, Latime, Ordine, Vizibil, Modificabil, Formula) 
select top 0 null,null,null,null,null,null,null,null,null,null,null,null

insert into webconfigTipuri (Meniu, Tip, Subtip, Ordine, Nume, Descriere, TextAdaugare, TextModificare, ProcDate, ProcScriere, ProcStergere, ProcDatePoz, ProcScrierePoz, ProcStergerePoz, Vizibil, Fel, procPopulare,tasta) 
select top 0 null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
union all select 'DO','AE','MA','6','Modificare antet','','','','','wOPModificareAntetDoc','','','','','1','O','wOPModificareAntetDoc_p',''
union all select 'DO','AI','MA','6','Modificare antet','','','','','wOPModificareAntetDoc','','','','','1','O','wOPModificareAntetDoc_p',''
union all select 'DO','AP','MA','6','Modificare antet','          Operatie care permite schimbarea datelor din antet.','','','','wOPModificareAntetDoc','','','','','1','O','wOPModificareAntetDoc_p',''
union all select 'DO','AS','MA','6','Modificare antet','          Operatie care permite schimbarea datelor din antet.','','','','wOPModificareAntetDoc','','','','','1','O','wOPModificareAntetDoc_p',''
union all select 'DO','CM','MA','6','Modificare antet','','','','','wOPModificareAntetDoc','','','','','1','O','wOPModificareAntetDoc_p',''
union all select 'DO','DF','MA','6','Modificare antet','','','','','wOPModificareAntetDoc','','','','','1','O','wOPModificareAntetDoc_p','U'
union all select 'DO','PF','MA','6','Modificare antet','','','','','wOPModificareAntetDoc','','','','','1','O','wOPModificareAntetDoc_p','U'
union all select 'DO','RC','MA','6','Modificare antet','','','','','wOPModificareAntetDoc','','','','','1','O','wOPModificareAntetDoc_p',''
union all select 'DO','RM','MA','6','Modificare antet','          Operatie care permite schimbarea datelor din antet.','','','','wOPModificareAntetDoc','','','','','1','O','wOPModificareAntetDoc_p','U'
union all select 'DO','RS','MA','6','Modificare antet','          Operatie care permite schimbarea datelor din antet.','','','','wOPModificareAntetDoc','','','','','1','O','wOPModificareAntetDoc_p',''
union all select 'DO','TE','MA','6','Modificare antet','          Operatie care permite schimbarea datelor din antet.','','','','wOPModificareAntetDoc','','','','','1','O','wOPModificareAntetDoc_p',''

insert into webconfigForm (Meniu, Tip, Subtip, Ordine, Nume, TipObiect, DataField, LabelField, Latime, Vizibil, Modificabil, ProcSQL, ListaValori, ListaEtichete, Initializare, Prompt, Procesare, Tooltip, formula)
select top 0 null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
union all select 'DO','AE','MA','6','Comanda','AC','@comanda','@dencomanda','300','1','1','wACComenzi','','','','Comanda','','',''
union all select 'DO','AE','MA','14','Cont coresp.','AC','@contcorespondent','@contcorespondent','200','1','0','wACConturi','','','','Cont coresp.','','',''
union all select 'DO','AE','MA','2','Data','D','@data','','100','1','1','','','','','','','',''
union all select 'DO','AE','MA','14','Explicatii','C','@explicatii','','300','1','1','','','','','Explicatii','','',''
union all select 'DO','AE','MA','3','Gestiune','AC','@gestiune','@dengestiune','300','1','1','wACGestiuni','','','','Gestiune','','',''
union all select 'DO','AE','MA','7','Loc munca','AC','@lm','@denlm','200','1','1','wACLocm','','','','Loc munca','','',''
union all select 'DO','AE','MA','1','Numar','C','@numar','','80','1','1','','','','','','','',''
union all select 'DO','AI','MA','6','Comanda','AC','@comanda','@dencomanda','300','1','1','wACComenzi','','','','Comanda','','',''
union all select 'DO','AI','MA','13','Cont coresp.','AC','@contcorespondent','@contcorespondent','200','1','1','wACConturi','','','','Cont coresp.','','',''
union all select 'DO','AI','MA','2','Data','D','@data','','100','1','1','','','','','','','',''
union all select 'DO','AI','MA','3','Gestiune','AC','@gestiune','@dengestiune','300','1','1','wACGestiuni','','','','Gestiune','','',''
union all select 'DO','AI','MA','7','Loc munca','AC','@lm','@denlm','200','1','1','wACLocm','','','','Loc munca','','',''
union all select 'DO','AI','MA','1','Numar','C','@numar','','80','1','1','','','','','','','',''
union all select 'DO','AP','MA','16','Categ. pret','AC','@categpret','@dencatpret','200','0','1','wACCategPret','','','','Categ. pret','','',''
union all select 'DO','AP','MA','6','Comanda','AC','@comanda','@dencomanda','300','0','1','wACComenzi','','','','Comanda','','',''
union all select 'DO','AP','MA','15','Cont de stoc','AC','@cont_stoc','@dencontstoc','300','0','1','wACConturi','','','','Cont de stoc','','',''
union all select 'DO','AP','MA','12','Cont fact.','AC','@contfactura','@dencontfactura','300','1','1','wACConturi','','','','Cont fact.','','',''
union all select 'DO','AP','MA','18','Contract','C','@contract','','300','0','0','','','','','Contract','','',''
union all select 'DO','AP','MA','13','Cont ven.','AC','@contvenituri','@dencontvenituri','300','0','1','wACConturi','','','','Cont','','',''
union all select 'DO','AP','MA','2','Data','D','@data','','100','1','1','','','','','','','',''
union all select 'DO','AP','MA','25','Data expedierii','D','@dataexpedierii','','200','0','0','','','','','Data exp.','','',''
union all select 'DO','AP','MA','10','Data facturii','D','@datafacturii','','100','1','1','','','','','Data facturii','','',''
union all select 'DO','AP','MA','11','Data scadentei','D','@datascadentei','','100','0','1','','','','','Data scad.','','',''
union all select 'DO','AP','MA','11','Discount','N','@discount','','100','0','1','','','','','','','',''
union all select 'DO','AP','MA','22','Eliberat','C','@eliberat','','200','0','0','','','','','Eliberat','','',''
union all select 'DO','AP','MA','14','Explicatii','C','@explicatii','','300','1','1','','','','','Explicatii','','',''
union all select 'DO','AP','MA','6','Factura','C','@factura','','100','1','1',' ','','','','Factura','','',''
union all select 'DO','AP','MA','3','Gestiune','AC','@gestiune','@dengestiune','300','1','1','wACGestiuni','','','','Gestiune','','',''
union all select 'DO','AP','MA','9','Gest. prim.','AC','@gestprim','','300','0','0','wACGestiuniPrim','','','','Gest. prim.','','',''
union all select 'DO','AP','MA','5','Indicator bug.','AC','@indbug','@denbug','400','0','1','wACIndBug','','','','Indicator bugetar','','',''
union all select 'DO','AP','MA','4','Loc munca','AC','@lm','@denlm','200','0','1','wACLocm','','','','Loc munca','','',''
union all select 'DO','AP','MA','23','Mijl.transp.','C','@mijloctp','','200','0','0','','','','','Mijl.transp.','','',''
union all select 'DO','AP','MA','24','Nr. mijl.transp.','C','@nrmijloctp','','200','0','0','','','','','Nr.mijl.transp.','','',''
union all select 'DO','AP','MA','1','Numar','C','@numar','','100','1','1','','','','','','','',''
union all select 'DO','AP','MA','21','Nr. buletin','C','@numarbuletin','','150','0','0','','','','','Nr. buletin','','',''
union all select 'DO','AP','MA','19','Nume delegat','C','@numedelegat','','300','0','0','','','','','Nume delegat','','',''
union all select 'DO','AP','MA','27','Observatii','C','@observatii','','200','0','0','','','','','Observatii','','',''
union all select 'DO','AP','MA','26','Ora expedierii','C','@oraexpedierii','','100','0','0','','','','','Ora exp.','','',''
union all select 'DO','AP','MA','15','Pct. livrare','AC','@punctlivrare','@denpunctlivrare','200','1','1','wACPuncteLivrare','','','','Pct. livrare','','',''
union all select 'DO','AP','MA','28','Pct. livrare exped.','C','@punctlivrareexped','','200','0','0','','','','','Pct.livr.exped','','',''
union all select 'DO','AP','MA','20','Seria buletin','C','@seriabuletin','','100','0','0','','','','','Seria buletin','','',''
union all select 'DO','AP','MA','5','Client','AC','@tert','@dentert','300','1','1','wACTerti','','','','Tert','','',''
union all select 'DO','AP','MA','2','Tip','C','@tip','','30','0','0','','','','','','','',''
union all select 'DO','AP','MA','29','Tip TVA','CB','@tiptva','@tiptva','200','1','0','','0,1,2','0-Tva deductibil,1-TVA Compenst,2-TVA Neinregistrat','','Tip TVA','','',''
union all select 'DO','AP','MA','17','Tva neex.','N','@tvaneexigibil','','200','0','0','','','','','Tva neex.','','',''
union all select 'DO','AP','MA','14','Val cu TVA','N','@valtotala',' ','100','0','0','','','','','Valoare cu TVA','','',''
union all select 'DO','AS','MA','16','Categ. pret','AC','@categpret','@dencatpret','200','1','1','wACCategPret','','','','Categ. pret','','',''
union all select 'DO','AS','MA','6','Comanda','AC','@comanda','@dencomanda','300','0','1','wACComenzi','','','','Comanda','','',''
union all select 'DO','AS','MA','15','Cont de stoc','AC','@cont_stoc','@dencontstoc','300','1','1','wACConturi','','','','Cont de stoc','','',''
union all select 'DO','AS','MA','12','Cont fact.','AC','@contfactura','@dencontfactura','300','1','1','wACConturi','','','','Cont fact.','','',''
union all select 'DO','AS','MA','18','Contract','C','@contract','','300','0','0','','','','','Contract','','',''
union all select 'DO','AS','MA','5','Cont','AC','@contvenituri','@dencontvenituri','300','0','1','wACConturi','','','','Cont','','',''
union all select 'DO','AS','MA','2','Data','D','@data','','100','1','1','','','','','','','',''
union all select 'DO','AS','MA','25','Data expedierii','D','@dataexpedierii','','200','0','0','','','','','Data exp.','','',''
union all select 'DO','AS','MA','10','Data facturii','D','@datafacturii','','100','1','1','','','','','Data facturii','','',''
union all select 'DO','AS','MA','11','Data scadentei','D','@datascadentei','','100','1','1','','','','','Data scad.','','',''
union all select 'DO','AS','MA','11','Discount','N','@discount','','100','1','1','','','','','','','',''
union all select 'DO','AS','MA','22','Eliberat','C','@eliberat','','200','0','0','','','','','Eliberat','','',''
union all select 'DO','AS','MA','14','Explicatii','C','@explicatii','','300','1','1','','','','','Explicatii','','',''
union all select 'DO','AS','MA','6','Factura','C','@factura','','100','1','1',' ','','','','Factura','','',''
union all select 'DO','AS','MA','3','Gestiune','AC','@gestiune','@dengestiune','300','1','1','wACGestiuni','','','','Gestiune','','',''
union all select 'DO','AS','MA','9','Gest. prim.','AC','@gestprim','','300','0','0','wACGestiuniPrim','','','','Gest. prim.','','',''
union all select 'DO','AS','MA','5','Indicator bug.','AC','@indbug','@denbug','400','0','1','wACIndBug','','','','Indicator bugetar','','',''
union all select 'DO','AS','MA','4','Loc munca','AC','@lm','@denlm','200','1','1','wACLocm','','','','Loc munca','','',''
union all select 'DO','AS','MA','23','Mijl.transp.','C','@mijloctp','','200','0','0','','','','','Mijl.transp.','','',''
union all select 'DO','AS','MA','24','Nr. mijl.transp.','C','@nrmijloctp','','200','0','0','','','','','Nr.mijl.transp.','','',''
union all select 'DO','AS','MA','1','Numar','C','@numar','','100','1','1','','','','','','','',''
union all select 'DO','AS','MA','21','Nr. buletin','C','@numarbuletin','','150','0','0','','','','','Nr. buletin','','',''
union all select 'DO','AS','MA','19','Nume delegat','C','@numedelegat','','300','0','0','','','','','Nume delegat','','',''
union all select 'DO','AS','MA','27','Observatii','C','@observatii','','200','0','0','','','','','Observatii','','',''
union all select 'DO','AS','MA','26','Ora expedierii','C','@oraexpedierii','','100','0','0','','','','','Ora exp.','','',''
union all select 'DO','AS','MA','15','Pct. livrare','AC','@punctlivrare','@denpunctlivrare','200','1','1','wACPuncteLivrare','','','','Pct. livrare','','',''
union all select 'DO','AS','MA','28','Pct. livrare exped.','C','@punctlivrareexped','','200','0','0','','','','','Pct.livr.exped','','',''
union all select 'DO','AS','MA','20','Seria buletin','C','@seriabuletin','','100','0','0','','','','','Seria buletin','','',''
union all select 'DO','AS','MA','5','Client','AC','@tert','@dentert','300','1','1','wACTerti','','','','Tert','','',''
union all select 'DO','AS','MA','2','Tip','C','@tip','','30','1','0','','','','','','','',''
union all select 'DO','AS','MA','29','Tip TVA','CB','@tiptva','@tiptva','200','1','0','','0,1,2','0-Tva deductibil,1-TVA Compenst,2-TVA Neinregistrat','','Tip TVA','','',''
union all select 'DO','AS','MA','17','Tva neex.','N','@tvaneexigibil','','200','0','0','','','','','Tva neex.','','',''
union all select 'DO','AS','MA','14','Val cu TVA','N','@valtotala',' ','100','1','0','','','','','Valoare cu TVA','','',''
union all select 'DO','CM','MA','2','Data','D','@data','','100','1','1','','','','','','','',''
union all select 'DO','CM','MA','3','Gestiune','AC','@gestiune','@dengestiune','300','1','1','wACGestiuni','','','','Gestiune','','',''
union all select 'DO','CM','MA','4','Loc munca','AC','@lm','@denlm','200','1','1','wACLocm','','','','Loc munca','','',''
union all select 'DO','CM','MA','1','Numar','C','@numar','','100','1','1','','','','','','','',''
union all select 'DO','CM','MA','2','Tip','C','@tip','','30','1','0','','','','','','','',''
union all select 'DO','DF','MA','2','Data','D','@data','','100','1','1','','','','','','','',''
union all select 'DO','DF','MA','4','Gestiune','AC','@gestiune','@dengestiune','300','1','1','wACGestiuni','','','','Gestiune','','',''
union all select 'DO','DF','MA','5','Salariat','AC','@gestprim','@dengestprim','300','1','1','wACSalariati','','','','Marca sau numele','','',''
union all select 'DO','DF','MA','3','Loc munca','AC','@lm','@denlm','200','1','1','wACLocm','','','','Loc munca','','',''
union all select 'DO','DF','MA','1','Numar','C','@numar','','100','1','1','','','','','','','',''
union all select 'DO','PF','MA','2','Data','D','@data','','100','1','1','','','','','','','',''
union all select 'DO','PF','MA','3','Marca pred.','AC','@gestiune','@dengestiune','300','1','1','wACSalariati','','','','Marca predatoare','','',''
union all select 'DO','PF','MA','5','Marca prim.','AC','@gestprim','@dengestprim','300','1','1','wACSalariati','','','','Marca. primitoare','','',''
union all select 'DO','PF','MA','4','Loc m. pred.','AC','@lm','@denlm','200','1','1','wACLocm','','','','Loc munca','','',''
union all select 'DO','PF','MA','6','Loc m. prim.','AC','@lmprim','@denlmprim','200','1','1','wACLocm','','','','Loc de munca prim','','',''
union all select 'DO','PF','MA','1','Numar','C','@numar','','80','1','1','','','','','','','',''
union all select 'DO','RC','MA','16','Categ. pret','AC','@categpret','@dencatpret','200','0','1','wACCategPret','','','','Categ. pret','','',''
union all select 'DO','RC','MA','6','Comanda','AC','@comanda','@dencomanda','300','0','1','wACComenzi','','','','Comanda','','',''
union all select 'DO','RC','MA','15','Cont de stoc','AC','@cont_stoc','@dencontstoc','300','0','1','wACConturi','','','','Cont de stoc','','',''
union all select 'DO','RC','MA','12','Cont fact.','AC','@contfactura','@dencontfactura','300','0','1','wACConturi','','','','Cont fact.','','',''
union all select 'DO','RC','MA','18','Contract','C','@contract','','300','0','0','','','','','Contract','','',''
union all select 'DO','RC','MA','5','Cont','AC','@contvenituri','@dencontvenituri','300','0','1','wACConturi','','','','Cont','','',''
union all select 'DO','RC','MA','2','Data','D','@data','','100','1','1','','','','','','','',''
union all select 'DO','RC','MA','25','Data expedierii','D','@dataexpedierii','','200','0','0','','','','','Data exp.','','',''
union all select 'DO','RC','MA','10','Data facturii','D','@datafacturii','','100','1','1','','','','','Data facturii','','',''
union all select 'DO','RC','MA','11','Data scadentei','D','@datascadentei','','100','1','1','','','','','Data scad.','','',''
union all select 'DO','RC','MA','11','Discount','N','@discount','','100','0','1','','','','','','','',''
union all select 'DO','RC','MA','22','Eliberat','C','@eliberat','','200','0','0','','','','','Eliberat','','',''
union all select 'DO','RC','MA','14','Explicatii','C','@explicatii','','300','0','1','','','','','Explicatii','','',''
union all select 'DO','RC','MA','6','Factura','C','@factura','','100','1','1',' ','','','','Factura','','',''
union all select 'DO','RC','MA','3','Gestiune','AC','@gestiune','@dengestiune','300','1','1','wACGestiuni','','','','Gestiune','','',''
union all select 'DO','RC','MA','9','Gest. prim.','AC','@gestprim','','300','0','0','wACGestiuniPrim','','','','Gest. prim.','','',''
union all select 'DO','RC','MA','5','Indicator bug.','AC','@indbug','@denbug','400','0','1','wACIndBug','','','','Indicator bugetar','','',''
union all select 'DO','RC','MA','4','Loc munca','AC','@lm','@denlm','200','1','1','wACLocm','','','','Loc munca','','',''
union all select 'DO','RC','MA','23','Mijl.transp.','C','@mijloctp','','200','0','0','','','','','Mijl.transp.','','',''
union all select 'DO','RC','MA','24','Nr. mijl.transp.','C','@nrmijloctp','','200','0','0','','','','','Nr.mijl.transp.','','',''
union all select 'DO','RC','MA','1','Numar','C','@numar','','100','1','1','','','','','','','',''
union all select 'DO','RC','MA','21','Nr. buletin','C','@numarbuletin','','150','0','0','','','','','Nr. buletin','','',''
union all select 'DO','RC','MA','19','Nume delegat','C','@numedelegat','','300','0','0','','','','','Nume delegat','','',''
union all select 'DO','RC','MA','27','Observatii','C','@observatii','','200','0','0','','','','','Observatii','','',''
union all select 'DO','RC','MA','26','Ora expedierii','C','@oraexpedierii','','100','0','0','','','','','Ora exp.','','',''
union all select 'DO','RC','MA','15','Pct. livrare','AC','@punctlivrare','@denpunctlivrare','200','0','1','wACPuncteLivrare','','','','Pct. livrare','','',''
union all select 'DO','RC','MA','28','Pct. livrare exped.','C','@punctlivrareexped','','200','0','0','','','','','Pct.livr.exped','','',''
union all select 'DO','RC','MA','20','Seria buletin','C','@seriabuletin','','100','0','0','','','','','Seria buletin','','',''
union all select 'DO','RC','MA','5','Client','AC','@tert','@dentert','300','0','1','wACTerti','','','','Tert','','',''
union all select 'DO','RC','MA','2','Tip','C','@tip','','30','0','0','','','','','','','',''
union all select 'DO','RC','MA','29','Tip TVA','CB','@tiptva','@tiptva','200','0','1','','0,1,2,3','0-Tva deductibil,1-TVA Compenst,2-TVA Nedeductibil,3-TVA Neded. cont intrare','','Tip TVA','','',''
union all select 'DO','RC','MA','17','Tva neex.','N','@tvaneexigibil','','200','0','0','','','','','Tva neex.','','',''
union all select 'DO','RC','MA','14','Val cu TVA','N','@valtotala',' ','100','0','0','','','','','Valoare cu TVA','','',''
union all select 'DO','RM','MA','16','Categ. pret','AC','@categpret','@dencatpret','200','0','1','wACCategPret','','','','Categ. pret','','',''
union all select 'DO','RM','MA','6','Comanda','AC','@comanda','@dencomanda','300','0','1','wACComenzi','','','','Comanda','','',''
union all select 'DO','RM','MA','15','Cont de stoc','AC','@cont_stoc','@dencontstoc','300','0','1','wACConturi','','','','Cont de stoc','','',''
union all select 'DO','RM','MA','12','Cont fact.','AC','@contfactura','@dencontfactura','300','1','1','wACConturi','','','','Cont fact.','','',''
union all select 'DO','RM','MA','18','Contract','C','@contract','','300','0','0','','','','','Contract','','',''
union all select 'DO','RM','MA','5','Cont','AC','@contvenituri','@dencontvenituri','300','0','1','wACConturi','','','','Cont','','',''
union all select 'DO','RM','MA','31','Curs','N','@curs','@curs','200','1','1','','','','','Curs valutare','','',''
union all select 'DO','RM','MA','2','Data','D','@data','','100','1','1','','','','','','','',''
union all select 'DO','RM','MA','25','Data expedierii','D','@dataexpedierii','','200','0','0','','','','','Data exp.','','',''
union all select 'DO','RM','MA','10','Data facturii','D','@datafacturii','','100','1','1','','','','','Data facturii','','',''
union all select 'DO','RM','MA','11','Data scadentei','D','@datascadentei','','100','1','1','','','','','Data scad.','','',''
union all select 'DO','RM','MA','11','Discount','N','@discount','','100','1','1','','','','','','','',''
union all select 'DO','RM','MA','22','Eliberat','C','@eliberat','','200','0','0','','','','','Eliberat','','',''
union all select 'DO','RM','MA','14','Explicatii','C','@explicatii','','300','1','1','','','','','Explicatii','','',''
union all select 'DO','RM','MA','6','Factura','C','@factura','','100','1','1',' ','','','','Factura','','',''
union all select 'DO','RM','MA','3','Gestiune','AC','@gestiune','@dengestiune','300','1','1','wACGestiuni','','','','Gestiune','','',''
union all select 'DO','RM','MA','9','Gest. prim.','AC','@gestprim','','300','0','0','wACGestiuniPrim','','','','Gest. prim.','','',''
union all select 'DO','RM','MA','5','Indicator bug.','AC','@indbug','@denbug','400','0','1','wACIndBug','','','','Indicator bugetar','','',''
union all select 'DO','RM','MA','4','Loc munca','AC','@lm','@denlm','200','1','1','wACLocm','','','','Loc munca','','',''
union all select 'DO','RM','MA','23','Mijl.transp.','C','@mijloctp','','200','0','0','','','','','Mijl.transp.','','',''
union all select 'DO','RM','MA','24','Nr. mijl.transp.','C','@nrmijloctp','','200','0','0','','','','','Nr.mijl.transp.','','',''
union all select 'DO','RM','MA','1','Numar','C','@numar','','100','1','1','','','','','','','',''
union all select 'DO','RM','MA','21','Nr. buletin','C','@numarbuletin','','150','0','0','','','','','Nr. buletin','','',''
union all select 'DO','RM','MA','19','Nume delegat','C','@numedelegat','','300','0','0','','','','','Nume delegat','','',''
union all select 'DO','RM','MA','27','Observatii','C','@observatii','','200','0','0','','','','','Observatii','','',''
union all select 'DO','RM','MA','26','Ora expedierii','C','@oraexpedierii','','100','0','0','','','','','Ora exp.','','',''
union all select 'DO','RM','MA','15','Pct. livrare','AC','@punctlivrare','@denpunctlivrare','200','0','1','wACPuncteLivrare','','','','Pct. livrare','','',''
union all select 'DO','RM','MA','28','Pct. livrare exped.','C','@punctlivrareexped','','200','0','0','','','','','Pct.livr.exped','','',''
union all select 'DO','RM','MA','20','Seria buletin','C','@seriabuletin','','100','0','0','','','','','Seria buletin','','',''
union all select 'DO','RM','MA','5','Furnizor','AC','@tert','@dentert','300','1','1','wACTerti','','','','Tert','','',''
union all select 'DO','RM','MA','2','Tip','C','@tip','','30','0','0','','','','','','','',''
union all select 'DO','RM','MA','29','Tip TVA','CB','@tiptva','@tiptva','200','1','0','','0,1,2,3','0-Tva deductibil,1-TVA Compenst,2-TVA Nedeductibil,3-TVA Neded. cont intrare','','Tip TVA','','',''
union all select 'DO','RM','MA','17','Tva neex.','N','@tvaneexigibil','','200','0','0','','','','','Tva neex.','','',''
union all select 'DO','RM','MA','14','Val cu TVA','N','@valtotala',' ','100','0','0','','','','','Valoare cu TVA','','',''
union all select 'DO','RM','MA','30','Valuta','AC','@valuta','@valuta','200','1','1','wACValuta','','','','Valuta','','',''
union all select 'DO','RS','MA','16','Categ. pret','AC','@categpret','@dencatpret','200','1','1','wACCategPret','','','','Categ. pret','','',''
union all select 'DO','RS','MA','6','Comanda','AC','@comanda','@dencomanda','300','0','1','wACComenzi','','','','Comanda','','',''
union all select 'DO','RS','MA','15','Cont de stoc','AC','@cont_stoc','@dencontstoc','300','1','1','wACConturi','','','','Cont de stoc','','',''
union all select 'DO','RS','MA','12','Cont fact.','AC','@contfactura','@dencontfactura','300','1','1','wACConturi','','','','Cont fact.','','',''
union all select 'DO','RS','MA','18','Contract','C','@contract','','300','0','0','','','','','Contract','','',''
union all select 'DO','RS','MA','5','Cont','AC','@contvenituri','@dencontvenituri','300','0','1','wACConturi','','','','Cont','','',''
union all select 'DO','RS','MA','2','Data','D','@data','','100','1','1','','','','','','','',''
union all select 'DO','RS','MA','25','Data expedierii','D','@dataexpedierii','','200','0','0','','','','','Data exp.','','',''
union all select 'DO','RS','MA','10','Data facturii','D','@datafacturii','','100','1','1','','','','','Data facturii','','',''
union all select 'DO','RS','MA','11','Data scadentei','D','@datascadentei','','100','1','1','','','','','Data scad.','','',''
union all select 'DO','RS','MA','11','Discount','N','@discount','','100','1','1','','','','','','','',''
union all select 'DO','RS','MA','22','Eliberat','C','@eliberat','','200','0','0','','','','','Eliberat','','',''
union all select 'DO','RS','MA','14','Explicatii','C','@explicatii','','300','1','1','','','','','Explicatii','','',''
union all select 'DO','RS','MA','6','Factura','C','@factura','','100','1','1',' ','','','','Factura','','',''
union all select 'DO','RS','MA','3','Gestiune','AC','@gestiune','@dengestiune','300','1','1','wACGestiuni','','','','Gestiune','','',''
union all select 'DO','RS','MA','9','Gest. prim.','AC','@gestprim','','300','0','0','wACGestiuniPrim','','','','Gest. prim.','','',''
union all select 'DO','RS','MA','5','Indicator bug.','AC','@indbug','@denbug','400','0','1','wACIndBug','','','','Indicator bugetar','','',''
union all select 'DO','RS','MA','4','Loc munca','AC','@lm','@denlm','200','1','1','wACLocm','','','','Loc munca','','',''
union all select 'DO','RS','MA','23','Mijl.transp.','C','@mijloctp','','200','0','0','','','','','Mijl.transp.','','',''
union all select 'DO','RS','MA','24','Nr. mijl.transp.','C','@nrmijloctp','','200','0','0','','','','','Nr.mijl.transp.','','',''
union all select 'DO','RS','MA','1','Numar','C','@numar','','100','1','1','','','','','','','',''
union all select 'DO','RS','MA','21','Nr. buletin','C','@numarbuletin','','150','0','0','','','','','Nr. buletin','','',''
union all select 'DO','RS','MA','19','Nume delegat','C','@numedelegat','','300','0','0','','','','','Nume delegat','','',''
union all select 'DO','RS','MA','27','Observatii','C','@observatii','','200','0','0','','','','','Observatii','','',''
union all select 'DO','RS','MA','26','Ora expedierii','C','@oraexpedierii','','100','0','0','','','','','Ora exp.','','',''
union all select 'DO','RS','MA','15','Pct. livrare','AC','@punctlivrare','@denpunctlivrare','200','1','1','wACPuncteLivrare','','','','Pct. livrare','','',''
union all select 'DO','RS','MA','28','Pct. livrare exped.','C','@punctlivrareexped','','200','0','0','','','','','Pct.livr.exped','','',''
union all select 'DO','RS','MA','20','Seria buletin','C','@seriabuletin','','100','0','0','','','','','Seria buletin','','',''
union all select 'DO','RS','MA','5','Client','AC','@tert','@dentert','300','1','1','wACTerti','','','','Tert','','',''
union all select 'DO','RS','MA','2','Tip','C','@tip','','30','1','0','','','','','','','',''
union all select 'DO','RS','MA','29','Tip TVA','CB','@tiptva','@tiptva','200','1','0','','0,1,2,3','0-Tva deductibil,1-TVA Compenst,2-TVA Nedeductibil,3-TVA Neded. cont intrare','','Tip TVA','','',''
union all select 'DO','RS','MA','17','Tva neex.','N','@tvaneexigibil','','200','0','0','','','','','Tva neex.','','',''
union all select 'DO','RS','MA','14','Val cu TVA','N','@valtotala',' ','100','1','0','','','','','Valoare cu TVA','','',''
union all select 'DO','TE','MA','16','Categ. pret','AC','@categpret','@dencatpret','200','1','1','wACCategPret','','','','Categ. pret','','',''
union all select 'DO','TE','MA','15','Cont de stoc','AC','@cont_stoc','@dencontstoc','300','1','1','wACConturi','','','','Cont de stoc','','',''
union all select 'DO','TE','MA','2','Data','D','@data','','100','1','1','','','','','','','',''
union all select 'DO','TE','MA','3','Gestiune','AC','@gestiune','@dengestiune','300','1','1','wACGestiuni','','','','Gestiune','','',''
union all select 'DO','TE','MA','4','Gestiune primitoare','AC','@gestprim','@dengestprim','300','1','1','wACGestiuniPrim','','','','Gestiune rpimitoare','','',''
union all select 'DO','TE','MA','4','Loc munca','AC','@lm','@denlm','200','1','1','wACLocm','','','','Loc munca','','',''
union all select 'DO','TE','MA','1','Numar','C','@numar','','100','1','1','','','','','','','',''
union all select 'DO','TE','MA','2','Tip','C','@tip','','30','1','0','','','','','','','',''