--insert into expval 
select 'SCD371','E',r.data_lunii,r.Loc_de_munca,'','','','',rul_prec=isnull(sum(round(convert(decimal(15,3),round((Rulaj_debit-Rulaj_credit),2)),2)),0)
	from rulaje 
	where valuta='' and cont=max(r.Cont) and Data>=rtrim(YEAR(r.Data_lunii))+'-01-01'
		and Data<rtrim(YEAR(r.Data_lunii))+'-'+rtrim(MONTH(r.Data_lunii))+'-01' and Loc_de_munca=r.Loc_de_munca) 
from (select c.data_lunii,cont,Loc_de_munca,
		sum(round(convert(decimal(15,3), round((rulaj_debit-Rulaj_credit),2)),2)) as rul_curent
	from rulaje r inner join CalStd c on c.Data=r.Data
	where valuta='' and cont like '371'
	group by c.data_lunii,cont,Loc_de_munca) r
where 1=1 and r.data_lunii between '01/01/2012' and '10/31/2012' group by r.data_lunii,r.Loc_de_munca                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               