--insert into expval 
select 'SCD371','E',rc.data_lunii,rc.Loc_de_munca,'','','','',sum(rc.rul_curent)+(select rul_prec=isnull(sum(round(convert(decimal(15,3),round((r.Rulaj_debit-r.Rulaj_credit),2)),2)),0)
	from rulaje r 
	where r.valuta='' and r.cont like '371' and r.Data>=rtrim(YEAR(rc.Data_lunii))+'-01-01'
		and r.Data<rtrim(YEAR(rc.Data_lunii))+'-'+rtrim(MONTH(rc.Data_lunii))+'-01' and r.Loc_de_munca=rc.Loc_de_munca) 
from (select c.data_lunii,r.Cont,r.Loc_de_munca,
		sum(round(convert(decimal(15,3), round((r.rulaj_debit-r.Rulaj_credit),2)), 2)) as rul_curent
	from rulaje r inner join CalStd c on c.Data=r.Data
	where r.valuta='' and r.cont like '371'
	group by c.data_lunii,r.Cont,r.Loc_de_munca) rc and rc.data_lunii between '01/01/2012' and '10/31/2012' group by rc.data_lunii,rc.Loc_de_munca                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    