--truncate table webConfigACRapoarte
--truncate table webConfigCataloage
--truncate table webConfigDetaliiOp
truncate table webConfigFiltre
--truncate table webConfigFiltreV2_0
truncate table webConfigForm
--truncate table webConfigFormMobile
--truncate table WebConfigFormulare
--truncate table webconfigformulare_meniu_unic
truncate table webConfigGrid
--truncate table webConfigGridDoc
--truncate table webConfigGridV2_0
truncate table webConfigMeniu
--truncate table webConfigMeniu_vechi
--truncate table webConfigMeniuUtiliz
--truncate table webConfigMeniuV2_0
--truncate table webConfigPozDoc
--truncate table webConfigRapoarte
truncate table webConfigTaburi
truncate table webConfigTipuri
--truncate table webConfigTipuriDoc
--truncate table webConfigTipuriV2_0