
--if exists (select 1 from webconfigmeniu where meniu='AD') begin raiserror('Acest meniu este configurat deja! Daca doriti, stergeti manual linia din webConfigMeniu',11,1) return end
delete from webconfigmeniu where tipMacheta='D' and meniu='AD'
delete from webconfigfiltre where meniu='AD' and (''='' or isnull(tip,'')='')
delete from webconfiggrid where meniu='AD' and (''='' or isnull(tip,'')='') and (''='' or isnull(subtip,'')='')
delete from webconfigtipuri where meniu='AD' and (''='' or isnull(tip,'')='') and (''='' or isnull(subtip,'')='')
delete from webconfigform where meniu='AD' and (''='' or isnull(tip,'')='') and (''='' or isnull(subtip,'')='')
delete from webConfigTaburi where MeniuSursa='AD' and (''='' or isnull(TipSursa,'')='')

insert into webconfigmeniu --(id,Nume,idParinte,Icoana,TipMacheta,Meniu,Modul)
				(Meniu, Nume, MeniuParinte, Icoana, TipMacheta, NrOrdine, Componenta, Semnatura, Detalii, vizibil)
select top 0 null,null,null,null,null,null,null,null,null,null
union all select 'AD','Compensari','DOCUMENTE','Compensari','D',14.00,'','','<row><vechi><row id="14" nume="Compensari" idparinte="1" icoana="Compensari" tipmacheta="D" meniu="AD" modul="1"/></vechi></row>',1

insert into webconfiggrid (Meniu, Tip, Subtip, InPozitii, NumeCol, DataField, TipObiect, Latime, Ordine, Vizibil, Modificabil, Formula) 
select top 0 null,null,null,null,null,null,null,null,null,null,null,null
union all select 'AD','C3','','1','Achit. fact.','@achitfact','N','150','21','0','0',''
union all select 'AD','C3','','1','Comanda','@comanda','C','150','27','0','0',''
union all select 'AD','C3','','1','Cont creditor','@contcred','C','150','11','1','0',''
union all select 'AD','C3','','1','Cont debitor','@contdeb','C','150','9','1','0',''
union all select 'AD','C3','','1','Cont dif.curs','@contdifcurs','C','150','22','0','0',''
union all select 'AD','C3','','1','Cota tva','@cotatva','N','50','14','1','0',''
union all select 'AD','C3','','1','Curs','@curs','N','50','17','0','0',''
union all select 'AD','C3','','0','Data','@data','D','100','3','1','0',''
union all select 'AD','C3','','1','Data','@data','D','100','3','0','0',''
union all select 'AD','C3','','1','Data facturii','@datafacturii','D','100','29','0','0',''
union all select 'AD','C3','','1','Data scadentei','@datascadentei','D','100','30','0','0',''
union all select 'AD','C3','','1','Den. comanda','@dencomanda','C','300','28','0','0',''
union all select 'AD','C3','','1','Den. cont creditor','@dencontcred','C','300','12','0','0',''
union all select 'AD','C3','','1','Den. cont debitor','@dencontdeb','C','300','10','0','0',''
union all select 'AD','C3','','1','Den. loc munca','@denlm','C','300','26','0','0',''
union all select 'AD','C3','','0','Den. tert','@dentert','C','300','5','1','0',''
union all select 'AD','C3','','1','Den. tert','@dentert','C','300','6','0','0',''
union all select 'AD','C3','','1','Dif. tva','@diftva','N','150','20','0','0',''
union all select 'AD','C3','','1','Explicatii','@explicatii','C','300','24','0','0',''
union all select 'AD','C3','','1','Factura dreapta','@facturadreapta','C','150','8','1','0',''
union all select 'AD','C3','','1','Factura stanga','@facturastinga','C','150','7','1','0',''
union all select 'AD','C3','','1','Jurnal','@jurnal','C','50','32','0','0',''
union all select 'AD','C3','','1','Loc munca','@lm','C','150','25','0','0',''
union all select 'AD','C3','','0','Numar','@numar','C','100','2','1','0',''
union all select 'AD','C3','','1','Numar','@numar','C','150','2','0','0',''
union all select 'AD','C3','','1','Nr. pozitie','@numarpozitie','N','50','31','0','0',''
union all select 'AD','C3','','0','Nr. pozitii','@numarpozitii','N','50','9','1','0',''
union all select 'AD','C3','','0','Stare','@stare','N','50','10','0','0',''
union all select 'AD','C3','','1','Subtip','@subtip','C','50','4','0','0',''
union all select 'AD','C3','','1','Suma','@suma','N','150','13','1','0',''
union all select 'AD','C3','','1','Suma dif.curs','@sumadifcurs','N','150','23','0','0',''
union all select 'AD','C3','','1','Suma tva','@sumatva','N','150','15','1','0',''
union all select 'AD','C3','','1','Suma valuta','@sumavaluta','N','150','18','0','0',''
union all select 'AD','C3','','0','Tert','@tert','C','150','4','0','0',''
union all select 'AD','C3','','1','Tert','@tert','C','150','5','0','0',''
union all select 'AD','C3','','1','Tert benef.','@tertbenef','C','150','19','0','0',''
union all select 'AD','C3','','0','Tip','@tip','C','50','1','0','0',''
union all select 'AD','C3','','1','Tip','@tip','C','50','1','0','0',''
union all select 'AD','C3','','0','Tva','@tva22','N','150','7','1','0',''
union all select 'AD','C3','','0','Valoare','@valoare','N','200','6','1','0',''
union all select 'AD','C3','','0','Valoare valuta','@valoarevaluta','N','150','8','0','0',''
union all select 'AD','C3','','1','Valuta','@valuta','C','50','16','0','0',''
union all select 'AD','C3','','0','Benenficiar','@dentertbenef','C','300','6','0','0',' '
union all select 'AD','CB','','1','Achit. fact.','@achitfact','N','150','21','0','0',''
union all select 'AD','CB','','1','Comanda','@comanda','C','150','27','0','0',''
union all select 'AD','CB','','1','Cont creditor','@contcred','C','150','11','1','0',''
union all select 'AD','CB','','1','Cont debitor','@contdeb','C','150','9','1','0',''
union all select 'AD','CB','','1','Cont dif.curs','@contdifcurs','C','150','22','0','0',''
union all select 'AD','CB','','1','Cota tva','@cotatva','N','50','14','0','0',''
union all select 'AD','CB','','1','Curs','@curs','N','50','17','0','0',''
union all select 'AD','CB','','0','Data','@data','D','100','3','1','0',''
union all select 'AD','CB','','1','Data','@data','D','100','3','0','0',''
union all select 'AD','CB','','1','Data facturii','@datafacturii','D','100','29','0','0',''
union all select 'AD','CB','','1','Data scadentei','@datascadentei','D','100','30','0','0',''
union all select 'AD','CB','','1','Den. comanda','@dencomanda','C','300','28','0','0',''
union all select 'AD','CB','','1','Den. cont creditor','@dencontcred','C','300','12','0','0',''
union all select 'AD','CB','','1','Den. cont debitor','@dencontdeb','C','300','10','0','0',''
union all select 'AD','CB','','1','Den. loc munca','@denlm','C','300','26','0','0',''
union all select 'AD','CB','','0','Den. tert','@dentert','C','300','5','1','0',''
union all select 'AD','CB','','1','Den. tert','@dentert','C','300','6','0','0',''
union all select 'AD','CB','','1','Dif. tva','@diftva','N','150','20','0','0',''
union all select 'AD','CB','','1','Explicatii','@explicatii','C','300','24','0','0',''
union all select 'AD','CB','','1','Factura','@facturadreapta','C','150','8','1','0',''
union all select 'AD','CB','','1','Avans','@facturastinga','C','150','7','1','0',''
union all select 'AD','CB','','1','Jurnal','@jurnal','C','50','32','0','0',''
union all select 'AD','CB','','1','Loc munca','@lm','C','150','25','0','0',''
union all select 'AD','CB','','0','Numar','@numar','C','100','2','1','0',''
union all select 'AD','CB','','1','Numar','@numar','C','150','2','0','0',''
union all select 'AD','CB','','1','Nr. pozitie','@numarpozitie','N','50','31','0','0',''
union all select 'AD','CB','','0','Nr. pozitii','@numarpozitii','N','50','9','1','0',''
union all select 'AD','CB','','0','Stare','@stare','N','50','10','0','0',''
union all select 'AD','CB','','1','Subtip','@subtip','C','50','4','0','0',''
union all select 'AD','CB','','1','Suma','@suma','N','150','13','1','0',''
union all select 'AD','CB','','1','Suma dif.curs','@sumadifcurs','N','150','23','0','0',''
union all select 'AD','CB','','1','Suma tva','@sumatva','N','150','15','0','0',''
union all select 'AD','CB','','1','Suma valuta','@sumavaluta','N','150','18','0','0',''
union all select 'AD','CB','','0','Tert','@tert','C','150','4','0','0',''
union all select 'AD','CB','','1','Tert','@tert','C','150','5','0','0',''
union all select 'AD','CB','','1','Tert benef.','@tertbenef','C','150','19','0','0',''
union all select 'AD','CB','','0','Tip','@tip','C','50','1','0','0',''
union all select 'AD','CB','','1','Tip','@tip','C','50','1','0','0',''
union all select 'AD','CB','','0','Tva','@tva22','N','150','7','1','0',''
union all select 'AD','CB','','0','Valoare','@valoare','N','200','6','1','0',''
union all select 'AD','CB','','0','Valoare valuta','@valoarevaluta','N','150','8','0','0',''
union all select 'AD','CB','','1','Valuta','@valuta','C','50','16','0','0',''
union all select 'AD','CF','','1','Achit. fact.','@achitfact','N','150','21','0','0',''
union all select 'AD','CF','','1','Comanda','@comanda','C','150','27','0','0',''
union all select 'AD','CF','','1','Cont creditor','@contcred','C','150','11','1','0',''
union all select 'AD','CF','','1','Cont debitor','@contdeb','C','150','9','1','0',''
union all select 'AD','CF','','1','Cont dif.curs','@contdifcurs','C','150','22','0','0',''
union all select 'AD','CF','','1','Cota tva','@cotatva','N','50','14','1','0',''
union all select 'AD','CF','','1','Curs','@curs','N','50','17','0','0',''
union all select 'AD','CF','','0','Data','@data','D','100','3','1','0',''
union all select 'AD','CF','','1','Data','@data','D','100','3','0','0',''
union all select 'AD','CF','','1','Data facturii','@datafacturii','D','100','29','0','0',''
union all select 'AD','CF','','1','Data scadentei','@datascadentei','D','100','30','0','0',''
union all select 'AD','CF','','1','Den. comanda','@dencomanda','C','300','28','0','0',''
union all select 'AD','CF','','1','Den. cont creditor','@dencontcred','C','300','12','0','0',''
union all select 'AD','CF','','1','Den. cont debitor','@dencontdeb','C','300','10','0','0',''
union all select 'AD','CF','','1','Den. loc munca','@denlm','C','300','26','0','0',''
union all select 'AD','CF','','0','Den. tert','@dentert','C','300','5','1','0',''
union all select 'AD','CF','','1','Den. tert','@dentert','C','300','6','0','0',''
union all select 'AD','CF','','1','Dif. tva','@diftva','N','150','20','0','0',''
union all select 'AD','CF','','1','Explicatii','@explicatii','C','300','24','0','0',''
union all select 'AD','CF','','1','Factura dreapta','@facturadreapta','C','150','8','1','0',''
union all select 'AD','CF','','1','Factura stanga','@facturastinga','C','150','7','1','0',''
union all select 'AD','CF','','1','Jurnal','@jurnal','C','50','32','0','0',''
union all select 'AD','CF','','1','Loc munca','@lm','C','150','25','0','0',''
union all select 'AD','CF','','0','Numar','@numar','C','100','2','1','0',''
union all select 'AD','CF','','1','Numar','@numar','C','150','2','0','0',''
union all select 'AD','CF','','1','Nr. pozitie','@numarpozitie','N','50','31','0','0',''
union all select 'AD','CF','','0','Nr. pozitii','@numarpozitii','N','50','9','1','0',''
union all select 'AD','CF','','0','Stare','@stare','N','50','10','0','0',''
union all select 'AD','CF','','1','Subtip','@subtip','C','50','4','0','0',''
union all select 'AD','CF','','1','Suma','@suma','N','150','13','1','0',''
union all select 'AD','CF','','1','Suma dif.curs','@sumadifcurs','N','150','23','0','0',''
union all select 'AD','CF','','1','Suma tva','@sumatva','N','150','15','1','0',''
union all select 'AD','CF','','1','Suma valuta','@sumavaluta','N','150','18','0','0',''
union all select 'AD','CF','','0','Tert','@tert','C','150','4','0','0',''
union all select 'AD','CF','','1','Tert','@tert','C','150','5','0','0',''
union all select 'AD','CF','','1','Tert benef.','@tertbenef','C','150','19','0','0',''
union all select 'AD','CF','','0','Tip','@tip','C','50','1','0','0',''
union all select 'AD','CF','','1','Tip','@tip','C','50','1','0','0',''
union all select 'AD','CF','','0','Tva','@tva22','N','150','7','1','0',''
union all select 'AD','CF','','0','Valoare','@valoare','N','200','6','1','0',''
union all select 'AD','CF','','0','Valoare valuta','@valoarevaluta','N','150','8','0','0',''
union all select 'AD','CF','','1','Valuta','@valuta','C','50','16','0','0',''
union all select 'AD','CO','','1','Achit. fact.','@achitfact','N','150','21','0','0',''
union all select 'AD','CO','','1','Comanda','@comanda','C','150','27','0','0',''
union all select 'AD','CO','','1','Cont creditor','@contcred','C','150','11','1','0',''
union all select 'AD','CO','','1','Cont debitor','@contdeb','C','150','9','1','0',''
union all select 'AD','CO','','1','Cont dif.curs','@contdifcurs','C','150','22','0','0',''
union all select 'AD','CO','','1','Cota tva','@cotatva','N','50','14','1','0',''
union all select 'AD','CO','','1','Curs','@curs','N','50','17','0','0',''
union all select 'AD','CO','','0','Data','@data','D','100','3','1','0',''
union all select 'AD','CO','','1','Data','@data','D','100','3','0','0',''
union all select 'AD','CO','','1','Data facturii','@datafacturii','D','100','29','0','0',''
union all select 'AD','CO','','1','Data scadentei','@datascadentei','D','100','30','0','0',''
union all select 'AD','CO','','1','Den. comanda','@dencomanda','C','300','28','0','0',''
union all select 'AD','CO','','1','Den. cont creditor','@dencontcred','C','300','12','0','0',''
union all select 'AD','CO','','1','Den. cont debitor','@dencontdeb','C','300','10','0','0',''
union all select 'AD','CO','','1','Den. loc munca','@denlm','C','300','26','0','0',''
union all select 'AD','CO','','0','Den. tert','@dentert','C','300','5','1','0',''
union all select 'AD','CO','','1','Den. tert','@dentert','C','300','6','0','0',''
union all select 'AD','CO','','1','Dif. tva','@diftva','N','150','20','0','0',''
union all select 'AD','CO','','1','Explicatii','@explicatii','C','300','24','0','0',''
union all select 'AD','CO','','1','Factura dreapta','@facturadreapta','C','150','8','1','0',''
union all select 'AD','CO','','1','Factura stanga','@facturastinga','C','150','7','1','0',''
union all select 'AD','CO','','1','Jurnal','@jurnal','C','50','32','0','0',''
union all select 'AD','CO','','1','Loc munca','@lm','C','150','25','0','0',''
union all select 'AD','CO','','0','Numar','@numar','C','100','2','1','0',''
union all select 'AD','CO','','1','Numar','@numar','C','150','2','0','0',''
union all select 'AD','CO','','1','Nr. pozitie','@numarpozitie','N','50','31','0','0',''
union all select 'AD','CO','','0','Nr. pozitii','@numarpozitii','N','50','9','1','0',''
union all select 'AD','CO','','0','Stare','@stare','N','50','10','0','0',''
union all select 'AD','CO','','1','Subtip','@subtip','C','50','4','0','0',''
union all select 'AD','CO','','1','Suma','@suma','N','150','13','1','0',''
union all select 'AD','CO','','1','Suma dif.curs','@sumadifcurs','N','150','23','0','0',''
union all select 'AD','CO','','1','Suma tva','@sumatva','N','150','15','1','0',''
union all select 'AD','CO','','1','Suma valuta','@sumavaluta','N','150','18','0','0',''
union all select 'AD','CO','','0','Tert','@tert','C','150','4','0','0',''
union all select 'AD','CO','','1','Tert','@tert','C','150','5','0','0',''
union all select 'AD','CO','','1','Tert benef.','@tertbenef','C','150','19','0','0',''
union all select 'AD','CO','','0','Tip','@tip','C','50','1','0','0',''
union all select 'AD','CO','','1','Tip','@tip','C','50','1','0','0',''
union all select 'AD','CO','','0','Tva','@tva22','N','150','7','1','0',''
union all select 'AD','CO','','0','Valoare','@valoare','N','200','6','1','0',''
union all select 'AD','CO','','0','Valoare valuta','@valoarevaluta','N','150','8','0','0',''
union all select 'AD','CO','','1','Valuta','@valuta','C','50','16','0','0',''
union all select 'AD','FB','','1','Achit. fact.','@achitfact','N','150','21','0','0',''
union all select 'AD','FB','','1','Comanda','@comanda','C','150','27','0','0',''
union all select 'AD','FB','','1','Cont creditor','@contcred','C','150','11','1','0',''
union all select 'AD','FB','','1','Cont debitor','@contdeb','C','150','9','1','0',''
union all select 'AD','FB','','1','Cont dif.curs','@contdifcurs','C','150','22','0','0',''
union all select 'AD','FB','','1','Cota tva','@cotatva','N','50','14','1','0',''
union all select 'AD','FB','','1','Curs','@curs','N','50','17','0','0',''
union all select 'AD','FB','','0','Data','@data','D','100','3','1','0',''
union all select 'AD','FB','','1','Data','@data','D','100','3','0','0',''
union all select 'AD','FB','','1','Data facturii','@datafacturii','D','100','29','0','0',''
union all select 'AD','FB','','1','Data scadentei','@datascadentei','D','100','30','0','0',''
union all select 'AD','FB','','1','Den. comanda','@dencomanda','C','300','28','0','0',''
union all select 'AD','FB','','1','Den. cont creditor','@dencontcred','C','300','12','0','0',''
union all select 'AD','FB','','1','Den. cont debitor','@dencontdeb','C','300','10','0','0',''
union all select 'AD','FB','','1','Den. loc munca','@denlm','C','300','26','0','0',''
union all select 'AD','FB','','0','Den. tert','@dentert','C','300','5','1','0',''
union all select 'AD','FB','','1','Den. tert','@dentert','C','300','6','0','0',''
union all select 'AD','FB','','1','Dif. tva','@diftva','N','150','20','0','0',''
union all select 'AD','FB','','1','Explicatii','@explicatii','C','300','24','0','0',''
union all select 'AD','FB','','1','Factura dreapta','@facturadreapta','C','150','8','0','0',''
union all select 'AD','FB','','1','Factura stanga','@facturastinga','C','150','7','1','0',''
union all select 'AD','FB','','1','Jurnal','@jurnal','C','50','32','0','0',''
union all select 'AD','FB','','1','Loc munca','@lm','C','150','25','0','0',''
union all select 'AD','FB','','0','Numar','@numar','C','100','2','1','0',''
union all select 'AD','FB','','1','Numar','@numar','C','150','2','0','0',''
union all select 'AD','FB','','1','Nr. pozitie','@numarpozitie','N','50','31','0','0',''
union all select 'AD','FB','','0','Nr. pozitii','@numarpozitii','N','50','9','1','0',''
union all select 'AD','FB','','0','Stare','@stare','N','50','10','0','0',''
union all select 'AD','FB','','1','Subtip','@subtip','C','50','4','0','0',''
union all select 'AD','FB','','1','Suma','@suma','N','150','13','1','0',''
union all select 'AD','FB','','1','Suma dif.curs','@sumadifcurs','N','150','23','0','0',''
union all select 'AD','FB','','1','Suma tva','@sumatva','N','150','15','1','0',''
union all select 'AD','FB','','1','Suma valuta','@sumavaluta','N','150','18','0','0',''
union all select 'AD','FB','','0','Tert','@tert','C','150','4','0','0',''
union all select 'AD','FB','','1','Tert','@tert','C','150','5','0','0',''
union all select 'AD','FB','','1','Tert benef.','@tertbenef','C','150','19','0','0',''
union all select 'AD','FB','','0','Tip','@tip','C','50','1','0','0',''
union all select 'AD','FB','','1','Tip','@tip','C','50','1','0','0',''
union all select 'AD','FB','','0','Tva','@tva22','N','150','7','1','0',''
union all select 'AD','FB','','0','Valoare','@valoare','N','200','6','1','0',''
union all select 'AD','FB','','0','Valoare valuta','@valoarevaluta','N','150','8','0','0',''
union all select 'AD','FB','','1','Valuta','@valuta','C','50','16','0','0',''
union all select 'AD','FF','','1','Achit. fact.','@achitfact','N','150','21','0','0',''
union all select 'AD','FF','','1','Comanda','@comanda','C','150','27','0','0',''
union all select 'AD','FF','','1','Cont creditor','@contcred','C','150','11','1','0',''
union all select 'AD','FF','','1','Cont debitor','@contdeb','C','150','9','1','0',''
union all select 'AD','FF','','1','Cont dif.curs','@contdifcurs','C','150','22','0','0',''
union all select 'AD','FF','','1','Cota tva','@cotatva','N','50','14','1','0',''
union all select 'AD','FF','','1','Curs','@curs','N','50','17','0','0',''
union all select 'AD','FF','','0','Data','@data','D','100','3','1','0',''
union all select 'AD','FF','','1','Data','@data','D','100','3','0','0',''
union all select 'AD','FF','','1','Data facturii','@datafacturii','D','100','29','0','0',''
union all select 'AD','FF','','1','Data scadentei','@datascadentei','D','100','30','0','0',''
union all select 'AD','FF','','1','Den. comanda','@dencomanda','C','300','28','0','0',''
union all select 'AD','FF','','1','Den. cont creditor','@dencontcred','C','300','12','0','0',''
union all select 'AD','FF','','1','Den. cont debitor','@dencontdeb','C','300','10','0','0',''
union all select 'AD','FF','','1','Den. loc munca','@denlm','C','300','26','0','0',''
union all select 'AD','FF','','0','Den. tert','@dentert','C','300','5','1','0',''
union all select 'AD','FF','','1','Den. tert','@dentert','C','300','6','0','0',''
union all select 'AD','FF','','1','Dif. tva','@diftva','N','150','20','0','0',''
union all select 'AD','FF','','1','Explicatii','@explicatii','C','300','24','0','0',''
union all select 'AD','FF','','1','Factura dreapta','@facturadreapta','C','150','8','1','0',''
union all select 'AD','FF','','1','Factura stanga','@facturastinga','C','150','7','0','0',''
union all select 'AD','FF','','1','Jurnal','@jurnal','C','50','32','0','0',''
union all select 'AD','FF','','1','Loc munca','@lm','C','150','25','0','0',''
union all select 'AD','FF','','0','Numar','@numar','C','100','2','1','0',''
union all select 'AD','FF','','1','Numar','@numar','C','150','2','0','0',''
union all select 'AD','FF','','1','Nr. pozitie','@numarpozitie','N','50','31','0','0',''
union all select 'AD','FF','','0','Nr. pozitii','@numarpozitii','N','50','9','1','0',''
union all select 'AD','FF','','0','Stare','@stare','N','50','10','0','0',''
union all select 'AD','FF','','1','Subtip','@subtip','C','50','4','0','0',''
union all select 'AD','FF','','1','Suma','@suma','N','150','13','1','0',''
union all select 'AD','FF','','1','Suma dif.curs','@sumadifcurs','N','150','23','0','0',''
union all select 'AD','FF','','1','Suma tva','@sumatva','N','150','15','1','0',''
union all select 'AD','FF','','1','Suma valuta','@sumavaluta','N','150','18','0','0',''
union all select 'AD','FF','','0','Tert','@tert','C','150','4','0','0',''
union all select 'AD','FF','','1','Tert','@tert','C','150','5','0','0',''
union all select 'AD','FF','','1','Tert benef.','@tertbenef','C','150','19','0','0',''
union all select 'AD','FF','','0','Tip','@tip','C','50','1','0','0',''
union all select 'AD','FF','','1','Tip','@tip','C','50','1','0','0',''
union all select 'AD','FF','','0','Tva','@tva22','N','150','7','1','0',''
union all select 'AD','FF','','0','Valoare','@valoare','N','200','6','1','0',''
union all select 'AD','FF','','0','Valoare valuta','@valoarevaluta','N','150','8','0','0',''
union all select 'AD','FF','','1','Valuta','@valuta','C','50','16','0','0',''
union all select 'AD','IF','','1','Achit. fact.','@achitfact','N','150','21','0','0',''
union all select 'AD','IF','','1','Comanda','@comanda','C','150','27','0','0',''
union all select 'AD','IF','','1','Cont creditor','@contcred','C','150','11','1','0',''
union all select 'AD','IF','','1','Cont debitor','@contdeb','C','150','9','1','0',''
union all select 'AD','IF','','1','Cont dif.curs','@contdifcurs','C','150','22','0','0',''
union all select 'AD','IF','','1','Cota tva','@cotatva','N','50','14','1','0',''
union all select 'AD','IF','','1','Curs','@curs','N','50','17','0','0',''
union all select 'AD','IF','','0','Data','@data','D','100','4','1','0',''
union all select 'AD','IF','','1','Data','@data','D','100','3','0','0',''
union all select 'AD','IF','','1','Data facturii','@datafacturii','D','100','29','0','0',''
union all select 'AD','IF','','1','Data scadentei','@datascadentei','D','100','30','0','0',''
union all select 'AD','IF','','1','Den. comanda','@dencomanda','C','300','28','0','0',''
union all select 'AD','IF','','1','Den. cont creditor','@dencontcred','C','300','12','0','0',''
union all select 'AD','IF','','1','Den. cont debitor','@dencontdeb','C','300','10','0','0',''
union all select 'AD','IF','','1','Den. loc munca','@denlm','C','300','26','0','0',''
union all select 'AD','IF','','0','Den. tert','@dentert','C','300','5','1','0',''
union all select 'AD','IF','','1','Den. tert','@dentert','C','300','6','0','0',''
union all select 'AD','IF','','1','Dif. tva','@diftva','N','150','20','0','0',''
union all select 'AD','IF','','1','Explicatii','@explicatii','C','300','24','0','0',''
union all select 'AD','IF','','0','Factura','@factura','C','100','3','1','0',''
union all select 'AD','IF','','1','Factura dreapta','@facturadreapta','C','150','8','1','0',''
union all select 'AD','IF','','1','Factura stanga','@facturastinga','C','150','7','1','0',''
union all select 'AD','IF','','1','Jurnal','@jurnal','C','50','32','0','0',''
union all select 'AD','IF','','1','Loc munca','@lm','C','150','25','0','0',''
union all select 'AD','IF','','0','Numar','@numar','C','100','2','1','0',''
union all select 'AD','IF','','1','Numar','@numar','C','150','2','0','0',''
union all select 'AD','IF','','1','Nr. pozitie','@numarpozitie','N','50','31','0','0',''
union all select 'AD','IF','','0','Nr. pozitii','@numarpozitii','N','50','9','1','0',''
union all select 'AD','IF','','0','Stare','@stare','N','50','10','0','0',''
union all select 'AD','IF','','1','Subtip','@subtip','C','50','4','0','0',''
union all select 'AD','IF','','1','Val f Tva','@suma','N','150','13','1','0',''
union all select 'AD','IF','','1','Suma dif.curs','@sumadifcurs','N','150','23','0','0',''
union all select 'AD','IF','','1','Val tva','@sumatva','N','150','15','1','0',''
union all select 'AD','IF','','1','Suma valuta','@sumavaluta','N','150','18','0','0',''
union all select 'AD','IF','','0','Tert','@tert','C','150','5','0','0',''
union all select 'AD','IF','','1','Tert','@tert','C','150','5','0','0',''
union all select 'AD','IF','','1','Tert benef.','@tertbenef','C','150','19','0','0',''
union all select 'AD','IF','','0','Tip','@tip','C','50','1','0','0',''
union all select 'AD','IF','','1','Tip','@tip','C','50','1','0','0',''
union all select 'AD','IF','','0','Tva','@tva22','N','150','7','1','0',''
union all select 'AD','IF','','0','Valoare f Tva','@valoare','N','200','6','1','0',''
union all select 'AD','IF','','0','Valoare valuta','@valoarevaluta','N','150','8','0','0',''
union all select 'AD','IF','','1','Valuta','@valuta','C','50','16','0','0',''
union all select 'AD','SF','','1','Achit. fact.','@achitfact','N','150','21','0','0',''
union all select 'AD','SF','','1','Comanda','@comanda','C','150','27','0','0',''
union all select 'AD','SF','','1','Cont creditor','@contcred','C','150','11','1','0',''
union all select 'AD','SF','','1','Cont debitor','@contdeb','C','150','9','1','0',''
union all select 'AD','SF','','1','Cont dif.curs','@contdifcurs','C','150','22','0','0',''
union all select 'AD','SF','','1','Cota tva','@cotatva','N','50','14','1','0',''
union all select 'AD','SF','','1','Curs','@curs','N','50','17','0','0',''
union all select 'AD','SF','','0','Data','@data','D','100','3','1','0',''
union all select 'AD','SF','','1','Data','@data','D','100','3','0','0',''
union all select 'AD','SF','','1','Data facturii','@datafacturii','D','100','29','0','0',''
union all select 'AD','SF','','1','Data scadentei','@datascadentei','D','100','30','0','0',''
union all select 'AD','SF','','1','Den. comanda','@dencomanda','C','300','28','0','0',''
union all select 'AD','SF','','1','Den. cont creditor','@dencontcred','C','300','12','0','0',''
union all select 'AD','SF','','1','Den. cont debitor','@dencontdeb','C','300','10','0','0',''
union all select 'AD','SF','','1','Den. loc munca','@denlm','C','300','26','0','0',''
union all select 'AD','SF','','0','Den. tert','@dentert','C','300','5','1','0',''
union all select 'AD','SF','','1','Den. tert','@dentert','C','300','6','0','0',''
union all select 'AD','SF','','1','Dif. tva','@diftva','N','150','20','0','0',''
union all select 'AD','SF','','1','Explicatii','@explicatii','C','300','24','0','0',''
union all select 'AD','SF','','1','Factura dreapta','@facturadreapta','C','150','8','1','0',''
union all select 'AD','SF','','1','Factura stanga','@facturastinga','C','150','7','1','0',''
union all select 'AD','SF','','1','Jurnal','@jurnal','C','50','32','0','0',''
union all select 'AD','SF','','1','Loc munca','@lm','C','150','25','0','0',''
union all select 'AD','SF','','0','Numar','@numar','C','100','2','1','0',''
union all select 'AD','SF','','1','Numar','@numar','C','150','2','0','0',''
union all select 'AD','SF','','1','Nr. pozitie','@numarpozitie','N','50','31','0','0',''
union all select 'AD','SF','','0','Nr. pozitii','@numarpozitii','N','50','9','1','0',''
union all select 'AD','SF','','0','Stare','@stare','N','50','10','0','0',''
union all select 'AD','SF','','1','Subtip','@subtip','C','50','4','0','0',''
union all select 'AD','SF','','1','Suma','@suma','N','150','13','1','0',''
union all select 'AD','SF','','1','Suma dif.curs','@sumadifcurs','N','150','23','0','0',''
union all select 'AD','SF','','1','Suma tva','@sumatva','N','150','15','1','0',''
union all select 'AD','SF','','1','Suma valuta','@sumavaluta','N','150','18','0','0',''
union all select 'AD','SF','','0','Tert','@tert','C','150','4','0','0',''
union all select 'AD','SF','','1','Tert','@tert','C','150','5','0','0',''
union all select 'AD','SF','','1','Tert benef.','@tertbenef','C','150','19','0','0',''
union all select 'AD','SF','','0','Tip','@tip','C','50','1','0','0',''
union all select 'AD','SF','','1','Tip','@tip','C','50','1','0','0',''
union all select 'AD','SF','','0','Tva','@tva22','N','150','7','1','0',''
union all select 'AD','SF','','0','Valoare','@valoare','N','200','6','1','0',''
union all select 'AD','SF','','0','Valoare valuta','@valoarevaluta','N','150','8','0','0',''
union all select 'AD','SF','','1','Valuta','@valuta','C','50','16','0','0',''

insert into webconfigFiltre (Meniu, Tip, Ordine, Vizibil, TipObiect, Descriere, Prompt1, DataField1, Interval, Prompt2, DataField2) 
select top 0 null,null,null,null,null,null,null,null,null,null,null
union all select 'AD','C3','5','1','','Den. tert','Denumire tert','@f_dentert','0','',''
union all select 'AD','C3','1','1','','Numar','Numar','@f_numar','0','',''
union all select 'AD','C3','4','1','','Tert','Tert','@f_tert','0','',''
union all select 'AD','C3','6','0','','Valoare','de la','@f_valoarejos','1','pana la','@f_valoaresus'
union all select 'AD','CB','5','1','','Den. tert','Denumire tert','@f_dentert','0','',''
union all select 'AD','CB','1','1','','Numar','Numar','@f_numar','0','',''
union all select 'AD','CB','4','1','','Tert','Tert','@f_tert','0','',''
union all select 'AD','CB','6','0','','Valoare','de la','@f_valoarejos','1','pana la','@f_valoaresus'
union all select 'AD','CF','5','1','','Den. tert','Denumire tert','@f_dentert','0','',''
union all select 'AD','CF','1','1','','Numar','Numar','@f_numar','0','',''
union all select 'AD','CF','4','1','','Tert','Tert','@f_tert','0','',''
union all select 'AD','CF','6','0','','Valoare','de la','@f_valoarejos','1','pana la','@f_valoaresus'
union all select 'AD','CO','5','1','','Den. tert','Denumire tert','@f_dentert','0','',''
union all select 'AD','CO','1','1','','Numar','Numar','@f_numar','0','',''
union all select 'AD','CO','4','1','','Tert','Tert','@f_tert','0','',''
union all select 'AD','CO','6','0','','Valoare','de la','@f_valoarejos','1','pana la','@f_valoaresus'
union all select 'AD','FB','5','1','','Den. tert','Denumire tert','@f_dentert','0','',''
union all select 'AD','FB','1','1','','Numar','Numar','@f_numar','0','',''
union all select 'AD','FB','4','1','','Tert','Tert','@f_tert','0','',''
union all select 'AD','FB','6','0','','Valoare','de la','@f_valoarejos','1','pana la','@f_valoaresus'
union all select 'AD','FF','5','1','','Den. tert','Denumire tert','@f_dentert','0','',''
union all select 'AD','FF','1','1','','Numar','Numar','@f_numar','0','',''
union all select 'AD','FF','4','1','','Tert','Tert','@f_tert','0','',''
union all select 'AD','FF','6','0','','Valoare','de la','@f_valoarejos','1','pana la','@f_valoaresus'
union all select 'AD','IF','5','1','','Den. tert','Denumire tert','@f_dentert','0','',''
union all select 'AD','IF','1','1','','Numar','Numar','@f_numar','0','',''
union all select 'AD','IF','4','1','','Tert','Tert','@f_tert','0','',''
union all select 'AD','IF','6','0','','Valoare','de la','@f_valoarejos','1','pana la','@f_valoaresus'
union all select 'AD','IF','2','1','','Factura','Factura','@facturastinga','0','',''
union all select 'AD','SF','5','1','','Den. tert','Denumire tert','@f_dentert','0','',''
union all select 'AD','SF','1','1','','Numar','Numar','@f_numar','0','',''
union all select 'AD','SF','4','1','','Tert','Tert','@f_tert','0','',''
union all select 'AD','SF','6','0','','Valoare','de la','@f_valoarejos','1','pana la','@f_valoaresus'

insert into webconfigTipuri (Meniu, Tip, Subtip, Ordine, Nume, Descriere, TextAdaugare, TextModificare, ProcDate, ProcScriere, ProcStergere, ProcDatePoz, ProcScrierePoz, ProcStergerePoz, Vizibil, Fel, procPopulare,tasta) 
select top 0 null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
union all select 'AD','C3','','2','Compensari in 3','','','','wIaAdoc','','','wIaPozadoc','wScriuPozadoc','wStergPozadoc','0','','',''
union all select 'AD','C3','C3','1','Compensari in 3','','','','','','',' ',' ',' ','0','','',''
union all select 'AD','C3','OP','2','Operatie','','','','wOperatieC3','','','','','','0','','',''
union all select 'AD','CF','','3','Compensari furnizori','','','','wIaAdoc','','','wIaPozadoc','wScriuPozadoc','wStergPozadoc','0','','',''
union all select 'AD','CF','CF','1','Compensare furn.','','','','','','',' ',' ',' ','0','','',''
union all select 'AD','CO','','1','Compensari','','','','wIaAdoc','','wStergAdoc','wIaPozadoc','wScriuPozadoc','wStergPozadoc','0','','',''
union all select 'AD','CO','CO','1','Compensare','','','','','','',' ',' ',' ','0','','',''
union all select 'AD','FB','','8','Facturi benef.','','','','wIaAdoc','','','wIaPozadoc','wScriuPozadoc','wStergPozadoc','0','','',''
union all select 'AD','FB','FB','1','Factura benef.','','','','','','',' ',' ',' ','0','','',''
union all select 'AD','FF','','7','Facturi furnizori','','','','wIaAdoc','','','wIaPozadoc','wScriuPozadoc','wStergPozadoc','0','','',''
union all select 'AD','FF','FF','1','Factura furnizor','','','',' ','','',' ',' ',' ','0','','',''
union all select 'AD','IF','','2','Intocmire fact.benef','','','','wIaAdoc','','','wIaPozadoc','wScriuPozadoc','wStergPozadoc','1','','',''
union all select 'AD','IF','IF','1','Intocmire fact.benef','','','','','','',' ',' ',' ','1','','',''
union all select 'AD','SF','','5','Sosire fact. furn.','','','','wIaAdoc','','','wIaPozadoc','wScriuPozadoc','wStergPozadoc','0','','',''
union all select 'AD','SF','SF','1','Sosire fact. furn.','','','','','','',' ',' ',' ','0','','',''
union all select 'AD','CB','','4','Compensari benef.','','','','wIaAdoc','','wStergAdoc','wIaPozadoc','wScriuPozadoc','wStergPozadoc','1','','',''
union all select 'AD','CB','CB','1','Compensare benef.','','','','','','',' ',' ',' ','1','','',''
union all select 'AD','CO','MA','2','Modificare antet','          Operatie de modificare antet alte documente.','','','','wOPModificareAntetADoc','','','','','0','O','wOPModificareAntetADoc_p',''
union all select 'AD','C3','RN','80','Refacere inreg. cont','Operatie pentru refacere inregistrari contabile','','','','wOPRefacereInregistrariContabileDocument','','','','','0','O','wOPRefacereInregistrariContabile_p',''
union all select 'AD','CB','RN','80','Refacere inreg. cont','Operatie pentru refacere inregistrari contabile','','','','wOPRefacereInregistrariContabileDocument','','','','','1','O','wOPRefacereInregistrariContabile_p',''
union all select 'AD','CF','RN','80','Refacere inreg. cont','Operatie pentru refacere inregistrari contabile','','','','wOPRefacereInregistrariContabileDocument','','','','','0','O','wOPRefacereInregistrariContabile_p',''
union all select 'AD','CO','RN','80','Refacere inreg. cont','Operatie pentru refacere inregistrari contabile','','','','wOPRefacereInregistrariContabileDocument','','','','','0','O','wOPRefacereInregistrariContabile_p',''
union all select 'AD','FB','RN','80','Refacere inreg. cont','Operatie pentru refacere inregistrari contabile','','','','wOPRefacereInregistrariContabileDocument','','','','','0','O','wOPRefacereInregistrariContabile_p',''
union all select 'AD','FF','RN','80','Refacere inreg. cont','Operatie pentru refacere inregistrari contabile','','','','wOPRefacereInregistrariContabileDocument','','','','','0','O','wOPRefacereInregistrariContabile_p',''
union all select 'AD','IF','RN','80','Refacere inreg. cont','Operatie pentru refacere inregistrari contabile','','','','wOPRefacereInregistrariContabileDocument','','','','','0','O','wOPRefacereInregistrariContabile_p',''
union all select 'AD','SF','RN','80','Refacere inreg. cont','Operatie pentru refacere inregistrari contabile','','','','wOPRefacereInregistrariContabileDocument','','','','','0','O','wOPRefacereInregistrariContabile_p',''

insert into webconfigForm (Meniu, Tip, Subtip, Ordine, Nume, TipObiect, DataField, LabelField, Latime, Vizibil, Modificabil, ProcSQL, ListaValori, ListaEtichete, Initializare, Prompt, Procesare, Tooltip, formula)
select top 0 null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
union all select 'AD','C3','','2','Data','D','@data','','100','1','1','','','','','Data','','',''
union all select 'AD','C3','','4','Factura','AC','@factura','@factura','300','0','1','wACFacturi','','','','Factura','','',''
union all select 'AD','C3','','1','Numar','C','@numar','','100','1','1','','','','','Numar','','',''
union all select 'AD','C3','','3','Tert','AC','@tert','@dentert','300','1','1','wACTerti','','','','Tert','','',''
union all select 'AD','C3','','5','Total','N','@valoarecutva','','100','0','0','','','','','','','',''
union all select 'AD','C3','','5','Beneficiar','AC','@tertbenef','@dentertbenef','300','0','1','wACTerti','','','','Beneficiar','','',''
union all select 'AD','C3','C3','15','Comanda','C','@comanda','','80','0','1','','','','','Comanda','','',''
union all select 'AD','C3','C3','6','Cont creditor','AC','@contcred','@contcred','250','1','1','wACConturi','','','','Cont creditor','','',''
union all select 'AD','C3','C3','5','Cont debitor','C','@contdeb','@contdeb','250','1','1','wACConturi','','','','Cont debitor','','',''
union all select 'AD','C3','C3','11','Cota tva','N','@cotatva','','40','1','1','','','','','Cota tva','','',''
union all select 'AD','C3','C3','9','Curs','N','@curs','','60','0','1','','','','','Curs','','',''
union all select 'AD','C3','C3','18','Data facturii','D','@datafacturii','','80','0','1','','','','','Data facturii','','',''
union all select 'AD','C3','C3','19','Data scadentei','D','@datascadentei','','80','0','1','','','','','Data scadentei','','',''
union all select 'AD','C3','C3','13','Explicatii','C','@explicatii','','200','0','1','','','','','Explicatii','','',''
union all select 'AD','C3','C3','4','Factura dreapta','C','@facturadreapta','','80','1','1','','','','','Factura dreapta','','',''
union all select 'AD','C3','C3','3','Factura stanga','C','@facturastinga','','80','1','1',' ','','','','Factura stanga','','',''
union all select 'AD','C3','C3','17','Jurnal','C','@jurnal','','80','0','1','','','','','Jurnal','','',''
union all select 'AD','C3','C3','14','Loc munca','C','@lm','','80','0','1','','','','','Loc munca','','',''
union all select 'AD','C3','C3','16','Nr. pozitie','C','@numarpozitie','','60','0','1','','','','','Nr. pozitite','','',''
union all select 'AD','C3','C3','1','Tip','C','@subtip','','40','0','1','','','','','Tip','','',''
union all select 'AD','C3','C3','7','Suma','N','@suma','','80','1','1','','','','','Suma','','',''
union all select 'AD','C3','C3','12','Suma tva','N','@sumatva','','80','0','1','','','','','Suma tva','','',''
union all select 'AD','C3','C3','10','Suma valuta','N','@sumavaluta','','80','0','1','','','','','Suma valuta','','',''
union all select 'AD','C3','C3','2','Tert beneficiar','AC','@tertbenef','@tertbenef','300','1','1','wACTerti','','','','Tert','','',''
union all select 'AD','C3','C3','8','Valuta','C','@valuta','','40','0','1','','','','','Valuta','','',''
union all select 'AD','C3','RN','3','Data','D','@data','','100','0','0','','','','','','','',''
union all select 'AD','C3','RN','2','Numar','C','@numar','','100','0','0','','','','','','','',''
union all select 'AD','C3','RN','1','Tip','C','@tip','','50','0','0','','','','','','','',''
union all select 'AD','CB','','2','Data','D','@data','','100','1','1','','','','','Data','','',''
union all select 'AD','CB','','4','Factura','AC','@factura','@factura','300','0','1','wACFacturi','','','','Factura','','',''
union all select 'AD','CB','','1','Numar','C','@numar','','100','1','1','','','','','Numar','','',''
union all select 'AD','CB','','3','Tert','AC','@tert','@dentert','300','1','1','wACTerti','','','','Tert','','',''
union all select 'AD','CB','','5','Total','N','@valoarecutva','','100','1','0','','','','','','','',''
union all select 'AD','CB','CB','22','Achit.fact.in valuta','N','@achitfact','','80','0','1','','','','','','','',''
union all select 'AD','CB','CB','15','Comanda','C','@comanda','','80','0','1','','','','','Comanda','','',''
union all select 'AD','CB','CB','6','Cont creditor','AC','@contcred','@contcred','250','0','1','wACConturi','','','','Cont creditor','','',''
union all select 'AD','CB','CB','5','Cont debitor','C','@contdeb','@contdeb','250','0','1','wACConturi','','','','Cont debitor','','',''
union all select 'AD','CB','CB','21','Cont dif. curs','AC','@contdifcurs','','250','0','1','wACConturi','','','','Cont dif. curs','','',''
union all select 'AD','CB','CB','11','Cota tva','N','@cotatva','','40','1','1','','','','','Cota tva','','',''
union all select 'AD','CB','CB','9','Curs','N','@curs','','60','0','1','','','','','Curs','','',''
union all select 'AD','CB','CB','18','Data facturii','D','@datafacturii','','80','0','1','','','','','Data facturii','','',''
union all select 'AD','CB','CB','19','Data scadentei','D','@datascadentei','','80','0','1','','','','','Data scadentei','','',''
union all select 'AD','CB','CB','13','Explicatii','C','@explicatii','','200','0','1','','','','','Explicatii','','',''
union all select 'AD','CB','CB','4','Factura','AC','@facturadreapta','@facturadreapta','300','1','1','wACFacturiBenef','','','','Factura','','',''
union all select 'AD','CB','CB','3','Avans','AC','@facturastinga','@facturastinga','300','1','1','wACFacturiBenef','','','','Avans','','',''
union all select 'AD','CB','CB','17','Jurnal','C','@jurnal','','80','0','1','','','','','Jurnal','','',''
union all select 'AD','CB','CB','14','Loc munca','C','@lm','','80','0','1','','','','','Loc munca','','',''
union all select 'AD','CB','CB','16','Nr. pozitie','C','@numarpozitie','','60','0','1','','','','','Nr. pozitite','','',''
union all select 'AD','CB','CB','1','Tip','C','@subtip','','40','0','1','','','','','Tip','','',''
union all select 'AD','CB','CB','7','Suma','N','@suma','','80','1','1','','','','','Suma','','',''
union all select 'AD','CB','CB','20','Dif. curs in lei','N','@sumadifcurs','','80','0','1','','','','','','','',''
union all select 'AD','CB','CB','12','Suma tva','N','@sumatva','','80','1','1','','','','','Suma tva','','',''
union all select 'AD','CB','CB','10','Suma valuta','N','@sumavaluta','','80','0','1','','','','','Suma valuta','','',''
union all select 'AD','CB','CB','2','Tert beneficiar','AC','@tertbenef','@tertbenef','300','0','1','wACTerti','','','','Tert','','',''
union all select 'AD','CB','CB','8','Valuta','C','@valuta','','40','0','1','','','','','Valuta','','',''
union all select 'AD','CB','RN','3','Data','D','@data','','100','1','0','','','','','','','',''
union all select 'AD','CB','RN','2','Numar','C','@numar','','100','1','0','','','','','','','',''
union all select 'AD','CB','RN','1','Tip','C','@tip','','50','1','0','','','','','','','',''
union all select 'AD','CF','','2','Data','D','@data','','100','1','1','','','','','Data','','',''
union all select 'AD','CF','','4','Factura','AC','@factura','@factura','300','0','1','wACFacturi','','','','Factura','','',''
union all select 'AD','CF','','1','Numar','C','@numar','','100','1','1','','','','','Numar','','',''
union all select 'AD','CF','','3','Tert','AC','@tert','@dentert','300','1','1','wACTerti','','','','Tert','','',''
union all select 'AD','CF','','5','Total','N','@valoarecutva','','100','0','0','','','','','','','',''
union all select 'AD','CF','CF','22','Achit.fact.in valuta','N','@achitfact','','80','0','1','','','','','','','',''
union all select 'AD','CF','CF','15','Comanda','C','@comanda','','80','0','1','','','','','Comanda','','',''
union all select 'AD','CF','CF','6','Cont creditor','AC','@contcred','@contcred','250','1','1','wACConturi','','','','Cont creditor','','',''
union all select 'AD','CF','CF','5','Cont debitor','C','@contdeb','@contdeb','250','1','1','wACConturi','','','','Cont debitor','','',''
union all select 'AD','CF','CF','21','Cont dif. curs','AC','@contdifcurs','','250','0','1','wACConturi','','','','Cont dif. curs','','',''
union all select 'AD','CF','CF','11','Cota tva','N','@cotatva','','40','1','1','','','','','Cota tva','','',''
union all select 'AD','CF','CF','9','Curs','N','@curs','','60','0','1','','','','','Curs','','',''
union all select 'AD','CF','CF','18','Data facturii','D','@datafacturii','','80','0','1','','','','','Data facturii','','',''
union all select 'AD','CF','CF','19','Data scadentei','D','@datascadentei','','80','0','1','','','','','Data scadentei','','',''
union all select 'AD','CF','CF','13','Explicatii','C','@explicatii','','200','0','1','','','','','Explicatii','','',''
union all select 'AD','CF','CF','4','Factura dreapta','C','@facturadreapta','','80','1','1','','','','','Factura dreapta','','',''
union all select 'AD','CF','CF','3','Factura stanga','C','@facturastinga','','80','1','1',' ','','','','Factura stanga','','',''
union all select 'AD','CF','CF','17','Jurnal','C','@jurnal','','80','0','1','','','','','Jurnal','','',''
union all select 'AD','CF','CF','14','Loc munca','C','@lm','','80','0','1','','','','','Loc munca','','',''
union all select 'AD','CF','CF','16','Nr. pozitie','C','@numarpozitie','','60','0','1','','','','','Nr. pozitite','','',''
union all select 'AD','CF','CF','1','Tip','C','@subtip','','40','0','1','','','','','Tip','','',''
union all select 'AD','CF','CF','7','Suma','N','@suma','','80','1','1','','','','','Suma','','',''
union all select 'AD','CF','CF','20','Dif. curs in lei','N','@sumadifcurs','','80','0','1','','','','','','','',''
union all select 'AD','CF','CF','12','Suma tva','N','@sumatva','','80','0','1','','','','','Suma tva','','',''
union all select 'AD','CF','CF','10','Suma valuta','N','@sumavaluta','','80','0','1','','','','','Suma valuta','','',''
union all select 'AD','CF','CF','2','Tert beneficiar','AC','@tertbenef','@tertbenef','300','0','1','wACTerti','','','','Tert','','',''
union all select 'AD','CF','CF','8','Valuta','C','@valuta','','40','0','1','','','','','Valuta','','',''
union all select 'AD','CF','RN','3','Data','D','@data','','100','0','0','','','','','','','',''
union all select 'AD','CF','RN','2','Numar','C','@numar','','100','0','0','','','','','','','',''
union all select 'AD','CF','RN','1','Tip','C','@tip','','50','0','0','','','','','','','',''
union all select 'AD','CO','','2','Data','D','@data','','100','1','1','','','','','Data','','',''
union all select 'AD','CO','','4','Factura','AC','@factura','@factura','300','0','1','wACFacturi','','','','Factura','','',''
union all select 'AD','CO','','1','Numar','C','@numar','','100','1','1','','','','','Numar','','',''
union all select 'AD','CO','','3','Tert','AC','@tert','@dentert','300','1','1','wACTerti','','','','Tert','','',''
union all select 'AD','CO','','5','Total','N','@valoarecutva','','100','0','0','','','','','','','',''
union all select 'AD','CO','CO','15','Comanda','C','@comanda','','80','0','1','','','','','Comanda','','',''
union all select 'AD','CO','CO','6','Cont creditor','AC','@contcred','@contcred','250','1','1','wACConturi','','','','Cont creditor','','',''
union all select 'AD','CO','CO','5','Cont debitor','C','@contdeb','@contdeb','250','1','1','wACConturi','','','','Cont debitor','','',''
union all select 'AD','CO','CO','11','Cota tva','N','@cotatva','','40','1','1','','','','','Cota tva','','',''
union all select 'AD','CO','CO','9','Curs','N','@curs','','60','0','1','','','','','Curs','','',''
union all select 'AD','CO','CO','18','Data facturii','D','@datafacturii','','80','0','1','','','','','Data facturii','','',''
union all select 'AD','CO','CO','19','Data scadentei','D','@datascadentei','','80','0','1','','','','','Data scadentei','','',''
union all select 'AD','CO','CO','13','Explicatii','C','@explicatii','','200','0','1','','','','','Explicatii','','',''
union all select 'AD','CO','CO','4','Factura dreapta','AC','@facturadreapta',' ','200','1','1','wACFacturiBenef','','','','Factura dreapta','','',''
union all select 'AD','CO','CO','3','Factura stanga','AC','@facturastinga',' ','200','1','1','wACFacturiFurn','','','','Factura stanga','','',''
union all select 'AD','CO','CO','17','Jurnal','C','@jurnal','','80','0','1','','','','','Jurnal','','',''
union all select 'AD','CO','CO','14','Loc munca','C','@lm','','80','0','1','','','','','Loc munca','','',''
union all select 'AD','CO','CO','16','Nr. pozitie','C','@numarpozitie','','60','0','1','','','','','Nr. pozitite','','',''
union all select 'AD','CO','CO','1','Tip','C','@subtip','','40','0','1','','','','','Tip','','',''
union all select 'AD','CO','CO','7','Suma','N','@suma','','80','1','1','','','','','Suma','','',''
union all select 'AD','CO','CO','12','Suma tva','N','@sumatva','','80','0','1','','','','','Suma tva','','',''
union all select 'AD','CO','CO','10','Suma valuta','N','@sumavaluta','','80','0','1','','','','','Suma valuta','','',''
union all select 'AD','CO','CO','2','Tert beneficiar','AC','@tertbenef','@tertbenef','300','0','1','wACTerti','','','','Tert','','',''
union all select 'AD','CO','CO','8','Valuta','C','@valuta','','40','0','1','','','','','Valuta','','',''
union all select 'AD','CO','MA','4','Data','D','@data','','100','0','1','','','','','Data','','',''
union all select 'AD','CO','MA','5','Data_scadenta','D','@datascadentei','','100','1','1','','','','','Data scadentei','','',''
union all select 'AD','CO','MA','5','Jurnal','C','@jurnal','','150','1','1','','','','','Jurnal','','',''
union all select 'AD','CO','MA','4','Data','D','@n_data','','100','1','1','','','','','Data','','',''
union all select 'AD','CO','MA','2','Numar','C','@n_numar','','100','1','1','','','','','Numar','','',''
union all select 'AD','CO','MA','3','Tert','AC','@n_tert','@dentert','300','1','1','wACTerti','','','','Tert','','',''
union all select 'AD','CO','MA','1','Tip','C','@n_tip','','50','1','0','','','','','Tip','','',''
union all select 'AD','CO','MA','2','Numar','C','@numar','','100','0','1','','','','','Numar','','',''
union all select 'AD','CO','MA','3','Tert','AC','@tert','@dentert','300','0','1','wACTerti','','','','Tert','','',''
union all select 'AD','CO','MA','1','Tip','C','@tip','','50','0','0','','','','','Tip','','',''
union all select 'AD','CO','RN','3','Data','D','@data','','100','0','0','','','','','','','',''
union all select 'AD','CO','RN','2','Numar','C','@numar','','100','0','0','','','','','','','',''
union all select 'AD','CO','RN','1','Tip','C','@tip','','50','0','0','','','','','','','',''
union all select 'AD','FB','','2','Data','D','@data','','100','1','1','','','','','Data','','',''
union all select 'AD','FB','','4','Factura','AC','@factura','@factura','300','0','1','wACFacturi','','','','Factura','','',''
union all select 'AD','FB','','1','Numar','C','@numar','','100','1','1','','','','','Numar','','',''
union all select 'AD','FB','','3','Tert','AC','@tert','@dentert','300','1','1','wACTerti','','','','Tert','','',''
union all select 'AD','FB','','5','Total','N','@valoarecutva','','100','0','0','','','','','','','',''
union all select 'AD','FB','FB','15','Comanda','C','@comanda','','80','0','1','','','','','Comanda','','',''
union all select 'AD','FB','FB','6','Cont creditor','AC','@contcred','@contcred','250','1','1','wACConturi','','','','Cont creditor','','',''
union all select 'AD','FB','FB','5','Cont debitor','C','@contdeb','@contdeb','250','1','1','wACConturi','','','','Cont debitor','','',''
union all select 'AD','FB','FB','11','Cota tva','N','@cotatva','','40','1','1','','','','','Cota tva','','',''
union all select 'AD','FB','FB','9','Curs','N','@curs','','60','0','1','','','','','Curs','','',''
union all select 'AD','FB','FB','18','Data facturii','D','@datafacturii','','80','0','1','','','','','Data facturii','','',''
union all select 'AD','FB','FB','19','Data scadentei','D','@datascadentei','','80','0','1','','','','','Data scadentei','','',''
union all select 'AD','FB','FB','13','Explicatii','C','@explicatii','','200','0','1','','','','','Explicatii','','',''
union all select 'AD','FB','FB','4','Factura dreapta','C','@facturadreapta','','80','0','1','','','','','Factura dreapta','','',''
union all select 'AD','FB','FB','3','Factura','C','@facturastinga','','80','1','1',' ','','','','Factura','','',''
union all select 'AD','FB','FB','17','Jurnal','C','@jurnal','','80','0','1','','','','','Jurnal','','',''
union all select 'AD','FB','FB','14','Loc munca','C','@lm','','80','0','1','','','','','Loc munca','','',''
union all select 'AD','FB','FB','16','Nr. pozitie','C','@numarpozitie','','60','0','1','','','','','Nr. pozitite','','',''
union all select 'AD','FB','FB','1','Tip','C','@subtip','','40','0','1','','','','','Tip','','',''
union all select 'AD','FB','FB','7','Suma','N','@suma','','80','1','1','','','','','Suma','','',''
union all select 'AD','FB','FB','12','Suma tva','N','@sumatva','','80','0','1','','','','','Suma tva','','',''
union all select 'AD','FB','FB','10','Suma valuta','N','@sumavaluta','','80','0','1','','','','','Suma valuta','','',''
union all select 'AD','FB','FB','2','Tert beneficiar','AC','@tertbenef','@tertbenef','300','0','1','wACTerti','','','','Tert','','',''
union all select 'AD','FB','FB','20','Tip tva','CB','@tiptva','','150','0','1','','0,1,2','0 Colectat,1 Compensat,2 Neinregistrat','0','','','',''
union all select 'AD','FB','FB','8','Valuta','C','@valuta','','40','0','1','','','','','Valuta','','',''
union all select 'AD','FB','RN','3','Data','D','@data','','100','0','0','','','','','','','',''
union all select 'AD','FB','RN','2','Numar','C','@numar','','100','0','0','','','','','','','',''
union all select 'AD','FB','RN','1','Tip','C','@tip','','50','0','0','','','','','','','',''
union all select 'AD','FF','','2','Data','D','@data','','100','1','1','','','','','Data','','',''
union all select 'AD','FF','','4','Factura','AC','@factura','@factura','300','0','1','wACFacturi','','','','Factura','','',''
union all select 'AD','FF','','1','Numar','C','@numar','','100','1','1','','','','','Numar','','',''
union all select 'AD','FF','','3','Tert','AC','@tert','@dentert','300','1','1','wACTerti','','','','Tert','','',''
union all select 'AD','FF','','5','Total','N','@valoarecutva','','100','0','0','','','','','','','',''
union all select 'AD','FF','FF','15','Comanda','C','@comanda','','80','0','1','','','','','Comanda','','',''
union all select 'AD','FF','FF','6','Cont creditor','AC','@contcred','@contcred','250','1','1','wACConturi','','','','Cont creditor','','',''
union all select 'AD','FF','FF','5','Cont debitor','C','@contdeb','@contdeb','250','1','1','wACConturi','','','','Cont debitor','','',''
union all select 'AD','FF','FF','11','Cota tva','N','@cotatva','','40','1','1','','','','','Cota tva','','',''
union all select 'AD','FF','FF','9','Curs','N','@curs','','60','0','1','','','','','Curs','','',''
union all select 'AD','FF','FF','18','Data facturii','D','@datafacturii','','80','0','1','','','','','Data facturii','','',''
union all select 'AD','FF','FF','19','Data scadentei','D','@datascadentei','','80','0','1','','','','','Data scadentei','','',''
union all select 'AD','FF','FF','13','Explicatii','C','@explicatii','','200','0','1','','','','','Explicatii','','',''
union all select 'AD','FF','FF','4','Factura','C','@facturadreapta','','80','1','1','','','','','Factura','','',''
union all select 'AD','FF','FF','3','Factura stanga','C','@facturastinga','','80','0','0',' ','','','','Factura stanga','','',''
union all select 'AD','FF','FF','17','Jurnal','C','@jurnal','','80','0','1','','','','','Jurnal','','',''
union all select 'AD','FF','FF','14','Loc munca','C','@lm','','80','0','1','','','','','Loc munca','','',''
union all select 'AD','FF','FF','16','Nr. pozitie','C','@numarpozitie','','60','0','1','','','','','Nr. pozitite','','',''
union all select 'AD','FF','FF','1','Tip','C','@subtip','','40','0','1','','','','','Tip','','',''
union all select 'AD','FF','FF','7','Suma','N','@suma','','80','1','1','','','','','Suma','','',''
union all select 'AD','FF','FF','12','Suma tva','N','@sumatva','','80','0','1','','','','','Suma tva','','',''
union all select 'AD','FF','FF','10','Suma valuta','N','@sumavaluta','','80','0','1','','','','','Suma valuta','','',''
union all select 'AD','FF','FF','2','Tert beneficiar','AC','@tertbenef','@tertbenef','300','0','1','wACTerti','','','','Tert','','',''
union all select 'AD','FF','FF','20','Tip tva','CB','@tiptva','','150','0','1','','0,1,2,3','0 Deductibil,1 Compensat,2 Nedeductibil,3 Neded.cont intr.','0','','','',''
union all select 'AD','FF','FF','8','Valuta','C','@valuta','','40','0','1','','','','','Valuta','','',''
union all select 'AD','FF','RN','3','Data','D','@data','','100','0','0','','','','','','','',''
union all select 'AD','FF','RN','2','Numar','C','@numar','','100','0','0','','','','','','','',''
union all select 'AD','FF','RN','1','Tip','C','@tip','','50','0','0','','','','','','','',''
union all select 'AD','IF','','2','Data','D','@data','','100','1','0','','','','','Data','','',''
union all select 'AD','IF','','4','Factura','AC','@factura','@factura','150','0','1','wACFacturi','','','','Factura','','',''
union all select 'AD','IF','','1','Numar compens','C','@numar','','100','1','0','','','','','Numar','','',''
union all select 'AD','IF','','3','Tert','AC','@tert','@dentert','300','1','1','wACTerti','','','','Tert','','',''
union all select 'AD','IF','','5','Total','N','@valoarecutva','','100','0','0','','','','','','','',''
union all select 'AD','IF','IF','15','Comanda','C','@comanda','','80','0','1','','','','','Comanda','','',''
union all select 'AD','IF','IF','6','Cont creditor','AC','@contcred','@contcred','100','1','0','wACConturi','','','','Cont creditor','','',''
union all select 'AD','IF','IF','5','Cont debitor','AC','@contdeb','@contdeb','100','1','0','wACConturi','','','411.2','Cont debitor','','',''
union all select 'AD','IF','IF','11','Cota tva','CB','@cotatva','','60','1','1','','0.00,9.00,19.00,24.00','0.00,9.00,19.00,24.00','24.00','Cota tva','','',''
union all select 'AD','IF','IF','9','Curs','N','@curs','','60','0','1','','','','','Curs','','',''
union all select 'AD','IF','IF','18','Data facturii','D','@datafacturii','','80','0','1','','','','','Data facturii','','',''
union all select 'AD','IF','IF','19','Data scadentei','D','@datascadentei','','80','0','1','','','','','Data scadentei','','',''
union all select 'AD','IF','IF','15','Diff.TVA','N','@diftva','','60','0','0','','','','','','','',''
union all select 'AD','IF','IF','14','Explicatii','C','@explicatii','','200','1','1','','','','','Explicatii','','',''
union all select 'AD','IF','IF','4','Aviz 418.0','AC','@facturadreapta','@facturadreapta','200','1','1','wACFacturiBenef','','','','Aviz 418.0','','',''
union all select 'AD','IF','IF','3','Factura stanga','C','@facturastinga','','100','1','0',' ','','','','Factura stanga','','',''
union all select 'AD','IF','IF','17','Jurnal','C','@jurnal','','80','0','1','','','','','Jurnal','','',''
union all select 'AD','IF','IF','13','Loc munca','C','@lm','','80','1','0','','','','','Loc munca','','',''
union all select 'AD','IF','IF','16','Nr. pozitie','C','@numarpozitie','','60','0','1','','','','','Nr. pozitite','','',''
union all select 'AD','IF','IF','1','Tip','C','@subtip','','40','0','1','','','','','Tip','','',''
union all select 'AD','IF','IF','7','Val F Tva','N','@suma','','120','1','1','','','','','Suma','','',''
union all select 'AD','IF','IF','12','Val Tva','N','@sumatva','','100','1','1','','','','','Suma tva','','',''
union all select 'AD','IF','IF','10','Suma valuta','N','@sumavaluta','','80','0','1','','','','','Suma valuta','','',''
union all select 'AD','IF','IF','2','Tert beneficiar','AC','@tertbenef','@tertbenef','300','0','1','wACTerti','','','','Tert','','',''
union all select 'AD','IF','IF','20','Tip tva','CB','@tiptva','','150','0','1','','0,1,2','0 Colectat,1 Compensat,2 Neinregistrat','0','','','',''
union all select 'AD','IF','IF','8','Valuta','C','@valuta','','40','0','1','','','','','Valuta','','',''
union all select 'AD','IF','RN','3','Data','D','@data','','100','0','0','','','','','','','',''
union all select 'AD','IF','RN','2','Numar','C','@numar','','100','0','0','','','','','','','',''
union all select 'AD','IF','RN','1','Tip','C','@tip','','50','0','0','','','','','','','',''
union all select 'AD','SF','','2','Data','D','@data','','100','1','1','','','','','Data','','',''
union all select 'AD','SF','','4','Factura','AC','@factura','@factura','300','0','1','wACFacturi','','','','Factura','','',''
union all select 'AD','SF','','1','Numar','C','@numar','','100','1','1','','','','','Numar','','',''
union all select 'AD','SF','','3','Tert','AC','@tert','@dentert','300','1','1','wACTerti','','','','Tert','','',''
union all select 'AD','SF','','5','Total','N','@valoarecutva','','100','0','0','','','','','','','',''
union all select 'AD','SF','RN','3','Data','D','@data','','100','0','0','','','','','','','',''
union all select 'AD','SF','RN','2','Numar','C','@numar','','100','0','0','','','','','','','',''
union all select 'AD','SF','RN','1','Tip','C','@tip','','50','0','0','','','','','','','',''
union all select 'AD','SF','SF','15','Comanda','C','@comanda','','80','0','1','','','','','Comanda','','',''
union all select 'AD','SF','SF','6','Cont creditor','AC','@contcred','@contcred','250','1','1','wACConturi','','','','Cont creditor','','',''
union all select 'AD','SF','SF','5','Cont debitor','C','@contdeb','@contdeb','250','1','1','wACConturi','','','','Cont debitor','','',''
union all select 'AD','SF','SF','11','Cota tva','N','@cotatva','','40','1','1','','','','','Cota tva','','',''
union all select 'AD','SF','SF','9','Curs','N','@curs','','60','0','1','','','','','Curs','','',''
union all select 'AD','SF','SF','18','Data facturii','D','@datafacturii','','80','0','1','','','','','Data facturii','','',''
union all select 'AD','SF','SF','19','Data scadentei','D','@datascadentei','','80','0','1','','','','','Data scadentei','','',''
union all select 'AD','SF','SF','15','Diff.TVA','N','@diftva','','60','1','1','','','','','','','',''
union all select 'AD','SF','SF','13','Explicatii','C','@explicatii','','200','0','1','','','','','Explicatii','','',''
union all select 'AD','SF','SF','4','Factura dreapta','C','@facturadreapta','','80','1','1','','','','','Factura dreapta','','',''
union all select 'AD','SF','SF','3','Factura stanga','C','@facturastinga','','80','1','1',' ','','','','Factura stanga','','',''
union all select 'AD','SF','SF','17','Jurnal','C','@jurnal','','80','0','1','','','','','Jurnal','','',''
union all select 'AD','SF','SF','14','Loc munca','C','@lm','','80','0','1','','','','','Loc munca','','',''
union all select 'AD','SF','SF','16','Nr. pozitie','C','@numarpozitie','','60','0','1','','','','','Nr. pozitite','','',''
union all select 'AD','SF','SF','1','Tip','C','@subtip','','40','0','1','','','','','Tip','','',''
union all select 'AD','SF','SF','7','Suma','N','@suma','','80','1','1','','','','','Suma','','',''
union all select 'AD','SF','SF','12','Suma tva','N','@sumatva','','80','0','1','','','','','Suma tva','','',''
union all select 'AD','SF','SF','10','Suma valuta','N','@sumavaluta','','80','0','1','','','','','Suma valuta','','',''
union all select 'AD','SF','SF','2','Tert beneficiar','AC','@tertbenef','@tertbenef','300','0','1','wACTerti','','','','Tert','','',''
union all select 'AD','SF','SF','20','Tip tva','CB','@tiptva','','150','0','1','','0,1,2','0 Deductibil,1 Compensat,2 Nedeductibil','0','','','',''
union all select 'AD','SF','SF','8','Valuta','C','@valuta','','40','0','1','','','','','Valuta','','',''

insert into webconfigtaburi (MeniuSursa,TipSursa,NumeTab,icoana,TipMachetaNoua,MeniuNou,TipNou,ProcPopulare,Ordine,Vizibil)
select top 0 null,null,null,null,null,null,null,null,null,null
union all select 'AD','C3','Compensari in 3','','PozDoc','AD','C3','','10','1'
union all select 'AD','C3','Note contabile','','PozDoc','IK','IC','','20','1'
union all select 'AD','CB','Compensari benef.','','PozDoc','AD','CB','','10','1'
union all select 'AD','CB','Note contabile','','PozDoc','IK','IC','','20','1'
union all select 'AD','CF','Compensari furnizori','','PozDoc','AD','CF','','10','1'
union all select 'AD','CF','Note contabile','','PozDoc','IK','IC','','20','1'
union all select 'AD','CO','Compensari','','PozDoc','AD','CO','','10','1'
union all select 'AD','CO','Note contabile','','PozDoc','IK','IC','','20','1'
union all select 'AD','FB','Facturi benef.','','PozDoc','AD','FB','','10','1'
union all select 'AD','FB','Note contabile','','PozDoc','IK','IC','','20','1'
union all select 'AD','FF','Facturi furnizori','','PozDoc','AD','FF','','10','1'
union all select 'AD','FF','Note contabile','','PozDoc','IK','IC','','20','1'
union all select 'AD','IF','Intocmire fact.benef','','PozDoc','AD','IF','','10','1'
union all select 'AD','IF','Note contabile','','PozDoc','IK','IC','','20','1'
union all select 'AD','SF','Note contabile','','PozDoc','IK','IC','','20','1'
union all select 'AD','SF','Sosire fact. furn.','','PozDoc','AD','SF','','10','1'
GO
