
--if exists (select 1 from webconfigmeniu where meniu='BO') begin raiserror('Acest meniu este configurat deja! Daca doriti, stergeti manual linia din webConfigMeniu',11,1) return end
delete from webconfigmeniu where tipMacheta='D' and meniu='BO'
delete from webconfigfiltre where meniu='BO' and (''='' or isnull(tip,'')='')
delete from webconfiggrid where meniu='BO' and (''='' or isnull(tip,'')='') and (''='' or isnull(subtip,'')='')
delete from webconfigtipuri where meniu='BO' and (''='' or isnull(tip,'')='') and (''='' or isnull(subtip,'')='')
delete from webconfigform where meniu='BO' and (''='' or isnull(tip,'')='') and (''='' or isnull(subtip,'')='')
delete from webConfigTaburi where MeniuSursa='BO' and (''='' or isnull(TipSursa,'')='')

insert into webconfigmeniu --(id,Nume,idParinte,Icoana,TipMacheta,Meniu,Modul)
				(Meniu, Nume, MeniuParinte, Icoana, TipMacheta, NrOrdine, Componenta, Semnatura, Detalii, vizibil)
select top 0 null,null,null,null,null,null,null,null,null,null
union all select 'BO','Bonuri','DOCUMENTE','Bonuri','D',18.00,'','','<row><vechi><row id="18" nume="Bonuri" idparinte="1" icoana="Bonuri" tipmacheta="D" meniu="BO" modul="0"/></vechi></row>',1

insert into webconfiggrid (Meniu, Tip, Subtip, InPozitii, NumeCol, DataField, TipObiect, Latime, Ordine, Vizibil, Modificabil, Formula) 
select top 0 null,null,null,null,null,null,null,null,null,null,null,null
union all select 'BO','BC','','0','Comanda','@comanda','C','80','13','1','0',' '
union all select 'BO','BC','','0','Com.livr.','@contract','C','80','17','1','0',' '
union all select 'BO','BC','','0','Den.comanda','@dencomanda','C','100','15','1','0',' '
union all select 'BO','BC','','1','Cantitate','@cantitate','N','80','3','1','0',''
union all select 'BO','BC','','0','Casa','@casam','N','40','-3','1','0',''
union all select 'BO','BC','','1','Cod','@cod','C','100','1','1','0',''
union all select 'BO','BC','','0','Data','@data','D','70','1','1','0',''
union all select 'BO','BC','','0','Den.gestiune','@dengestiune','C','100','8','0','0',''
union all select 'BO','BC',' ','0','Client','@dentert','C','150','4','1','0',''
union all select 'BO','BC','','1','Beneficiar','@dentert','C','250','9','0','0',''
union all select 'BO','BC','','1','Denumire','@denumire','C','350','2','1','0',''
union all select 'BO','BC','','0','Factura','@factura','C','50','3','1','0',''
union all select 'BO','BC','','0','Gestiune','@gestiune','C','50','-5','1','0',''
union all select 'BO','BC','','0','Nr.bon','@numar','C','50','0','1','0',''
union all select 'BO','BC','','0','Nr.pozitii','@numarpozitii','N','50','6','1','0',''
union all select 'BO','BC','','0','Ora','@ora','D','50','2','1','0',''
union all select 'BO','BC','','1','Val cu TVA','@pret','N','80','4','1','0',''
union all select 'BO','BC','','1','Val TVA','@tva','N','80','5','1','0',''
union all select 'BO','BC','','0','Val cu TVA','@valtotala','N','80','5','1','0',''
union all select 'BO','BC','','0','Vanzator','@vanzator','C','80','10','1','0',''
union all select 'BO','BN','','1','Cantitate','@cantitate','N','80','3','1','0',''
union all select 'BO','BN','','0','Casa de marcat','@casam','N','100','7','1','0',''
union all select 'BO','BN','','1','Cod','@cod','C','100','1','1','0',''
union all select 'BO','BN','','0','Data','@data','D','80','2','1','0',''
union all select 'BO','BN','','0','Denumire gestiune','@dengestiune','C','200','6','1','0',''
union all select 'BO','BN','','0','Beneficiar','@dentert','C','250','9','1','0',''
union all select 'BO','BN','','1','Denumire','@denumire','C','250','2','1','0',''
union all select 'BO','BN','','0','Factura','@factura','C','100','10','1','0',''
union all select 'BO','BN','','0','Gestiune','@gestiune','C','80','5','1','0',''
union all select 'BO','BN','','0','Numar bon','@numar','C','100','1','1','0',''
union all select 'BO','BN','','0','Numar pozitii','@numarpozitii','N','100','4','1','0',''
union all select 'BO','BN','','0','Ora','@ora','D','50','2','1','0',''
union all select 'BO','BN','','1','Pret cu TVA','@pret','N','80','4','1','0',''
union all select 'BO','BN','','1','TVA','@tva','N','80','5','1','0',''
union all select 'BO','BN','','0','Valoare','@valtotala','N','120','3','1','0',''
union all select 'BO','BN','','0','Vanzator','@vanzator','C','150','8','1','0',''
union all select 'BO','BY','','1','Cantitate','@cantitate','N','80','3','1','0',''
union all select 'BO','BY','','0','Casa de marcat','@casam','N','80','5','1','0',''
union all select 'BO','BY','','1','Cod','@cod','C','100','1','1','0',''
union all select 'BO','BY','','0','Data facturii','@data','D','100','2','1','0',''
union all select 'BO','BY','','0','Beneficiar','@dentert','C','250','7','1','0',''
union all select 'BO','BY','','1','Denumire','@denumire','C','250','2','1','0',''
union all select 'BO','BY','','0','Factura','@factura','C','100','1','1','0',''
union all select 'BO','BY','','0','Numar bon','@numar','C','100','1','0','0',''
union all select 'BO','BY','','0','Numar pozitii','@numarpozitii','N','100','4','1','0',''
union all select 'BO','BY','','1','Pret cu TVA','@pret','N','80','4','1','0',''
union all select 'BO','BY','','1','Valoare TVA','@tva','N','80','5','1','0',''
union all select 'BO','BY','','0','Valoarea totala','@valtotala','N','120','3','1','0',''
union all select 'BO','BY','','0','Vanzator','@vanzator','C','150','6','1','0',''
union all select 'BO','BC','','1','Discount','@discount','N','60','10','1','0',' '
union all select 'BO','BC','SB','1','Cod','@cod_produs','C','100','1','1','0',''
union all select 'BO','BC','SB','1','Denumire','@denumire','C','300','2','1','0',''
union all select 'BO','BC','SB','1','Gestiune','@gestiune','C','150','3','1','0',''
union all select 'BO','BC','SB','1','Cantitate','@cantitate','N','100','4','1','0',''
union all select 'BO','BC','SB','1','Cod intrare','@codintrare','C','100','5','0','0',''
union all select 'BO','BC','SB','1','Pret furnizor','@pstoc','C','100','6','0','0',''
union all select 'BO','BC','SB','1','Pret amanunt','@pret','N','100','7','1','0',''
union all select 'BO','BC','SB','1','Cant. storno','@cant_storno','N','100','8','1','1',''

insert into webconfigFiltre (Meniu, Tip, Ordine, Vizibil, TipObiect, Descriere, Prompt1, DataField1, Interval, Prompt2, DataField2) 
select top 0 null,null,null,null,null,null,null,null,null,null,null
union all select 'BO','BN','2','0','','Data','Data bon','@data','0','',''
union all select 'BO','BN','3','1','','Casa','Casa de marcat','@f_casam','0','',''
union all select 'BO','BN','4','1','','Benenficiar','Tert','@f_dentert','0','',''
union all select 'BO','BN','5','0','','Factura','Numar factura','@f_factura','0','',''
union all select 'BO','BN','6','1','','Gestiunea','Cod gestiune','@f_gestiune','0','',''
union all select 'BO','BN','1','1','','Numar','Numar bon','@numar','0','',''
union all select 'BO','BY','2','1','','Benenficiar','Denumire beneficiar','@f_dentert','0','',''
union all select 'BO','BY','1','1','','Factura','Numar factura','@f_factura','0','',''
union all select 'BO','BC','2','0','','Data','Data bon','@data','0','',''
union all select 'BO','BC','3','1','','Casa','Casa de marcat','@f_casam','0','',''
union all select 'BO','BC','6','1','','Client','Tert','@f_dentert','0','',''
union all select 'BO','BC','5','0','','Factura','Numar factura','@f_factura','0','',''
union all select 'BO','BC','4','1','','Gestiunea','Cod gestiune','@f_gestiune','0','',''
union all select 'BO','BC','1','1','','Numar','Numar bon','@numar','0','',''

insert into webconfigTipuri (Meniu, Tip, Subtip, Ordine, Nume, Descriere, TextAdaugare, TextModificare, ProcDate, ProcScriere, ProcStergere, ProcDatePoz, ProcScrierePoz, ProcStergerePoz, Vizibil, Fel, procPopulare,tasta) 
select top 0 null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
union all select 'BO','BY','','2','Factura','','','','wIaBonuri','','','wIaPozBonuri',' ','','1','','',''
union all select 'BO','BY','AF','1','Anulare bon','Operatie de anulare bon! Operatia va anula bonul fie ca are factura, fie ca nu are.  In ambele cazuri operatia va sterge documente corespunzatoare CG: AC/TE.','','','','wOPAnulareBon','','','','','1','O','',''
union all select 'BO','BY','BY','1','Pozitie factura','','','','','','','','','','1','','',''
union all select 'BO','','','0','','','','','','','','','','','0',' ','',''
union all select 'BO','BC','','1','Bon casa','','','','wIaBonuri','','','wIaPozBonuri',' ','','1','','',''
union all select 'BO','BC','AF','1','Anulare bon','Operatie de anulare bon! Operatia va anula bonul fie ca are factura, fie ca nu are.  In ambele cazuri operatia va sterge documente corespunzatoare CG: AC/TE.','','','','wOPAnulareBon','','','','','1','O','',''
union all select 'BO','BC','BC','1','Pozitie bon','','','','','','','','','','1','','',''
union all select 'BO','BC','FP','4','Formular pachete','','','','','yso_wOPFormularPacheteBonPV','','','','','1','O','',''
union all select 'BO','BN','','1','Bon nedescarcat','','','','wIaBonuriNedescarcateSP','','','wIaPozBonuri',' ','','1','','',''
union all select 'BO','BN','AF','1','Anulare bon','Operatie de anulare bon! Operatia va anula bonul fie ca are factura, fie ca nu are.  In ambele cazuri operatia va sterge documente corespunzatoare CG: AC/TE.','','','','wOPAnulareBon','','','','','1','O','',''
union all select 'BO','BN','BN','1','Pozitie bon','','','','','','','','','','1','','',''
union all select 'BO','BN','FP','4','Formular pachete','','','','','yso_wOPFormularPacheteBonPV','','','','','1','O','',''
union all select 'BO','BN','DB','3','Dealocare bon','Operatie de stergere date de factura de pe bonul selectat fara a sterge bonul!','','','','wOPDealocareBon','','','','','1','O','wOPDealocareBon_p',''
union all select 'BO','BC','DB','3','Dealocare bon','Operatie de stergere date de factura de pe bonul selectat fara a sterge bonul!','','','','wOPDealocareBon','','','','','1','O','wOPDealocareBon_p',''
union all select 'BO','BN','RF','2','Refacere AC/TE','Refacere AC/AP si TE din bonuri (bp) pe bonul si gestiunea bonului selectat. Se presupune ca gestiunea data apare si pe AP si pe AC, iar TE automat se face in ambele cazuri.','','','','wOPRefacACTE','','','','','1','O','yso_wOPRefacACTE_p',''
union all select 'BO','BC','RF','2','Refacere AC/TE','Refacere AC/AP si TE din bonuri (bp) pe bonul si gestiunea bonului selectat. Se presupune ca gestiunea data apare si pe AP si pe AC, iar TE automat se face in ambele cazuri.','','','','wOPRefacACTE','','','','','1','O','yso_wOPRefacACTE_p',''
union all select 'BO','BC','SB','4','Stornare bon','Operatia realizeaza stornarea pozitiilor de pe bon generand o factura storno, o plata diverse si listeaza formularul de factura si plata. Campul cantitate storno este editabil si se completeaza cu valoarea zero daca nu se doreste stornarea pozitiei sau cu valori negative care sa nu depaseasca cantitatea de pe pozitia respectiva.','','','','wOPStornareBon','','','','','1','O','wOPStornareBon_p',''

insert into webconfigForm (Meniu, Tip, Subtip, Ordine, Nume, TipObiect, DataField, LabelField, Latime, Vizibil, Modificabil, ProcSQL, ListaValori, ListaEtichete, Initializare, Prompt, Procesare, Tooltip, formula)
select top 0 null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
union all select 'BO','BC','','3','Casa','N','@casam','','40','1','1','','','','','Nr. casa','','',''
union all select 'BO','BC',' ','2','Data','D','@data','','80','1','1','','','','','','','',''
union all select 'BO','BC','','5','Beneficiar','C','@dentert','','250','1','1','','','','','Nume beneficiar','','',''
union all select 'BO','BC','','1','Numar bon','C','@numar','','80','1','1','','','','','','','',''
union all select 'BO','BC','','6','Valoare','N','@valtotala','','100','1','1','','','','','Valoare cu TVA','','',''
union all select 'BO','BC','','4','Vanzator','C','@vanzator','','150','1','1','','','','','Nume vanzator','','',''
union all select 'BO','BC','AF','6','Anulare bon/factura','CHB','@anularefact','','200','1','1','','','','','Anulare bon/factura','','',''
union all select 'BO','BC','AF','2','Data','D','@data','','100','1','0','','','','','','','',''
union all select 'BO','BC','AF','5','Beneficiar','C','@dentert','','250','1','0','','','','','','','',''
union all select 'BO','BC','AF','1','Numar bon','C','@numar','','100','1','0','','','','','','','',''
union all select 'BO','BC','AF','3','Valoare','N','@valtotala','','80','1','0','','','','','','','',''
union all select 'BO','BC','AF','4','Vanzator','C','@vanzator','','150','1','0','','','','','','','',''
union all select 'BO','BC','DB','1','Bon nr:','C','@bon','','100','1','0','','','','','','','',''
union all select 'BO','BC','DB','3','Client','C','@client','','250','1','0','','','','','','','',''
union all select 'BO','BC','DB','2','Data bon','D','@databon','','100','1','0','','','','','','','',''
union all select 'BO','BC','DB','5','Data facturii','D','@datafacturii','','100','1','0','','','','','','','',''
union all select 'BO','BC','DB','4','Factura','C','@factura','','100','1','0','','','','','','','',''
union all select 'BO','BC','RF','2','Generare documente','CHB','@generare','','200','1','1','','','','','','','',''
union all select 'BO','BC','RF','1','Stergere documente','CHB','@stergere','','200','1','1','','','','','','','',''
union all select 'BO','BN','','3','Casa','N','@casam','','40','1','1','','','','','Nr. casa','','',''
union all select 'BO','BN',' ','2','Data','D','@data','','80','1','1','','','','','','','',''
union all select 'BO','BN','','5','Beneficiar','C','@dentert','','250','1','1','','','','','Nume beneficiar','','',''
union all select 'BO','BN','','1','Numar bon','C','@numar','','80','1','1','','','','','','','',''
union all select 'BO','BN','','6','Valoare','N','@valtotala','','100','1','1','','','','','Valoare cu TVA','','',''
union all select 'BO','BN','','4','Vanzator','C','@vanzator','','150','1','1','','','','','Nume vanzator','','',''
union all select 'BO','BN','AF','6','Anulare bon/factura','CHB','@anularefact','','200','1','1','','','','','Anulare bon/factura','','',''
union all select 'BO','BN','AF','2','Data','D','@data','','100','1','0','','','','','','','',''
union all select 'BO','BN','AF','5','Beneficiar','C','@dentert','','250','1','0','','','','','','','',''
union all select 'BO','BN','AF','1','Numar bon','C','@numar','','100','1','0','','','','','','','',''
union all select 'BO','BN','AF','3','Valoare','N','@valtotala','','80','1','0','','','','','','','',''
union all select 'BO','BN','AF','4','Vanzator','C','@vanzator','','150','1','0','','','','','','','',''
union all select 'BO','BN','DB','1','Bon nr:','C','@bon','','100','1','0','','','','','','','',''
union all select 'BO','BN','DB','3','Client','C','@client','','250','1','0','','','','','','','',''
union all select 'BO','BN','DB','2','Data bon','D','@databon','','100','1','0','','','','','','','',''
union all select 'BO','BN','DB','5','Data facturii','D','@datafacturii','','100','1','0','','','','','','','',''
union all select 'BO','BN','DB','4','Factura','C','@factura','','100','1','0','','','','','','','',''
union all select 'BO','BN','RF','2','Generare documente','CHB','@generare','','200','1','1','','','','','','','',''
union all select 'BO','BN','RF','1','Stergere documente','CHB','@stergere','','200','1','1','','','','','','','',''
union all select 'BO','BN','SB','4','Data','D','@data_storno','','200','1','0','','','','','','','',''
union all select 'BO','BN','SB','2','Gestiune','AC','@gestiune_storno','@dengestiune_storno','200','1','0','wACGestiuni','','','','','','',''
union all select 'BO','BN','SB','3','Loc de munca','AC','@lm_storno','@denlm_storno','200','1','0','wACLocm','','','','','','',''
union all select 'BO','BN','SB','1','Tert','AC','@tert_storno','','200','1','1','wACTerti','','','','Tert factura','','',''
union all select 'BO','BY','','3','Casa','N','@casam','','40','1','1','','','','','','','',''
union all select 'BO','BY','','2','Data','D','@data','','100','1','1','','','','','Data facturii','','',''
union all select 'BO','BY','','5','Beneficiar','C','@dentert','','250','1','1','','','','','Denumire beneficiar','','',''
union all select 'BO','BY','','1','Numar factura','C','@numar','','80','1','1','','','','','Numar','','',''
union all select 'BO','BC','SB','1','Tert','AC','@tert_storno','','200','1','1','wACTerti','','','','Tert factura','','',''
union all select 'BO','BC','SB','2','Gestiune','AC','@gestiune_storno','@dengestiune_storno','200','1','1','wACGestiuni','','','','','','',''
union all select 'BO','BC','SB','3','Loc de munca','AC','@lm_storno','@denlm_storno','200','1','1','wACLocm','','','','','','',''
union all select 'BO','BC','SB','4','Data','D','@data_storno','','200','1','1','','','','','','','',''
union all select 'BO','BC','SB','5','Fara generare in plati incasari','CHB','@faraplin','','200','1','1','','','','','','','',''

insert into webconfigtaburi (MeniuSursa,TipSursa,NumeTab,icoana,TipMachetaNoua,MeniuNou,TipNou,ProcPopulare,Ordine,Vizibil)
select top 0 null,null,null,null,null,null,null,null,null,null
union all select 'BO','BC','Aviz chitanta','','PozDoc','DO','AC','yso_wIaAvizBon_p','30','1'
union all select 'BO','BC','Bon casa','','PozDoc','BO','BC','','10','1'
union all select 'BO','BC','Date client','','C','T','','','60','1'
union all select 'BO','BC','Transfer','','PozDoc','DO','TE','yso_wIaTEBon_p','20','1'
union all select 'BO','BY','Aviz','','PozDoc','DO','AP','yso_wIaAvizBon_p','20','0'
union all select 'BO','BY','Factura PV','','PozDoc','BO','BY','','10','1'
GO
