CREATE INDEX missing_index_2596 ON [TET].[dbo].[bp] ([Client])			
CREATE INDEX missing_index_2591 ON [TET].[dbo].[doc] ([Tip], [Cod_tert])			
CREATE INDEX missing_index_2584 ON [TET].[dbo].[pozdoc] ([Tip], [Tert]) INCLUDE ([Subunitate], [Numar], [Cod], [Data], [Gestiune], [Cantitate], [Pret_valuta], [Pret_de_stoc], [Adaos], [Pret_vanzare], [Pret_cu_amanuntul], [TVA_deductibil], [Cota_TVA], [Utilizator], [Data_operarii], [Ora_operarii], [Cod_intrare], [Cont_de_stoc], [Cont_corespondent], [TVA_neexigibil], [Pret_amanunt_predator], [Tip_miscare], [Locatie], [Data_expirarii], [Numar_pozitie], [Loc_de_munca], [Comanda], [Barcod], [Cont_intermediar], [Cont_venituri], [Discount], [Factura], [Gestiune_primitoare], [Numar_DVI], [Stare], [Grupa], [Cont_factura], [Valuta], [Curs], [Data_facturii], [Data_scadentei], [Procent_vama], [Suprataxe_vama], [Accize_cumparare], [Accize_datorate], [Contract], [Jurnal], [detalii], [idPozDoc], [subtip], [idIntrareFirma], [idIntrare], [idIntrareTI])			
CREATE INDEX missing_index_2593 ON [TET].[dbo].[doc] ([Cod_gestiune], [Cod_tert])			
CREATE INDEX missing_index_2564 ON [TET].[dbo].[pozdoc] ([Cont_factura], [Tip], [Data]) INCLUDE ([Numar], [Cont_corespondent], [Tert], [Factura], [Data_facturii])			
CREATE INDEX missing_index_2556 ON [TESTOV].[dbo].[pozincon] ([Subunitate], [Cont_debitor], [Data]) INCLUDE ([Suma], [Loc_de_munca])			
CREATE INDEX missing_index_2558 ON [TESTOV].[dbo].[pozincon] ([Subunitate], [Cont_creditor], [Data]) INCLUDE ([Suma], [Loc_de_munca])			
CREATE INDEX missing_index_2560 ON [TESTOV].[dbo].[pozincon] ([Subunitate], [Cont_debitor], [Data]) INCLUDE ([Valuta], [Suma_valuta], [Loc_de_munca])			
CREATE INDEX missing_index_2562 ON [TESTOV].[dbo].[pozincon] ([Subunitate], [Cont_creditor], [Data]) INCLUDE ([Valuta], [Suma_valuta], [Loc_de_munca])			
CREATE INDEX missing_index_2598 ON [TET].[dbo].[bp] ([Vinzator], [Client])			
CREATE INDEX missing_index_2587 ON [TET].[dbo].[pozdoc] ([Tip], [Gestiune], [Tert]) INCLUDE ([Subunitate], [Numar], [Data], [Numar_pozitie])			
CREATE INDEX missing_index_2553 ON [TET].[dbo].[stocuri] ([Subunitate], [Cod])			
CREATE INDEX missing_index_2605 ON [TEST].[dbo].[webConfigSTDForm] ([Meniu], [Tip], [Subtip]) INCLUDE ([Ordine], [Nume], [TipObiect], [DataField], [LabelField], [Latime], [Vizibil], [Modificabil], [ProcSQL], [ListaValori], [ListaEtichete], [Initializare], [Prompt], [Procesare], [Tooltip])			
CREATE INDEX missing_index_2579 ON [TEST].[dbo].[nomencl] ([Cont]) INCLUDE ([Cod])			
CREATE INDEX missing_index_2582 ON [TEST].[dbo].[par] ([Tip_parametru], [Val_alfanumerica]) INCLUDE ([Parametru], [Denumire_parametru], [Val_logica], [Val_numerica])			
CREATE INDEX missing_index_2572 ON [TET].[dbo].[facturi] ([Subunitate], [Tip], [Tert])			
CREATE INDEX missing_index_2603 ON [TEST].[dbo].[webConfigTipuri] ([Meniu]) INCLUDE ([Subtip], [ProcInchidereMacheta])			
CREATE INDEX missing_index_2609 ON [TET].[dbo].[pozincon] ([Data]) INCLUDE ([Subunitate], [Tip_document], [Numar_document], [Cont_debitor], [Cont_creditor], [Suma], [Utilizator], [Numar_pozitie])			
CREATE INDEX missing_index_2576 ON [TEST].[dbo].[antetBonuri] ([Chitanta], [Data_bon]) INCLUDE ([Casa_de_marcat], [Numar_bon], [Vinzator], [Factura], [Data_facturii], [Tert], [Gestiune], [Contract], [Comanda], [IdAntetBon])			
CREATE INDEX missing_index_2612 ON [TET].[dbo].[facturi] ([Subunitate], [Tert])			
