select * from avnefac a where a.Terminal='ASIS'
SELECT* from pozplin p where p.Tert='RO21489482   '
select rtrim(isnull((select val_alfanumerica from par where tip_parametru='GE' and parametru='NUME'),'')) as [FIRMA], rtrim(isnull((select val_alfanumerica from par where tip_parametru='GE' and parametru='JUDET'),'')) as [JUDF], rtrim(isnull((select val_alfanumerica from par where tip_parametru='GE' and parametru='ADRESA'),'')) as [ADRESAF], rtrim(isnull((select val_alfanumerica from par where tip_parametru='GE' and parametru='CONTBC'),'')) as [CONTF], rtrim(isnull((select val_alfanumerica from par where tip_parametru='GE' and parametru='BANCA'),'')) as [BANCAF], rtrim(isnull((select val_alfanumerica from par where tip_parametru='GE' and parametru='CODFISC'),'')) as [CUIF], rtrim(isnull((select val_alfanumerica from par where tip_parametru='GE' and parametru='ORDREG'),'')) as [JF], rtrim(isnull((select val_alfanumerica from par where tip_parametru='GE' and parametru='CAPITALS'),'')) as [CAPSOC], rtrim(max(terti.denumire)) as [TERT], rtrim(max(terti.adresa)) as [ADRESA], rtrim((select lm.Denumire from lm  where pozplin.loc_de_munca= lm.Cod)) as [PUNCTLUCRU], rtrim(max(pozplin.numar)) as [NRCHIT], rtrim(convert(char(10),pozplin.data,103)) as [DATACHIT], rtrim(convert(char(15),convert(money,round(pozplin.suma,2)),1)) as [SUMA], rtrim(dbo.nr2text(round(pozplin.suma,2))) as [TRANSFORM], rtrim('C / V facturii') as [CE], rtrim(rtrim(pozplin.factura)+' din '+convert(CHAR(10),(select top 1 f.data from facturi f where f.subunitate=pozplin.subunitate and f.tert=pozplin.tert and f.factura=pozplin.factura),103)) as [FACTURA], rtrim(MAX(TERTI.LOCALITATE)) as [LOCALIT], rtrim(max(terti.JUDET)) as [JUDETBEN], rtrim(MAX(TERTI.COD_FISCAL)) as [CUIBEN], rtrim((select max(BANCA3)  from INFOTERT WHERE pozplin.TERT=INFOTERT.TERT AND INFOTERT.SUBUNITATE='1' and infotert.identificator='')) as [JBEN]
 --into ##raspASIS 
FROM avnefac, terti,POZplin
WHERE avnefac.subunitate=terti.subunitate 
 and avnefac.Contractul=pozplin.Cont and avnefac.Data=pozplin.data and avnefac.tip='RE' and pozplin.Tert=terti.tert and  pozplin.tert=avnefac.Cod_tert and pozplin.Numar=avnefac.numar
and avnefac.terminal='ASIS' 
GROUP BY pozplin.subunitate,pozplin.suma,pozplin.NUMAR,pozplin.FACTURA,pozplin.DATA,pozplin.TERT,pozplin.loc_de_munca 
--set @maxrand = isnull((select count(*) from ##raspASIS),0)