CREATE TABLE [dbo].[calitatePP] (
    [Subunitate]                    CHAR (9)   NOT NULL,
    [Tip]                           CHAR (2)   NOT NULL,
    [Numar]                         CHAR (8)   NOT NULL,
    [Data]                          DATETIME   NOT NULL,
    [Numar_pozitie]                 INT        NOT NULL,
    [Nr_raport]                     CHAR (13)  NOT NULL,
    [Data_raport]                   DATETIME   NOT NULL,
    [Latime_ST]                     CHAR (12)  NOT NULL,
    [Latime_RA]                     CHAR (12)  NOT NULL,
    [Masa_ST]                       CHAR (12)  NOT NULL,
    [Masa_RA]                       CHAR (12)  NOT NULL,
    [Desime_bat_ST]                 CHAR (12)  NOT NULL,
    [Desime_bat_RA]                 CHAR (12)  NOT NULL,
    [Legatura_de_baza_ST]           CHAR (12)  NOT NULL,
    [Legatura_de_baza_RA]           CHAR (12)  NOT NULL,
    [Finete_urzeala_ST]             CHAR (12)  NOT NULL,
    [Finete_urzeala_RA]             CHAR (12)  NOT NULL,
    [Finete_batatura_ST]            CHAR (12)  NOT NULL,
    [Finete_batatura_RA]            CHAR (12)  NOT NULL,
    [Finete_prindere_ST]            CHAR (12)  NOT NULL,
    [Finete_prindere_RA]            CHAR (12)  NOT NULL,
    [Finete_snur_ST]                CHAR (12)  NOT NULL,
    [Finete_snur_RA]                CHAR (12)  NOT NULL,
    [Fire_in_U_ST]                  CHAR (12)  NOT NULL,
    [Fire_in_U_RA]                  CHAR (12)  NOT NULL,
    [Fire_snur_ST]                  CHAR (12)  NOT NULL,
    [Fire_snur_RA]                  CHAR (12)  NOT NULL,
    [Diagonala_vulst_ST]            CHAR (12)  NOT NULL,
    [Diagonala_vulst_RA]            CHAR (12)  NOT NULL,
    [Sarcina_la_rupere_ST]          CHAR (12)  NOT NULL,
    [Sarcina_la_rupere_RA]          CHAR (12)  NOT NULL,
    [Alungire_ST]                   CHAR (12)  NOT NULL,
    [Alungire_RA]                   CHAR (12)  NOT NULL,
    [Elasticitate_ST]               CHAR (12)  NOT NULL,
    [Elasticitate_RA]               CHAR (12)  NOT NULL,
    [Grosime_ST]                    CHAR (12)  NOT NULL,
    [Grosime_RA]                    CHAR (12)  NOT NULL,
    [Rezistenta_frecare_uscata_ST]  CHAR (12)  NOT NULL,
    [Rezistenta_frecare_uscata_RA]  CHAR (12)  NOT NULL,
    [Rezistenta_apa_rece_ST]        CHAR (12)  NOT NULL,
    [Rezistenta_apa_rece_RA]        CHAR (12)  NOT NULL,
    [Rezistenta_transp_acida_ST]    CHAR (12)  NOT NULL,
    [Rezistenta_transp_acida_RA]    CHAR (12)  NOT NULL,
    [Rezistenta_transp_alcalina_ST] CHAR (12)  NOT NULL,
    [Rezistenta_transp_alcalina_RA] CHAR (12)  NOT NULL,
    [Obs]                           CHAR (200) NOT NULL,
    [Rezultat]                      CHAR (1)   NOT NULL,
    [Nr_declaratie_conf]            CHAR (10)  NOT NULL,
    [Data_declaratie_conf]          DATETIME   NOT NULL,
    [Numar_RPN]                     CHAR (8)   NOT NULL,
    [Data_RPN]                      DATETIME   NOT NULL,
    [Cantitate_inspectata]          FLOAT (53) NOT NULL,
    [Cantitate_neconforma]          FLOAT (53) NOT NULL,
    [Contract]                      CHAR (20)  NOT NULL,
    [Data_comanda]                  DATETIME   NOT NULL,
    [Clauza_contractuala]           CHAR (30)  NOT NULL,
    [Locul_constatarii]             CHAR (1)   NOT NULL,
    [Alt_loc_constatare]            CHAR (10)  NOT NULL,
    [Descriere_neconformitate]      CHAR (500) NOT NULL,
    [Persoana_constatatoare]        CHAR (20)  NOT NULL,
    [Inspector_CI]                  CHAR (20)  NOT NULL,
    [Data_constatarii]              DATETIME   NOT NULL,
    [Tip_masuri_corectie]           CHAR (1)   NOT NULL,
    [Alte_masuri_corectie]          CHAR (15)  NOT NULL,
    [Cauze]                         CHAR (200) NOT NULL,
    [Masuri_corective]              CHAR (500) NOT NULL,
    [Persoana_resp_corectie]        CHAR (20)  NOT NULL,
    [Data_cunostinta_corectie]      DATETIME   NOT NULL,
    [Data_planif_corectie]          DATETIME   NOT NULL,
    [Masuri_preventive]             CHAR (300) NOT NULL,
    [Persoana_resp_preventive]      CHAR (20)  NOT NULL,
    [Data_cunostinta_preventive]    DATETIME   NOT NULL,
    [Data_planif_preventive]        DATETIME   NOT NULL,
    [Concluzii_masuri]              CHAR (300) NOT NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [CalitRM]
    ON [dbo].[calitatePP]([Subunitate] ASC, [Tip] ASC, [Numar] ASC, [Data] ASC, [Numar_pozitie] ASC);


GO
CREATE NONCLUSTERED INDEX [Buletin_RM]
    ON [dbo].[calitatePP]([Subunitate] ASC, [Tip] ASC, [Nr_raport] ASC, [Data_raport] ASC);

