CREATE TABLE [dbo].[CON_CLIENTI] (
    [CLIENT]             VARCHAR (500) NULL,
    [subunitate]         VARCHAR (50)  NULL,
    [tip]                VARCHAR (50)  NULL,
    [contract]           VARCHAR (50)  NULL,
    [cod_fiscal]         VARCHAR (50)  NULL,
    [Punct_livrare]      VARCHAR (50)  NULL,
    [Data]               VARCHAR (50)  NULL,
    [Stare]              VARCHAR (50)  NULL,
    [Loc_de_munca]       VARCHAR (100) NULL,
    [gestiunea]          VARCHAR (50)  NULL,
    [termen livrare]     VARCHAR (50)  NULL,
    [termem plata]       VARCHAR (50)  NULL,
    [Discount]           VARCHAR (50)  NULL,
    [moneda]             VARCHAR (50)  NULL,
    [Curs]               VARCHAR (50)  NULL,
    [Mod plata ]         VARCHAR (50)  NULL,
    [Mod_ambalare]       VARCHAR (50)  NULL,
    [Factura]            CHAR (20)     NOT NULL,
    [target]             VARCHAR (50)  NULL,
    [Total_TVA]          VARCHAR (50)  NULL,
    [Contract_coresp]    VARCHAR (50)  NULL,
    [Mod_penalizare]     VARCHAR (50)  NULL,
    [Procent_penalizare] VARCHAR (50)  NULL,
    [Procent_avans]      VARCHAR (50)  NULL,
    [Avans]              VARCHAR (50)  NULL,
    [Nr_rate]            VARCHAR (50)  NULL,
    [Val_reziduala]      VARCHAR (50)  NULL,
    [Sold_initial]       VARCHAR (50)  NULL,
    [Cod_dobanda]        VARCHAR (50)  NULL,
    [Dobanda]            VARCHAR (50)  NULL,
    [Incasat]            VARCHAR (50)  NULL,
    [Responsabil]        VARCHAR (50)  NULL,
    [Responsabil_tert]   VARCHAR (50)  NULL,
    [Explicatii]         VARCHAR (50)  NULL,
    [Data_rezilierii]    VARCHAR (50)  NULL,
    [limita credit]      VARCHAR (50)  NULL,
    [SIC_CODE]           VARCHAR (50)  NULL,
    [SIC_CODE_TYPE]      VARCHAR (50)  NULL,
    [TAX_REFERENCE]      VARCHAR (50)  NULL,
    [PROVINCE]           VARCHAR (50)  NULL
);

