CREATE TABLE [dbo].[D112angajatorB] (
    [Data]          DATETIME    NULL,
    [B_cnp]         CHAR (6)    NULL,
    [B_sanatate]    CHAR (6)    NULL,
    [B_pensie]      CHAR (5)    NULL,
    [B_brutSalarii] CHAR (15)   NULL,
    [totalPlata_A]  CHAR (15)   NULL,
    [C1_11]         CHAR (15)   NULL,
    [C1_12]         CHAR (15)   NULL,
    [C1_13]         CHAR (15)   NULL,
    [C1_21]         CHAR (15)   NULL,
    [C1_22]         CHAR (15)   NULL,
    [C1_23]         CHAR (15)   NULL,
    [C1_31]         CHAR (15)   NULL,
    [C1_32]         CHAR (15)   NULL,
    [C1_33]         CHAR (15)   NULL,
    [C1_T1]         CHAR (15)   NULL,
    [C1_T2]         CHAR (15)   NULL,
    [C1_T]          CHAR (15)   NULL,
    [C1_T3]         CHAR (15)   NULL,
    [C1_5]          CHAR (15)   NULL,
    [C1_6]          CHAR (15)   NULL,
    [C1_7]          CHAR (15)   NULL,
    [C2_11]         CHAR (6)    NULL,
    [C2_12]         CHAR (5)    NULL,
    [C2_13]         CHAR (5)    NULL,
    [C2_14]         CHAR (5)    NULL,
    [C2_15]         CHAR (15)   NULL,
    [C2_16]         CHAR (15)   NULL,
    [C2_21]         CHAR (6)    NULL,
    [C2_22]         CHAR (5)    NULL,
    [C2_24]         CHAR (5)    NULL,
    [C2_26]         CHAR (15)   NULL,
    [C2_31]         CHAR (6)    NULL,
    [C2_32]         CHAR (5)    NULL,
    [C2_34]         CHAR (5)    NULL,
    [C2_36]         CHAR (15)   NULL,
    [C2_41]         CHAR (6)    NULL,
    [C2_42]         CHAR (5)    NULL,
    [C2_44]         CHAR (5)    NULL,
    [C2_46]         CHAR (15)   NULL,
    [C2_51]         CHAR (6)    NULL,
    [C2_52]         CHAR (5)    NULL,
    [C2_54]         CHAR (5)    NULL,
    [C2_56]         CHAR (15)   NULL,
    [C2_T6]         CHAR (15)   NULL,
    [C2_7]          CHAR (15)   NULL,
    [C2_8]          CHAR (15)   NULL,
    [C2_9]          CHAR (15)   NULL,
    [C2_10]         CHAR (15)   NULL,
    [C2_110]        CHAR (15)   NULL,
    [C2_120]        CHAR (15)   NULL,
    [C2_130]        CHAR (15)   NULL,
    [C3_11]         CHAR (6)    NULL,
    [C3_12]         CHAR (5)    NULL,
    [C3_13]         CHAR (15)   NULL,
    [C3_14]         CHAR (15)   NULL,
    [C3_21]         CHAR (6)    NULL,
    [C3_22]         CHAR (5)    NULL,
    [C3_23]         CHAR (15)   NULL,
    [C3_24]         CHAR (15)   NULL,
    [C3_31]         CHAR (6)    NULL,
    [C3_32]         CHAR (5)    NULL,
    [C3_33]         CHAR (15)   NULL,
    [C3_34]         CHAR (15)   NULL,
    [C3_41]         CHAR (6)    NULL,
    [C3_42]         CHAR (5)    NULL,
    [C3_43]         CHAR (15)   NULL,
    [C3_44]         CHAR (15)   NULL,
    [C3_total]      CHAR (15)   NULL,
    [C3_suma]       CHAR (15)   NULL,
    [C3_aj_nr]      CHAR (15)   NULL,
    [C3_aj_suma]    CHAR (15)   NULL,
    [C4_scutitaSo]  CHAR (15)   NULL,
    [C6_baza]       CHAR (15)   NULL,
    [C6_ct]         CHAR (15)   NULL,
    [C7_baza]       CHAR (15)   NULL,
    [C7_ct]         CHAR (15)   NULL,
    [D1]            CHAR (6)    NULL,
    [E1_venit]      CHAR (15)   NULL,
    [F1_suma]       CHAR (15)   NULL,
    [Loc_de_munca]  VARCHAR (9) DEFAULT (NULL) NULL,
    [B_sal]         VARCHAR (6) DEFAULT (NULL) NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [Data]
    ON [dbo].[D112angajatorB]([Data] ASC, [Loc_de_munca] ASC);

