CREATE TABLE [dbo].[FiseFisc] (
    [An]           SMALLINT   NOT NULL,
    [Versiune]     SMALLINT   NOT NULL,
    [Fisa_fiscala] CHAR (1)   NOT NULL,
    [Marca]        CHAR (6)   NOT NULL,
    [Cod_angajat]  FLOAT (53) NOT NULL,
    [Nume]         CHAR (40)  NOT NULL,
    [Prenume]      CHAR (40)  NOT NULL,
    [Localitate]   CHAR (50)  NOT NULL,
    [Judet]        CHAR (20)  NOT NULL,
    [Strada]       CHAR (50)  NOT NULL,
    [Numar]        CHAR (10)  NOT NULL,
    [Cod_postal]   INT        NOT NULL,
    [Bloc]         CHAR (10)  NOT NULL,
    [Scara]        CHAR (10)  NOT NULL,
    [Etaj]         CHAR (10)  NOT NULL,
    [Ap]           CHAR (10)  NOT NULL,
    [Sector]       SMALLINT   NOT NULL,
    [Rectific]     CHAR (1)   NOT NULL,
    [Regulariz]    CHAR (1)   NOT NULL,
    [Fara_dom]     CHAR (1)   NOT NULL,
    [Alte_surse]   CHAR (1)   NOT NULL,
    [Invalid_I]    CHAR (1)   NOT NULL,
    [Invalid_II]   CHAR (1)   NOT NULL,
    [Alte_sit]     CHAR (1)   NOT NULL,
    [Data_angaj]   DATETIME   NOT NULL,
    [Data_incet]   DATETIME   NOT NULL,
    [Coef_T_01]    REAL       NOT NULL,
    [Coef_T_02]    REAL       NOT NULL,
    [Coef_T_03]    REAL       NOT NULL,
    [Coef_T_04]    REAL       NOT NULL,
    [Coef_T_05]    REAL       NOT NULL,
    [Coef_T_06]    REAL       NOT NULL,
    [Coef_T_07]    REAL       NOT NULL,
    [Coef_T_08]    REAL       NOT NULL,
    [Coef_T_09]    REAL       NOT NULL,
    [Coef_T_10]    REAL       NOT NULL,
    [Coef_T_11]    REAL       NOT NULL,
    [Coef_T_12]    REAL       NOT NULL,
    [Coef_P_01]    REAL       NOT NULL,
    [Coef_P_02]    REAL       NOT NULL,
    [Coef_P_03]    REAL       NOT NULL,
    [Coef_P_04]    REAL       NOT NULL,
    [Coef_P_05]    REAL       NOT NULL,
    [Coef_P_06]    REAL       NOT NULL,
    [Coef_P_07]    REAL       NOT NULL,
    [Coef_P_08]    REAL       NOT NULL,
    [Coef_P_09]    REAL       NOT NULL,
    [Coef_P_10]    REAL       NOT NULL,
    [Coef_P_11]    REAL       NOT NULL,
    [Coef_P_12]    REAL       NOT NULL,
    [Venit_01]     FLOAT (53) NOT NULL,
    [Impozit_01]   FLOAT (53) NOT NULL,
    [Venit_02]     FLOAT (53) NOT NULL,
    [Impozit_02]   FLOAT (53) NOT NULL,
    [Venit_03]     FLOAT (53) NOT NULL,
    [Impozit_03]   FLOAT (53) NOT NULL,
    [Venit_04]     FLOAT (53) NOT NULL,
    [Impozit_04]   FLOAT (53) NOT NULL,
    [Venit_05]     FLOAT (53) NOT NULL,
    [Impozit_05]   FLOAT (53) NOT NULL,
    [Venit_06]     FLOAT (53) NOT NULL,
    [Impozit_06]   FLOAT (53) NOT NULL,
    [Venit_07]     FLOAT (53) NOT NULL,
    [Impozit_07]   FLOAT (53) NOT NULL,
    [Venit_08]     FLOAT (53) NOT NULL,
    [Impozit_08]   FLOAT (53) NOT NULL,
    [Venit_09]     FLOAT (53) NOT NULL,
    [Impozit_09]   FLOAT (53) NOT NULL,
    [Venit_10]     FLOAT (53) NOT NULL,
    [Impozit_10]   FLOAT (53) NOT NULL,
    [Venit_11]     FLOAT (53) NOT NULL,
    [Impozit_11]   FLOAT (53) NOT NULL,
    [Venit_12]     FLOAT (53) NOT NULL,
    [Impozit_12]   FLOAT (53) NOT NULL,
    [Venit_13]     FLOAT (53) NOT NULL,
    [Impozit_13]   FLOAT (53) NOT NULL,
    [Venit_14]     FLOAT (53) NOT NULL,
    [Impozit_14]   FLOAT (53) NOT NULL,
    [Nr_luni]      SMALLINT   NOT NULL,
    [Ch_acord]     FLOAT (53) NOT NULL,
    [Ch_cuven]     FLOAT (53) NOT NULL,
    [Venit_rec]    FLOAT (53) NOT NULL,
    [Deduceri]     FLOAT (53) NOT NULL,
    [Venit_baza]   FLOAT (53) NOT NULL,
    [Imp_anual]    FLOAT (53) NOT NULL,
    [Dif_plata]    FLOAT (53) NOT NULL,
    [Dif_restit]   FLOAT (53) NOT NULL,
    [Venit_fin]    FLOAT (53) NOT NULL,
    [Imp_fin]      FLOAT (53) NOT NULL,
    [Venit_scut]   FLOAT (53) NOT NULL,
    [AS1]          CHAR (1)   NOT NULL,
    [AS2]          CHAR (1)   NOT NULL,
    [AS3]          CHAR (1)   NOT NULL,
    [AS4]          CHAR (1)   NOT NULL,
    [AS5]          CHAR (1)   NOT NULL,
    [AS6]          CHAR (1)   NOT NULL,
    [AS7]          CHAR (1)   NOT NULL,
    [AS8]          CHAR (1)   NOT NULL,
    [Nu_plata]     CHAR (1)   NOT NULL,
    [Pers_mis]     CHAR (1)   NOT NULL,
    [Pers_deced]   CHAR (1)   NOT NULL,
    [Ct_sind_st]   FLOAT (53) NOT NULL,
    [Ct_sind_or]   FLOAT (53) NOT NULL,
    [Cotiz_sind]   FLOAT (53) NOT NULL,
    [Bursa_pl]     FLOAT (53) NOT NULL,
    [Bursa_ad]     FLOAT (53) NOT NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [unic]
    ON [dbo].[FiseFisc]([An] ASC, [Versiune] ASC, [Fisa_fiscala] ASC, [Marca] ASC);


GO
CREATE NONCLUSTERED INDEX [Operare]
    ON [dbo].[FiseFisc]([An] ASC, [Versiune] ASC, [Fisa_fiscala] ASC, [Nume] ASC);


GO
CREATE NONCLUSTERED INDEX [Cnp]
    ON [dbo].[FiseFisc]([An] ASC, [Versiune] ASC, [Fisa_fiscala] ASC, [Cod_angajat] ASC);

