CREATE TABLE [dbo].[insertpozcontmp] (
    [disc]                 REAL       NULL,
    [Subunitate]           CHAR (9)   NULL,
    [Tip]                  CHAR (2)   NULL,
    [Contract]             CHAR (20)  NULL,
    [Tert]                 CHAR (13)  NULL,
    [Punct_livrare]        CHAR (13)  NULL,
    [Data]                 DATETIME   NULL,
    [Cod]                  CHAR (20)  NULL,
    [Cantitate]            FLOAT (53) NULL,
    [Pret]                 FLOAT (53) NULL,
    [Pret_promotional]     FLOAT (53) NULL,
    [Discount]             REAL       NULL,
    [Termen]               DATETIME   NULL,
    [Factura]              CHAR (20)  NULL,
    [Cant_disponibila]     FLOAT (53) NULL,
    [Cant_aprobata]        FLOAT (53) NULL,
    [Cant_realizata]       FLOAT (53) NULL,
    [Valuta]               CHAR (3)   NULL,
    [Cota_TVA]             REAL       NULL,
    [Suma_TVA]             FLOAT (53) NULL,
    [Mod_de_plata]         CHAR (8)   NULL,
    [UM]                   CHAR (1)   NULL,
    [Zi_scadenta_din_luna] SMALLINT   NULL,
    [Explicatii]           CHAR (200) NULL,
    [Numar_pozitie]        INT        NULL,
    [Utilizator]           CHAR (10)  NULL,
    [Data_operarii]        DATETIME   NULL,
    [Ora_operarii]         CHAR (6)   NULL
);

