CREATE TABLE [dbo].[LOCATORI_FINAL] (
    [Column 0]    VARCHAR (50)  NULL,
    [ARTICOL]     VARCHAR (50)  NULL,
    [DESCRIPTION] VARCHAR (200) NULL,
    [STOC]        VARCHAR (50)  NULL,
    [GESTIUNEA]   VARCHAR (50)  NULL,
    [LOCATOR]     VARCHAR (100) NULL
);

