CREATE TABLE [dbo].[POZCON_FURNIZORI] (
    [Subunitate]           BIGINT        NOT NULL,
    [Tip]                  VARCHAR (50)  NULL,
    [Contract]             VARCHAR (50)  NULL,
    [Tert]                 VARCHAR (50)  NULL,
    [Punct_livrare]        VARCHAR (50)  NULL,
    [Data]                 VARCHAR (50)  NULL,
    [Cod]                  VARCHAR (50)  NULL,
    [Cantitate]            VARCHAR (50)  NULL,
    [Pret_]                VARCHAR (50)  NULL,
    [Pret_promotional]     VARCHAR (50)  NULL,
    [Discount]             VARCHAR (50)  NULL,
    [Termen]               VARCHAR (50)  NULL,
    [Factura]              CHAR (20)     NOT NULL,
    [Cant_disponibila]     VARCHAR (50)  NULL,
    [Cant_aprobata]        VARCHAR (50)  NULL,
    [Cant_realizata]       VARCHAR (50)  NULL,
    [Valuta]               VARCHAR (50)  NULL,
    [Cota_TVA]             VARCHAR (50)  NULL,
    [Suma_TVA]             VARCHAR (50)  NULL,
    [Mod_de_plata]         VARCHAR (50)  NULL,
    [UM]                   VARCHAR (50)  NULL,
    [Zi_scadenta_din_luna] VARCHAR (50)  NULL,
    [Explicatii]           VARCHAR (50)  NULL,
    [Numar_pozitie]        VARCHAR (50)  NULL,
    [Utilizator]           VARCHAR (50)  NULL,
    [Data_operarii]        VARCHAR (50)  NULL,
    [Ora_operarii]         VARCHAR (50)  NULL,
    [denumire produs]      VARCHAR (500) NULL,
    [ID]                   INT           IDENTITY (1, 1) NOT NULL
);

