CREATE TABLE [dbo].[STOC_MINIM_PIESE] (
    [BRAND]             VARCHAR (50)  NULL,
    [COD_ARTICOL]       VARCHAR (50)  NULL,
    [DESCRIERE_ARTICOL] VARCHAR (200) NULL,
    [Stoc minim]        VARCHAR (50)  NULL
);

