CREATE TABLE [dbo].[syssmasini] (
    [Host_id]                 CHAR (10) NOT NULL,
    [Host_name]               CHAR (30) NOT NULL,
    [Aplicatia]               CHAR (30) NOT NULL,
    [Data_operarii]           DATETIME  NOT NULL,
    [Utilizator]              CHAR (10) NOT NULL,
    [Tip_act]                 CHAR (1)  NOT NULL,
    [cod_masina]              CHAR (20) NOT NULL,
    [tip_masina]              CHAR (20) NOT NULL,
    [nr_inmatriculare]        CHAR (15) NOT NULL,
    [denumire]                CHAR (40) NOT NULL,
    [nr_inventar]             CHAR (13) NOT NULL,
    [capacitate_metri_cubi]   REAL      NOT NULL,
    [consum_normat_100km]     REAL      NOT NULL,
    [consum_pe_ora]           REAL      NOT NULL,
    [grupa]                   CHAR (20) NOT NULL,
    [loc_de_munca]            CHAR (9)  NOT NULL,
    [coeficient]              REAL      NOT NULL,
    [tonaj]                   REAL      NOT NULL,
    [benzina_sau_motorina]    CHAR (1)  NOT NULL,
    [capacitate_rezervor]     REAL      NOT NULL,
    [capacitate_baie_de_ulei] REAL      NOT NULL,
    [norma_de_ulei]           REAL      NOT NULL,
    [consum_vara]             REAL      NOT NULL,
    [consum_iarna]            REAL      NOT NULL,
    [consum_usor]             REAL      NOT NULL,
    [consum_mediu]            REAL      NOT NULL,
    [consum_greu]             REAL      NOT NULL,
    [km_la_bord_efectivi]     INT       NOT NULL,
    [km_la_bord_echivalenti]  INT       NOT NULL,
    [km_SU]                   INT       NOT NULL,
    [km_RK]                   INT       NOT NULL,
    [km_RT1]                  INT       NOT NULL,
    [km_RT2]                  INT       NOT NULL,
    [ultim_SU]                DATETIME  NOT NULL,
    [ultim_RK]                DATETIME  NOT NULL,
    [ultim_RT1]               DATETIME  NOT NULL,
    [ultim_RT2]               DATETIME  NOT NULL,
    [de_care_masina]          CHAR (1)  NOT NULL,
    [de_putere_mare]          CHAR (1)  NOT NULL,
    [Comanda]                 CHAR (13) NOT NULL,
    [data_expirarii_ITP]      DATETIME  NOT NULL,
    [Firma_CASCO]             CHAR (30) NOT NULL,
    [Serie_caroserie]         CHAR (30) NOT NULL
) ON [SYSS];

