CREATE TABLE [dbo].[sysspa] (
    [Host_id]         CHAR (10)    NOT NULL,
    [Host_name]       CHAR (30)    NOT NULL,
    [Aplicatia]       CHAR (30)    NOT NULL,
    [Data_stergerii]  DATETIME     NOT NULL,
    [Stergator]       CHAR (10)    NOT NULL,
    [Data_operarii]   DATETIME     NOT NULL,
    [Ora_operarii]    CHAR (6)     NOT NULL,
    [Subunitate]      CHAR (9)     NOT NULL,
    [Numar_document]  CHAR (8)     NOT NULL,
    [Data]            DATETIME     NOT NULL,
    [Tert]            CHAR (13)    NOT NULL,
    [Tip]             CHAR (2)     NOT NULL,
    [Factura_stinga]  CHAR (20)    NOT NULL,
    [Factura_dreapta] CHAR (20)    NOT NULL,
    [Cont_deb]        VARCHAR (20) NULL,
    [Cont_cred]       VARCHAR (20) NULL,
    [Suma]            FLOAT (53)   NOT NULL,
    [TVA11]           FLOAT (53)   NOT NULL,
    [TVA22]           FLOAT (53)   NOT NULL,
    [Utilizator]      CHAR (10)    NOT NULL,
    [Numar_pozitie]   INT          NOT NULL,
    [Tert_beneficiar] CHAR (13)    NOT NULL,
    [Explicatii]      CHAR (50)    NOT NULL,
    [Valuta]          CHAR (3)     NOT NULL,
    [Curs]            FLOAT (53)   NOT NULL,
    [Suma_valuta]     FLOAT (53)   NOT NULL,
    [Cont_dif]        VARCHAR (20) NULL,
    [suma_dif]        FLOAT (53)   NOT NULL,
    [Loc_munca]       CHAR (9)     NOT NULL,
    [Comanda]         CHAR (40)    NOT NULL,
    [Data_fact]       DATETIME     NOT NULL,
    [Data_scad]       DATETIME     NOT NULL,
    [Stare]           SMALLINT     NOT NULL,
    [Achit_fact]      FLOAT (53)   NOT NULL,
    [Dif_TVA]         FLOAT (53)   NOT NULL,
    [Jurnal]          CHAR (3)     NOT NULL
) ON [SYSS];

