CREATE TABLE [dbo].[sysscoef] (
    [Host_id]                  CHAR (10)  NOT NULL,
    [Host_name]                CHAR (30)  NOT NULL,
    [Aplicatia]                CHAR (30)  NOT NULL,
    [Data_operarii]            DATETIME   NOT NULL,
    [Utilizator]               CHAR (10)  NOT NULL,
    [Tip_act]                  CHAR (1)   NOT NULL,
    [Tip]                      CHAR (3)   NOT NULL,
    [Cod_deviz]                CHAR (20)  NOT NULL,
    [Data]                     DATETIME   NOT NULL,
    [Valoare_material]         FLOAT (53) NOT NULL,
    [Valoare_manopera]         FLOAT (53) NOT NULL,
    [Valoare_utilaj]           FLOAT (53) NOT NULL,
    [Transport_auto]           FLOAT (53) NOT NULL,
    [Transport_CFR]            FLOAT (53) NOT NULL,
    [Manopera_utilaje]         FLOAT (53) NOT NULL,
    [Manopera_transport]       FLOAT (53) NOT NULL,
    [Manopera_indirecta]       FLOAT (53) NOT NULL,
    [Retributie_maistri]       FLOAT (53) NOT NULL,
    [Impozit]                  FLOAT (53) NOT NULL,
    [Somaj]                    FLOAT (53) NOT NULL,
    [CAS]                      FLOAT (53) NOT NULL,
    [Asigurari_sanatate]       FLOAT (53) NOT NULL,
    [Fond_de_risc]             FLOAT (53) NOT NULL,
    [Cheltuieli_aprovizionare] FLOAT (53) NOT NULL,
    [Procent_indirecte]        FLOAT (53) NOT NULL,
    [Cheltuieli_indirecte]     FLOAT (53) NOT NULL,
    [Cercetare_dezvoltare]     FLOAT (53) NOT NULL,
    [Profit]                   FLOAT (53) NOT NULL,
    [Chelt_frig]               FLOAT (53) NOT NULL,
    [Organizare_santier]       FLOAT (53) NOT NULL,
    [Plaja_de_ofertare]        FLOAT (53) NOT NULL,
    [Fond_CSC]                 FLOAT (53) NOT NULL,
    [Cota_TVA]                 SMALLINT   NOT NULL,
    [Transp_punct]             FLOAT (53) NOT NULL
) ON [SYSS];

