CREATE TABLE [dbo].[syssWebConfigForm] (
    [LogId]            INT            IDENTITY (1, 1) NOT NULL,
    [user_name]        VARCHAR (100)  NULL,
    [host_name]        VARCHAR (1000) NULL,
    [program_name]     VARCHAR (1000) NULL,
    [tip_operatie]     VARCHAR (1000) NULL,
    [data_modificarii] DATETIME       NULL,
    [Meniu]            VARCHAR (20)   NOT NULL,
    [Tip]              VARCHAR (2)    NULL,
    [Subtip]           VARCHAR (2)    NULL,
    [Ordine]           INT            NULL,
    [Nume]             VARCHAR (50)   NULL,
    [TipObiect]        VARCHAR (50)   NULL,
    [DataField]        VARCHAR (50)   NULL,
    [LabelField]       VARCHAR (50)   NULL,
    [Latime]           INT            NULL,
    [Vizibil]          BIT            NULL,
    [Modificabil]      BIT            NULL,
    [ProcSQL]          VARCHAR (50)   NULL,
    [ListaValori]      VARCHAR (100)  NULL,
    [ListaEtichete]    VARCHAR (600)  NULL,
    [Initializare]     VARCHAR (50)   NULL,
    [Prompt]           VARCHAR (50)   NULL,
    [Procesare]        VARCHAR (50)   NULL,
    [Tooltip]          VARCHAR (500)  NULL,
    [formula]          VARCHAR (MAX)  NULL,
    [detalii]          XML            NULL,
    CONSTRAINT [PK__syssWebC__5E54864824547528] PRIMARY KEY CLUSTERED ([LogId] ASC) ON [SYSS]
);

