CREATE TABLE [dbo].[sysspdev] (
    [Host_id]             CHAR (10)       NOT NULL,
    [Host_name]           CHAR (30)       NOT NULL,
    [Aplicatia]           CHAR (30)       NOT NULL,
    [Data_operarii]       DATETIME        NOT NULL,
    [Utilizator]          CHAR (10)       NOT NULL,
    [Tip_act]             CHAR (1)        NOT NULL,
    [Cod_deviz]           CHAR (20)       NOT NULL,
    [Pozitie_articol]     SMALLINT        NOT NULL,
    [Tip_articol]         CHAR (1)        NOT NULL,
    [Cod_articol]         CHAR (20)       NOT NULL,
    [Expandat]            BINARY (1)      NOT NULL,
    [Cantitate_articol]   FLOAT (53)      NOT NULL,
    [Pret_articol]        FLOAT (53)      NOT NULL,
    [Tip_resursa]         CHAR (1)        NOT NULL,
    [Cod_resursa]         CHAR (20)       NOT NULL,
    [Cantitate_resursa]   FLOAT (53)      NOT NULL,
    [Pret_resursa]        FLOAT (53)      NOT NULL,
    [Cod_corespondent]    CHAR (20)       NOT NULL,
    [Subcapitol]          CHAR (9)        NOT NULL,
    [Furnizor]            CHAR (13)       NOT NULL,
    [Data_lansarii]       DATETIME        NOT NULL,
    [Data_inchiderii]     DATETIME        NOT NULL,
    [Coeficient_manopera] FLOAT (53)      NOT NULL,
    [Coeficient_resurse]  NUMERIC (16, 6) NOT NULL,
    [Comasare]            CHAR (20)       NOT NULL,
    [Alfa1]               CHAR (20)       NOT NULL,
    [Alfa2]               CHAR (20)       NOT NULL,
    [Utilizator_dev]      CHAR (10)       NOT NULL,
    [Data_operarii_dev]   DATETIME        NOT NULL,
    [Ora_operarii]        CHAR (6)        NOT NULL
) ON [SYSS];

