CREATE TABLE [dbo].[tehnpoz_coduri_mari] (
    [Cod_tehn]     CHAR (30)  NOT NULL,
    [Tip]          CHAR (1)   NOT NULL,
    [Cod]          CHAR (30)  NOT NULL,
    [Cod_operatie] CHAR (20)  NOT NULL,
    [Nr]           FLOAT (53) NOT NULL,
    [Subtip]       CHAR (1)   NOT NULL,
    [Supr]         FLOAT (53) NOT NULL,
    [Coef_consum]  FLOAT (53) NOT NULL,
    [Randament]    FLOAT (53) NOT NULL,
    [Specific]     FLOAT (53) NOT NULL,
    [Cod_inlocuit] CHAR (30)  NOT NULL,
    [Loc_munca]    CHAR (20)  NOT NULL,
    [Obs]          CHAR (200) NOT NULL,
    [Utilaj]       CHAR (20)  NOT NULL,
    [Timp_preg]    FLOAT (53) NOT NULL,
    [Timp_util]    FLOAT (53) NOT NULL,
    [Categ_salar]  CHAR (20)  NOT NULL,
    [Norma_timp]   FLOAT (53) NOT NULL,
    [Tarif_unitar] FLOAT (53) NOT NULL,
    [Lungime]      FLOAT (53) NOT NULL,
    [Latime]       FLOAT (53) NOT NULL,
    [Inaltime]     FLOAT (53) NOT NULL,
    [Comanda]      CHAR (20)  NOT NULL,
    [Alfa1]        CHAR (20)  NOT NULL,
    [Alfa2]        CHAR (20)  NOT NULL,
    [Alfa3]        CHAR (20)  NOT NULL,
    [Alfa4]        CHAR (20)  NOT NULL,
    [Alfa5]        CHAR (20)  NOT NULL,
    [Val1]         FLOAT (53) NOT NULL,
    [Val2]         FLOAT (53) NOT NULL,
    [Val3]         FLOAT (53) NOT NULL,
    [Val4]         FLOAT (53) NOT NULL,
    [Val5]         FLOAT (53) NOT NULL
);

