CREATE TABLE [dbo].[TEMP_5365142] (
    [FLD1] CHAR (2)   NOT NULL,
    [FLD2] CHAR (8)   NOT NULL,
    [FLD3] DATETIME   NOT NULL,
    [FLD4] FLOAT (53) NOT NULL,
    [FLD5] FLOAT (53) NOT NULL,
    [FLD6] FLOAT (53) NOT NULL,
    [FLD7] CHAR (13)  NOT NULL,
    [FLD8] CHAR (9)   NOT NULL,
    [FLD9] CHAR (13)  NOT NULL,
    [TS]   ROWVERSION NOT NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [KEY_TSTEMP_5365142]
    ON [dbo].[TEMP_5365142]([TS] ASC);

