CREATE TABLE [dbo].[TEMP_1858244] (
    [FLD1]  DATETIME   NOT NULL,
    [FLD2]  CHAR (6)   NOT NULL,
    [FLD3]  CHAR (10)  NOT NULL,
    [FLD4]  CHAR (9)   NOT NULL,
    [FLD5]  CHAR (20)  NOT NULL,
    [FLD6]  FLOAT (53) NOT NULL,
    [FLD7]  FLOAT (53) NOT NULL,
    [FLD8]  REAL       NOT NULL,
    [FLD9]  REAL       NOT NULL,
    [FLD10] FLOAT (53) NOT NULL,
    [FLD11] DATETIME   NOT NULL,
    [FLD12] FLOAT (53) NOT NULL,
    [FLD13] CHAR (50)  NOT NULL,
    [TS]    ROWVERSION NOT NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [KEY_TSTEMP_1858244]
    ON [dbo].[TEMP_1858244]([TS] ASC);

