CREATE TABLE [dbo].[TEMP_7471325] (
    [TMPFLD1]  CHAR (10)  NOT NULL,
    [TMPFLD2]  DATETIME   NOT NULL,
    [TMPFLD3]  CHAR (2)   NOT NULL,
    [TMPFLD4]  CHAR (8)   NOT NULL,
    [TMPFLD5]  CHAR (20)  NOT NULL,
    [TMPFLD6]  DATETIME   NOT NULL,
    [TMPFLD7]  CHAR (9)   NOT NULL,
    [TMPFLD8]  FLOAT (53) NOT NULL,
    [TMPFLD9]  FLOAT (53) NOT NULL,
    [TMPFLD10] FLOAT (53) NOT NULL,
    [TMPFLD11] CHAR (13)  NOT NULL,
    [TMPFLD12] CHAR (9)   NOT NULL,
    [TMPFLD13] CHAR (40)  NOT NULL,
    [TMPFLD14] CHAR (3)   NOT NULL,
    [TMPFLD15] DATETIME   NOT NULL,
    [TS]       ROWVERSION NOT NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [KEY_TSTEMP_7471325]
    ON [dbo].[TEMP_7471325]([TS] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [KEY001TEMP_7471325]
    ON [dbo].[TEMP_7471325]([TMPFLD15] DESC, [TS] ASC);

