CREATE TABLE [dbo].[tmp_proforma] (
    [pret2]          FLOAT (53)       NULL,
    [discTot1]       NUMERIC (38, 6)  NULL,
    [cotva]          NUMERIC (21, 8)  NULL,
    [pretdiscoritva] NUMERIC (38, 6)  NULL,
    [pretCuTvaDisc2] NUMERIC (38, 6)  NULL,
    [discTot2]       NUMERIC (38, 6)  NULL,
    [pretCuTva]      NUMERIC (38, 6)  NULL,
    [pretCuTva2]     NUMERIC (38, 6)  NULL,
    [CotaTVA]        NUMERIC (21, 8)  NULL,
    [pretFrTva]      NUMERIC (38, 20) NULL,
    [Discount]       REAL             NULL,
    [DiscDoi]        DECIMAL (12, 2)  NULL,
    [DiscTrei]       DECIMAL (12, 2)  NULL,
    [TOTALCTVAC]     FLOAT (53)       NULL,
    [TOTALCTVA]      VARCHAR (16)     NULL,
    [DISCPOZ]        VARCHAR (15)     NULL,
    [TOTAL]          VARCHAR (16)     NULL,
    [valFrTva]       NUMERIC (38, 6)  NULL,
    [UNITATE]        VARCHAR (200)    NULL,
    [CUI]            VARCHAR (200)    NULL,
    [ORDREG]         VARCHAR (200)    NULL,
    [ADR]            VARCHAR (200)    NULL,
    [CONT]           VARCHAR (200)    NULL,
    [BANCA]          VARCHAR (200)    NULL,
    [NUMAR]          VARCHAR (20)     NULL,
    [CODFISC]        VARCHAR (16)     NULL,
    [JUDETTERT]      VARCHAR (20)     NULL,
    [LOCTERT]        VARCHAR (35)     NULL,
    [BANCATERT]      VARCHAR (20)     NULL,
    [CONTTERT]       VARCHAR (35)     NULL,
    [TERT]           VARCHAR (40)     NULL,
    [ADRESATERT]     VARCHAR (60)     NULL,
    [DATA]           VARCHAR (12)     NULL,
    [COMANDA]        VARCHAR (20)     NULL,
    [VALUTA]         VARCHAR (3)      NULL,
    [PCLUCRU]        VARCHAR (43)     NULL,
    [CURS]           VARCHAR (16)     NULL,
    [NUMARRAND]      VARCHAR (24)     NULL,
    [NR]             VARCHAR (24)     NULL,
    [TVALINIE]       VARCHAR (15)     NULL,
    [COD]            VARCHAR (20)     NULL,
    [DISC]           VARCHAR (15)     NULL,
    [DENUMIRE]       VARCHAR (171)    NULL,
    [UM]             VARCHAR (3)      NULL,
    [CANT]           VARCHAR (15)     NULL,
    [PRETBAZA]       VARCHAR (15)     NULL,
    [PRETDISCUNU]    VARCHAR (15)     NULL,
    [PRETDISCDOI]    VARCHAR (15)     NULL,
    [PRET]           VARCHAR (16)     NULL,
    [AVANS]          VARCHAR (15)     NULL,
    [DELEGAT]        VARCHAR (30)     NULL,
    [EMAIL]          VARCHAR (200)    NULL,
    [DISCTOT]        VARCHAR (15)     NULL,
    [TOTRONFARATVA]  VARCHAR (16)     NULL,
    [TOTRONTVA]      VARCHAR (16)     NULL,
    [TOTRONCUTVA]    VARCHAR (16)     NULL
);

