 alter  table misMF enable trigger misMFsterg 
 alter  table elemente enable trigger elemsterg 
 alter  table tipmasini enable trigger tipmassterg 
 alter  table elemtipm enable trigger elemtmsterg 
 alter  table utilizatori enable trigger wTrigRia 
 alter  table facturi enable trigger yso_tr_validFacturi 
 alter  table facturi enable trigger tr_validFacturi 
 alter  table coefmasini enable trigger coefmsterg 
 alter  table pozplin enable trigger plinfac 
 alter  table pozplin enable trigger plininc 
 alter  table pozplin enable trigger plinTinc 
 alter  table pozplin enable trigger plinTxinc 
 alter  table pozplin enable trigger plinefect 
 alter  table pozplin enable trigger plindec 
 alter  table pozplin enable trigger plinantet 
 alter  table pozplin enable trigger pozplinsterg 
 alter  table incfact enable trigger incplin 
 alter  table bp enable trigger yso_bpsterg 
 alter  table terti enable trigger tertisterg 
 alter  table infoPers enable trigger tr_validInfopers 
 alter  table conturi enable trigger tr_validConturi 
 alter  table conturi enable trigger conturisterg 
 alter  table nomencl enable trigger nomenclsterg 
 alter  table nomencl enable trigger yso_insnomencl 
 alter  table doc enable trigger yso_docsterg 
 alter  table con enable trigger DelExtcon 
 alter  table con enable trigger consterg 
 alter  table benret enable trigger tr_validBenret 
 alter  table DVI enable trigger DVIfac 
 alter  table tipret enable trigger tr_validTipret 
 alter  table pozdoc enable trigger yso_tr_ValidPozdoc 
 alter  table pozdoc enable trigger tr_ValidPozdoc 
 alter  table pozdoc enable trigger pozdocsterg 
 alter  table pozdoc enable trigger doccontr 
 alter  table pozdoc enable trigger docantet 
 alter  table pozdoc enable trigger docdec 
 alter  table pozdoc enable trigger docfac 
 alter  table pozdoc enable trigger docfacav 
 alter  table pozdoc enable trigger realizpozprod 
 alter  table pozdoc enable trigger docMfix 
 alter  table pozdoc enable trigger docstoc 
 alter  table pozdoc enable trigger docXstoc 
 alter  table pozdoc enable trigger docFinc 
 alter  table pozdoc enable trigger docFxinc 
 alter  table pozdoc enable trigger docMinc 
 alter  table pozdoc enable trigger docNinc 
 alter  table pozdoc enable trigger docdefinitiv 
 alter  table pozdoc enable trigger doclunastc 
 alter  table pozdoc enable trigger docAinc 
 alter  table pozdoc enable trigger docAxinc 
 alter  table pozdoc enable trigger docBinc 
 alter  table pozdoc enable trigger docBxinc 
 alter  table pozdoc enable trigger docDinc 
 alter  table pozdoc enable trigger docDxinc 
 alter  table pozdoc enable trigger docRinc 
 alter  table pozdoc enable trigger docTinc 
 alter  table pozdoc enable trigger docTxinc 
 alter  table pozdoc enable trigger docTxyinc 
 alter  table pozdoc enable trigger docXinc 
 alter  table pozdoc enable trigger docXyinc 
 alter  table pozdoc enable trigger docXzinc 
 alter  table resal enable trigger resalsterg 
 alter  table resal enable trigger tr_ValidResal 
 alter  table resal enable trigger resalLmExp 
 alter  table resal enable trigger resallunai 
 alter  table lansman enable trigger lansmansterg 
 alter  table pozadoc enable trigger adocinc 
 alter  table pozadoc enable trigger adocXinc 
 alter  table pozadoc enable trigger adocXyinc 
 alter  table pozadoc enable trigger adocfacst 
 alter  table pozadoc enable trigger pozadocsterg 
 alter  table pozadoc enable trigger adocfacdr 
 alter  table pozadoc enable trigger adocantet 
 alter  table pozadoc enable trigger tr_ValidPozadoc 
 alter  table pontaj enable trigger pontajLmExp 
 alter  table pontaj enable trigger pontajlunai 
 alter  table pontaj enable trigger tr_ValidPontaj 
 alter  table pontaj enable trigger pontajsterg 
 alter  table lm enable trigger lmsterg 
 alter  table lansmat enable trigger lansmatsterg 
 alter  table Infopontaj enable trigger infopontajLmExp 
 alter  table Infopontaj enable trigger infopontajlunai 
 alter  table gestiuni enable trigger gestiunisterg 
 alter  table avexcep enable trigger avexceplunai 
 alter  table avexcep enable trigger avexcepsterg 
 alter  table avexcep enable trigger tr_ValidAvexcep 
 alter  table conmed enable trigger conmedsterg 
 alter  table conmed enable trigger conmedLmExp 
 alter  table conmed enable trigger conmedlunai 
 alter  table conmed enable trigger tr_ValidConmed 
 alter  table comenzi enable trigger delcompozprod 
 alter  table comenzi enable trigger comenzisterg 
 alter  table ConcOdih enable trigger concodihsterg 
 alter  table ConcOdih enable trigger tr_ValidConcodih 
 alter  table ConcOdih enable trigger concodihLmExp 
 alter  table ConcOdih enable trigger concodihlunai 
 alter  table corectii enable trigger corectiiLmExp 
 alter  table corectii enable trigger corectiilunai 
 alter  table corectii enable trigger tr_ValidCorectii 
 alter  table corectii enable trigger corectiisterg 
 alter  table personal enable trigger tr_validPersonal 
 alter  table personal enable trigger personalsterg 
 alter  table indicatori enable trigger tr_modifind 
 alter  table functii enable trigger tr_validFunctii 
 alter  table grupe enable trigger yso_grupesterg 
 alter  table persintr enable trigger tr_ValidPersintr 
 alter  table persintr enable trigger persintrlunai 
 alter  table Extinfop enable trigger tr_ValidExtinfop 
 alter  table tichete enable trigger tr_ValidTichete 
 alter  table tichete enable trigger ticheteLmExp 
 alter  table tichete enable trigger tichetelunai 
 alter  table tichete enable trigger tichetesterg 
 alter  table activitati enable trigger activsterg 
 alter  table pozactivitati enable trigger pozactivsterg 
 alter  table elemactivitati enable trigger elemactivsterg 
 alter  table tehn enable trigger yso_instehncomenzi 
 alter  table tehnpoz enable trigger yso_instehnpozcom 
 alter  table MFix enable trigger MFixsterg 
 alter  table infoconmed enable trigger infoconmedlunai 
 alter  table infoconmed enable trigger tr_ValidInfoconmed 
 alter  table conalte enable trigger conaltelunai 
 alter  table conalte enable trigger conaltesterg 
 alter  table conalte enable trigger tr_ValidConalte 
 alter  table preturi enable trigger preturisterg 
 alter  table realcom enable trigger tr_validRealcom 
 alter  table realcom enable trigger realcominch 
 alter  table realcom enable trigger realcomsterg 
 alter  table SalariiZilieri enable trigger SalariiZilierilunai 
 alter  table Termene enable trigger termsterg 
 alter  table pozcon enable trigger yso_ins_pozcon 
 alter  table pozcon enable trigger yso_delpozconexp 
 alter  table pozcon enable trigger yso_tr_validPozcon 
 alter  table pozcon enable trigger livrpozprod 
 alter  table pozcon enable trigger delpozprod 
 alter  table pozcon enable trigger cantcon 
 alter  table pozcon enable trigger pozconsterg 
 alter  table pozcon enable trigger cantpozaprov 
 alter  table pozcon enable trigger delpozaprov 
 alter  table catop enable trigger catopsterg 
 alter  table pozncon enable trigger nconant 
 alter  table pozncon enable trigger nconinc 
 alter  table pozncon enable trigger poznconsterg 
 alter  table extpozplin enable trigger extplinef 
 alter  table extpozplin enable trigger extplindec 
 alter  table penalizarifact enable trigger penalizarifact_modific 
 alter  table incrate enable trigger RATEPLIN 
 alter  table rulaje enable trigger rulajeinisterg 
 alter  table pozincon enable trigger inconant 
 alter  table pozincon enable trigger IncRul 
 alter  table pozincon enable trigger inconLmExp 
 alter  table pozincon enable trigger inconlunai 
 alter  table pozincon enable trigger tr_ValidPozincon 
 alter  table par enable trigger paramsterg 