--select Cont_intermediar,*
--update p set Cont_intermediar='371.0'
--from pozdoc p
--where tip='AP' and data between '07/01/2014' and '08/31/2014' 
--and gestiune_primitoare not like '378%'  and gestiune_primitoare<>'' and Cont_intermediar=''
